export type { AdminControllerAddTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-add-task";
export type { AdminControllerApproveUserTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-approve-user-task";
export type { AdminControllerCreateCampaignMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-create-campaign";
export type { AdminControllerDeleteCampaignMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-delete-campaign";
export type { AdminControllerRejectUserTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-reject-user-task";
export type { AdminControllerRemoveTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-remove-task";
export type { AdminControllerUpdateCampaignMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-update-campaign";
export type { AdminControllerUpdateTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-update-task";
export { adminControllerAddTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-add-task";
export { adminControllerAddTaskMutationOptions } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-add-task";
export { useAdminControllerAddTask } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-add-task";
export { adminControllerApproveUserTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-approve-user-task";
export { adminControllerApproveUserTaskMutationOptions } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-approve-user-task";
export { useAdminControllerApproveUserTask } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-approve-user-task";
export { adminControllerCreateCampaignMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-create-campaign";
export { adminControllerCreateCampaignMutationOptions } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-create-campaign";
export { useAdminControllerCreateCampaign } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-create-campaign";
export { adminControllerDeleteCampaignMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-delete-campaign";
export { adminControllerDeleteCampaignMutationOptions } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-delete-campaign";
export { useAdminControllerDeleteCampaign } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-delete-campaign";
export { adminControllerRejectUserTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-reject-user-task";
export { adminControllerRejectUserTaskMutationOptions } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-reject-user-task";
export { useAdminControllerRejectUserTask } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-reject-user-task";
export { adminControllerRemoveTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-remove-task";
export { adminControllerRemoveTaskMutationOptions } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-remove-task";
export { useAdminControllerRemoveTask } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-remove-task";
export { adminControllerUpdateCampaignMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-update-campaign";
export { adminControllerUpdateCampaignMutationOptions } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-update-campaign";
export { useAdminControllerUpdateCampaign } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-update-campaign";
export { adminControllerUpdateTaskMutationKey } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-update-task";
export { adminControllerUpdateTaskMutationOptions } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-update-task";
export { useAdminControllerUpdateTask } from "@/gen-quest/hooks/admin-hooks/use-admin-controller-update-task";