/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface AccountControllerGetPositionPathParams {
  publicKey: string;
}

export type AccountControllerGetPosition200 = {};

export type AccountControllerGetPositionQueryResponse = {};

export type AccountControllerGetPositionQuery = {};
