/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeployAccountDto } from "@/gen-backend/types/deploy-account-dto";

export type AccountControllerBuildSetupTxs201 = any;

export type AccountControllerBuildSetupTxsMutationRequest = DeployAccountDto;

export type AccountControllerBuildSetupTxsMutationResponse = AccountControllerBuildSetupTxs201;

export type AccountControllerBuildSetupTxsMutation = {
    Response: AccountControllerBuildSetupTxs201;
    Request: AccountControllerBuildSetupTxsMutationRequest;
    Errors: any;
};