/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AccountControllerGetPositionPathParams = {
    /**
     * @type string
    */
    publicKey: string;
};

export type AccountControllerGetPosition200 = any;

export type AccountControllerGetPositionQueryResponse = AccountControllerGetPosition200;

export type AccountControllerGetPositionQuery = {
    Response: AccountControllerGetPosition200;
    PathParams: AccountControllerGetPositionPathParams;
    Errors: any;
};