/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeployAccountDto } from "@/gen-backend/types/deploy-account-dto";

export type AccountControllerBuildDeployTx201 = any;

export type AccountControllerBuildDeployTxMutationRequest = DeployAccountDto;

export type AccountControllerBuildDeployTxMutationResponse = AccountControllerBuildDeployTx201;

export type AccountControllerBuildDeployTxMutation = {
    Response: AccountControllerBuildDeployTx201;
    Request: AccountControllerBuildDeployTxMutationRequest;
    Errors: any;
};