/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeployAccountDto } from "@/gen-backend/types/deploy-account-dto";

export type AccountControllerBuildRevokeTx201 = any;

export type AccountControllerBuildRevokeTxMutationRequest = DeployAccountDto;

export type AccountControllerBuildRevokeTxMutationResponse = AccountControllerBuildRevokeTx201;

export type AccountControllerBuildRevokeTxMutation = {
    Response: AccountControllerBuildRevokeTx201;
    Request: AccountControllerBuildRevokeTxMutationRequest;
    Errors: any;
};