/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FundAccountDto } from "@/gen-backend/types/fund-account-dto";

export type AccountControllerBuildFundTx201 = any;

export type AccountControllerBuildFundTxMutationRequest = FundAccountDto;

export type AccountControllerBuildFundTxMutationResponse = AccountControllerBuildFundTx201;

export type AccountControllerBuildFundTxMutation = {
    Response: AccountControllerBuildFundTx201;
    Request: AccountControllerBuildFundTxMutationRequest;
    Errors: any;
};