/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ActivityControllerReplayPathParams = {
    /**
     * @type string
    */
    decisionId: string;
};

export const activityControllerReplay200NetworkEnum = {
    testnet: "testnet",
    mainnet: "mainnet"
} as const;

export type ActivityControllerReplay200NetworkEnumKey = (typeof activityControllerReplay200NetworkEnum)[keyof typeof activityControllerReplay200NetworkEnum];

export type ActivityControllerReplay200 = {
    /**
     * @type string
    */
    decisionId: string;
    /**
     * @type string
    */
    accountId: string;
    network: ActivityControllerReplay200NetworkEnumKey;
    /**
     * @type array
    */
    stages: object[];
    /**
     * @type boolean
    */
    chainValid: boolean;
    /**
     * @type string
    */
    recomputedRoot: string;
    /**
     * @type string
    */
    finalTx?: string | null;
    /**
     * @type string
    */
    finalTxExplorer?: string | null;
};

export type ActivityControllerReplayQueryResponse = ActivityControllerReplay200;

export type ActivityControllerReplayQuery = {
    Response: ActivityControllerReplay200;
    PathParams: ActivityControllerReplayPathParams;
    Errors: any;
};