/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarkPayoutDto } from "@/gen-backend/types/mark-payout-dto";

export type AdminSeasonsControllerMarkPayoutPathParams = {
    /**
     * @type string
    */
    id: string;
};

export type AdminSeasonsControllerMarkPayout200 = any;

export type AdminSeasonsControllerMarkPayoutMutationRequest = MarkPayoutDto;

export type AdminSeasonsControllerMarkPayoutMutationResponse = AdminSeasonsControllerMarkPayout200;

export type AdminSeasonsControllerMarkPayoutMutation = {
    Response: AdminSeasonsControllerMarkPayout200;
    Request: AdminSeasonsControllerMarkPayoutMutationRequest;
    PathParams: AdminSeasonsControllerMarkPayoutPathParams;
    Errors: any;
};