/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface AdminControllerRevokeCodePathParams {
  id: string;
}

export type AdminControllerRevokeCode200 = {};

export type AdminControllerRevokeCodeMutationResponse = {};

export type AdminControllerRevokeCodeMutation = {};
