/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateFomoEventDto } from "@/gen-backend/types/create-fomo-event-dto";

export type AdminControllerCreateFomoEvent201 = any;

export type AdminControllerCreateFomoEventMutationRequest = CreateFomoEventDto;

export type AdminControllerCreateFomoEventMutationResponse = AdminControllerCreateFomoEvent201;

export type AdminControllerCreateFomoEventMutation = {
    Response: AdminControllerCreateFomoEvent201;
    Request: AdminControllerCreateFomoEventMutationRequest;
    Errors: any;
};