/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateGiftDto } from "@/gen-backend/types/create-gift-dto";

export type AdminControllerCreateGift201 = any;

export type AdminControllerCreateGiftMutationRequest = CreateGiftDto;

export type AdminControllerCreateGiftMutationResponse = AdminControllerCreateGift201;

export type AdminControllerCreateGiftMutation = {
    Response: AdminControllerCreateGift201;
    Request: AdminControllerCreateGiftMutationRequest;
    Errors: any;
};