/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TransactionsStatsDto } from "@/gen-backend/types/transactions-stats-dto";

export type AdminControllerGetTransactionsStatsQueryParams = {
    /**
     * @type string | undefined
    */
    to?: string;
    /**
     * @type string | undefined
    */
    from?: string;
};

export type AdminControllerGetTransactionsStats200 = TransactionsStatsDto;

export type AdminControllerGetTransactionsStatsQueryResponse = AdminControllerGetTransactionsStats200;

export type AdminControllerGetTransactionsStatsQuery = {
    Response: AdminControllerGetTransactionsStats200;
    QueryParams: AdminControllerGetTransactionsStatsQueryParams;
    Errors: any;
};