/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerDeleteFomoEventPathParams = {
    /**
     * @type string
    */
    id: string;
};

export type AdminControllerDeleteFomoEvent200 = any;

export type AdminControllerDeleteFomoEventMutationResponse = AdminControllerDeleteFomoEvent200;

export type AdminControllerDeleteFomoEventMutation = {
    Response: AdminControllerDeleteFomoEvent200;
    PathParams: AdminControllerDeleteFomoEventPathParams;
    Errors: any;
};