/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerListCampaigns200 = any;

export type AdminControllerListCampaignsQueryResponse = AdminControllerListCampaigns200;

export type AdminControllerListCampaignsQuery = {
    Response: AdminControllerListCampaigns200;
    Errors: any;
};