/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateFomoEventDto } from "@/gen-backend/types/update-fomo-event-dto";

export type AdminControllerUpdateFomoEventPathParams = {
    /**
     * @type string
    */
    id: string;
};

export type AdminControllerUpdateFomoEvent200 = any;

export type AdminControllerUpdateFomoEventMutationRequest = UpdateFomoEventDto;

export type AdminControllerUpdateFomoEventMutationResponse = AdminControllerUpdateFomoEvent200;

export type AdminControllerUpdateFomoEventMutation = {
    Response: AdminControllerUpdateFomoEvent200;
    Request: AdminControllerUpdateFomoEventMutationRequest;
    PathParams: AdminControllerUpdateFomoEventPathParams;
    Errors: any;
};