/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerUpdateWaitlistEntryPathParams = {
    /**
     * @type string
    */
    id: string;
};

export type AdminControllerUpdateWaitlistEntry200 = any;

export type AdminControllerUpdateWaitlistEntryMutationResponse = AdminControllerUpdateWaitlistEntry200;

export type AdminControllerUpdateWaitlistEntryMutation = {
    Response: AdminControllerUpdateWaitlistEntry200;
    PathParams: AdminControllerUpdateWaitlistEntryPathParams;
    Errors: any;
};