/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateTaskDto } from "@/gen-backend/types/create-task-dto";

export type AdminControllerAddTaskPathParams = {
    /**
     * @type string
    */
    campaignId: string;
};

export type AdminControllerAddTask201 = any;

export type AdminControllerAddTaskMutationRequest = CreateTaskDto;

export type AdminControllerAddTaskMutationResponse = AdminControllerAddTask201;

export type AdminControllerAddTaskMutation = {
    Response: AdminControllerAddTask201;
    Request: AdminControllerAddTaskMutationRequest;
    PathParams: AdminControllerAddTaskPathParams;
    Errors: any;
};