/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerExportRegistrationStatsQueryParams = {
    /**
     * @type number | undefined
    */
    days?: number;
};

export type AdminControllerExportRegistrationStats200 = any;

export type AdminControllerExportRegistrationStatsQueryResponse = AdminControllerExportRegistrationStats200;

export type AdminControllerExportRegistrationStatsQuery = {
    Response: AdminControllerExportRegistrationStats200;
    QueryParams: AdminControllerExportRegistrationStatsQueryParams;
    Errors: any;
};