/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateQuestCampaignDto } from "@/gen-backend/types/create-quest-campaign-dto";

export type AdminControllerCreateQuestCampaign201 = any;

export type AdminControllerCreateQuestCampaignMutationRequest = CreateQuestCampaignDto;

export type AdminControllerCreateQuestCampaignMutationResponse = AdminControllerCreateQuestCampaign201;

export type AdminControllerCreateQuestCampaignMutation = {
    Response: AdminControllerCreateQuestCampaign201;
    Request: AdminControllerCreateQuestCampaignMutationRequest;
    Errors: any;
};