/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerResendGiftEmailPathParams = {
    /**
     * @type string
    */
    recipientId: string;
};

export type AdminControllerResendGiftEmail201 = any;

export type AdminControllerResendGiftEmailMutationResponse = AdminControllerResendGiftEmail201;

export type AdminControllerResendGiftEmailMutation = {
    Response: AdminControllerResendGiftEmail201;
    PathParams: AdminControllerResendGiftEmailPathParams;
    Errors: any;
};