/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerListGifts200 = any;

export type AdminControllerListGiftsQueryResponse = AdminControllerListGifts200;

export type AdminControllerListGiftsQuery = {
    Response: AdminControllerListGifts200;
    Errors: any;
};