/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AuthControllerRegister201 = any;

export type AuthControllerRegisterMutationResponse = AuthControllerRegister201;

export type AuthControllerRegisterMutation = {
    Response: AuthControllerRegister201;
    Errors: any;
};