/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminLoginDto } from "@/gen-backend/types/admin-login-dto";

export type AuthControllerLogin201 = any;

export type AuthControllerLoginMutationRequest = AdminLoginDto;

export type AuthControllerLoginMutationResponse = AuthControllerLogin201;

export type AuthControllerLoginMutation = {
    Response: AuthControllerLogin201;
    Request: AuthControllerLoginMutationRequest;
    Errors: any;
};