/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AuthControllerMe200 = any;

export type AuthControllerMeQueryResponse = AuthControllerMe200;

export type AuthControllerMeQuery = {
    Response: AuthControllerMe200;
    Errors: any;
};