/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InternalChatUsageCommitDto } from "@/gen-backend/types/internal-chat-usage-commit-dto";

export type ChatUsageInternalControllerCommit201 = any;

export type ChatUsageInternalControllerCommitMutationRequest = InternalChatUsageCommitDto;

export type ChatUsageInternalControllerCommitMutationResponse = ChatUsageInternalControllerCommit201;

export type ChatUsageInternalControllerCommitMutation = {
    Response: ChatUsageInternalControllerCommit201;
    Request: ChatUsageInternalControllerCommitMutationRequest;
    Errors: any;
};