/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface ChatUsageInternalControllerGetSnapshotPathParams {
  userId: string;
}

export type ChatUsageInternalControllerGetSnapshot200 = {};

export type ChatUsageInternalControllerGetSnapshotQueryResponse = {};

export type ChatUsageInternalControllerGetSnapshotQuery = {};
