/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateNotificationDto = {
    /**
     * @description Target user id, empty for broadcast
     * @type string | undefined
    */
    userId?: string;
    /**
     * @type string
    */
    title: string;
    /**
     * @type string
    */
    body: string;
};