/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateQuestCampaignDto = {
    /**
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    protocol?: string;
    /**
     * @type string | undefined
    */
    category?: string;
    /**
     * @type string | undefined
    */
    logoUrl?: string;
    /**
     * @type string | undefined
    */
    startAt?: string;
    /**
     * @type string | undefined
    */
    endAt?: string;
    /**
     * @type number | undefined
    */
    maxParticipants?: number;
    /**
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type boolean | undefined
    */
    isDaily?: boolean;
    /**
     * @type boolean | undefined
    */
    isFeatured?: boolean;
    /**
     * @minLength 1
     * @type number | undefined
    */
    rewardPoints?: number;
    /**
     * @minLength 1
     * @type number | undefined
    */
    minTasksToComplete?: number;
    /**
     * @type string | undefined
    */
    descriptionDetail?: string;
    /**
     * @type string | undefined
    */
    coverUrl?: string;
};