/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreditPackageControllerList200 = {};

export type CreditPackageControllerListQueryResponse = {};

export type CreditPackageControllerListQuery = {};
