/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketplaceAdminControllerGetOverview200 = any;

export type MarketplaceAdminControllerGetOverviewQueryResponse = MarketplaceAdminControllerGetOverview200;

export type MarketplaceAdminControllerGetOverviewQuery = {
    Response: MarketplaceAdminControllerGetOverview200;
    Errors: any;
};