/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketplaceControllerPauseConfirmPathParams = {
    /**
     * @type string
    */
    id: string;
};

export type MarketplaceControllerPauseConfirm201 = any;

export type MarketplaceControllerPauseConfirmMutationResponse = MarketplaceControllerPauseConfirm201;

export type MarketplaceControllerPauseConfirmMutation = {
    Response: MarketplaceControllerPauseConfirm201;
    PathParams: MarketplaceControllerPauseConfirmPathParams;
    Errors: any;
};