/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketplaceControllerConfirmClaim201 = any;

export type MarketplaceControllerConfirmClaimMutationResponse = MarketplaceControllerConfirmClaim201;

export type MarketplaceControllerConfirmClaimMutation = {
    Response: MarketplaceControllerConfirmClaim201;
    Errors: any;
};