/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketplaceAdminControllerApprovePathParams = {
    /**
     * @type string
    */
    id: string;
};

export type MarketplaceAdminControllerApprove201 = any;

export type MarketplaceAdminControllerApproveMutationResponse = MarketplaceAdminControllerApprove201;

export type MarketplaceAdminControllerApproveMutation = {
    Response: MarketplaceAdminControllerApprove201;
    PathParams: MarketplaceAdminControllerApprovePathParams;
    Errors: any;
};