/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


;

export interface PortfolioControllerGetHistoryQueryParamsDaysEnumKey {
}

export interface PortfolioControllerGetHistoryQueryParams {
  publicKey: string
  days?: number
}

export interface PortfolioControllerGetHistory200 {
}

export interface PortfolioControllerGetHistoryQueryResponse {
}

export interface PortfolioControllerGetHistoryQuery {
}