/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface ProtocolControllerGetAllApysQueryParams {
  asset: string;
}

/**
 * @description Returns APY from all protocols across all chains for an asset, sorted by APY descending
 */
export type ProtocolControllerGetAllApys200 = {};

export type ProtocolControllerGetAllApysQueryResponse = {};

export type ProtocolControllerGetAllApysQuery = {};
