/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProtocolControllerGetUserPositionQueryParamsProtocolEnumKey = {};

export interface ProtocolControllerGetUserPositionQueryParams {
  protocol:
    | "aave"
    | "spark"
    | "compound"
    | "moonwell"
    | "fluid"
    | "euler"
    | "harvest"
    | "wasabi"
    | "morpho"
    | "silo"
    | "dolomite";
  userAddress: string;
  asset?: string;
}

/**
 * @description Returns the user supplied position in the protocol
 */
export type ProtocolControllerGetUserPosition200 = {};

export type ProtocolControllerGetUserPositionQueryResponse = {};

export type ProtocolControllerGetUserPositionQuery = {};
