/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type QuestVolumeItemDto = {
    /**
     * @description reward_volume_events row id
     * @type string
    */
    id: string;
    /**
     * @description Protocol
     * @type string
    */
    protocol: string;
    /**
     * @description Operation kind
     * @type string
    */
    operationKind: string;
    /**
     * @description Volume for this tx (USD)
     * @type number
    */
    amountUsd: number;
    /**
     * @description Masked wallet — never the full pubkey
     * @type string
    */
    walletMasked: string;
    /**
     * @description ISO timestamp
     * @type string
    */
    createdAt: string;
};
