/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RebalanceControllerGetStatus200 = {};

export type RebalanceControllerGetStatusQueryResponse = {};

export type RebalanceControllerGetStatusQuery = {};
