/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RebalanceControllerResume201 = any;

export type RebalanceControllerResumeMutationResponse = RebalanceControllerResume201;

export type RebalanceControllerResumeMutation = {
    Response: RebalanceControllerResume201;
    Errors: any;
};