/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ReferralControllerLinkXStart201 = any;

export type ReferralControllerLinkXStartMutationResponse = ReferralControllerLinkXStart201;

export type ReferralControllerLinkXStartMutation = {
    Response: ReferralControllerLinkXStart201;
    Errors: any;
};