/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TierRewardItemDto } from "@/gen-backend/types/tier-reward-item-dto";

export type SetTierRewardsDto = {
    /**
     * @type array
    */
    rewards: TierRewardItemDto[];
};