/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description List of linked social accounts
*/
export type SocialAccountsControllerFindAll200 = any;

export type SocialAccountsControllerFindAllQueryResponse = SocialAccountsControllerFindAll200;

export type SocialAccountsControllerFindAllQuery = {
    Response: SocialAccountsControllerFindAll200;
    Errors: any;
};