/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SponsorAdminControllerGetLogsQueryParams = {
    /**
     * @type number | undefined
    */
    limit?: number;
    /**
     * @type number | undefined
    */
    page?: number;
};

export type SponsorAdminControllerGetLogs200 = any;

export type SponsorAdminControllerGetLogsQueryResponse = SponsorAdminControllerGetLogs200;

export type SponsorAdminControllerGetLogsQuery = {
    Response: SponsorAdminControllerGetLogs200;
    QueryParams: SponsorAdminControllerGetLogsQueryParams;
    Errors: any;
};