/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubmitAiTxMetaDto } from "@/gen-backend/types/submit-ai-tx-meta-dto";

export type SubmitAiTxDto = {
    /**
     * @description Signed XDR string from user wallet
     * @type string
    */
    signedXdr: string;
    /**
     * @description User Stellar public key
     * @type string
    */
    publicKey: string;
    /**
     * @type object | undefined
    */
    meta?: SubmitAiTxMetaDto;
};