/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TxMetaDto } from "@/gen-backend/types/tx-meta-dto";

export type SubmitWithSponsorDto = {
    /**
     * @type string
    */
    signedInnerXdr: string;
    /**
     * @type object
    */
    meta: TxMetaDto;
};