/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SetTierRewardsDto } from "@/gen-backend/types/set-tier-rewards-dto";

export type TierRewardsAdminControllerSetRewards200 = any;

export type TierRewardsAdminControllerSetRewardsMutationRequest = SetTierRewardsDto;

export type TierRewardsAdminControllerSetRewardsMutationResponse = TierRewardsAdminControllerSetRewards200;

export type TierRewardsAdminControllerSetRewardsMutation = {
    Response: TierRewardsAdminControllerSetRewards200;
    Request: TierRewardsAdminControllerSetRewardsMutationRequest;
    Errors: any;
};