/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TransactionTypeCountDto = {
    /**
     * @type string
    */
    type: string;
    /**
     * @type number
    */
    count: number;
};