/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UsersControllerGetMe200 = any;

export type UsersControllerGetMeQueryResponse = UsersControllerGetMe200;

export type UsersControllerGetMeQuery = {
    Response: UsersControllerGetMe200;
    Errors: any;
};