/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegisterWalletDto } from "@/gen-backend/types/register-wallet-dto";

export type WaitlistControllerRegisterWallet200 = any;

export type WaitlistControllerRegisterWalletMutationRequest = RegisterWalletDto;

export type WaitlistControllerRegisterWalletMutationResponse = WaitlistControllerRegisterWallet200;

export type WaitlistControllerRegisterWalletMutation = {
    Response: WaitlistControllerRegisterWallet200;
    Request: WaitlistControllerRegisterWalletMutationRequest;
    Errors: any;
};