/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type WaitlistControllerAttachContact200 = {};

export type WaitlistControllerAttachContactMutationRequest = {};

export type WaitlistControllerAttachContactMutationResponse = {};

export type WaitlistControllerAttachContactMutation = {};
