/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TrackWelcomeRewardTxDto } from "@/gen-backend/types/track-welcome-reward-tx-dto";

export type WelcomeRewardControllerTrackTransaction201 = any;

export type WelcomeRewardControllerTrackTransactionMutationRequest = TrackWelcomeRewardTxDto;

export type WelcomeRewardControllerTrackTransactionMutationResponse = WelcomeRewardControllerTrackTransaction201;

export type WelcomeRewardControllerTrackTransactionMutation = {
    Response: WelcomeRewardControllerTrackTransaction201;
    Request: WelcomeRewardControllerTrackTransactionMutationRequest;
    Errors: any;
};