/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type WelcomeRewardControllerMarkSeen201 = {};

export type WelcomeRewardControllerMarkSeenMutationResponse = {};

export type WelcomeRewardControllerMarkSeenMutation = {};
