/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface WelcomeRewardControllerGetStatus200 {
}

export interface WelcomeRewardControllerGetStatusQueryResponse {
}

export interface WelcomeRewardControllerGetStatusQuery {
}