export type { AccountControllerBuildDeployTxMutationKey } from "@/gen-backend/hooks/use-account-controller-build-deploy-tx";
export type { AccountControllerBuildFundTxMutationKey } from "@/gen-backend/hooks/use-account-controller-build-fund-tx";
export type { AccountControllerBuildReactivateTxsMutationKey } from "@/gen-backend/hooks/use-account-controller-build-reactivate-txs";
export type { AccountControllerBuildRevokeTxMutationKey } from "@/gen-backend/hooks/use-account-controller-build-revoke-tx";
export type { AccountControllerBuildSetupTxsMutationKey } from "@/gen-backend/hooks/use-account-controller-build-setup-txs";
export type { AccountControllerBuildWithdrawTxMutationKey } from "@/gen-backend/hooks/use-account-controller-build-withdraw-tx";
export type { AccountControllerGetActivitySuspenseQueryKey } from "@/gen-backend/hooks/use-account-controller-get-activity-suspense";
export type { AccountControllerGetActivityQueryKey } from "@/gen-backend/hooks/use-account-controller-get-activity";
export type { AccountControllerGetPositionSuspenseQueryKey } from "@/gen-backend/hooks/use-account-controller-get-position-suspense";
export type { AccountControllerGetPositionQueryKey } from "@/gen-backend/hooks/use-account-controller-get-position";
export type { AccountControllerGetPresetsSuspenseQueryKey } from "@/gen-backend/hooks/use-account-controller-get-presets-suspense";
export type { AccountControllerGetPresetsQueryKey } from "@/gen-backend/hooks/use-account-controller-get-presets";
export type { AccountControllerResumeAccountMutationKey } from "@/gen-backend/hooks/use-account-controller-resume-account";
export type { AccountControllerSubmitTxMutationKey } from "@/gen-backend/hooks/use-account-controller-submit-tx";
export type { AccountControllerUpdatePresetMutationKey } from "@/gen-backend/hooks/use-account-controller-update-preset";
export type { AdminAuthControllerCreateAdminMutationKey } from "@/gen-backend/hooks/use-admin-auth-controller-create-admin";
export type { AdminAuthControllerLoginMutationKey } from "@/gen-backend/hooks/use-admin-auth-controller-login";
export type { AdminControllerGenerateCodesMutationKey } from "@/gen-backend/hooks/use-admin-controller-generate-codes";
export type { AdminControllerGetCampaignStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-campaign-status-suspense";
export type { AdminControllerGetCampaignStatusQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-campaign-status";
export type { AdminControllerGetDashboardSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-dashboard-suspense";
export type { AdminControllerGetDashboardQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-dashboard";
export type { AdminControllerGetRegistrationStatsSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-registration-stats-suspense";
export type { AdminControllerGetRegistrationStatsQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-registration-stats";
export type { AdminControllerListCampaignsSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-list-campaigns-suspense";
export type { AdminControllerListCampaignsQueryKey } from "@/gen-backend/hooks/use-admin-controller-list-campaigns";
export type { AdminControllerListCodesSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-list-codes-suspense";
export type { AdminControllerListCodesQueryKey } from "@/gen-backend/hooks/use-admin-controller-list-codes";
export type { AdminControllerRevokeCodeMutationKey } from "@/gen-backend/hooks/use-admin-controller-revoke-code";
export type { AdminControllerSendCampaignMutationKey } from "@/gen-backend/hooks/use-admin-controller-send-campaign";
export type { AppControllerGetHelloSuspenseQueryKey } from "@/gen-backend/hooks/use-app-controller-get-hello-suspense";
export type { AppControllerGetHelloQueryKey } from "@/gen-backend/hooks/use-app-controller-get-hello";
export type { AuthControllerChallengeMutationKey } from "@/gen-backend/hooks/use-auth-controller-challenge";
export type { AuthControllerLoginMutationKey } from "@/gen-backend/hooks/use-auth-controller-login";
export type { AuthControllerRegisterMutationKey } from "@/gen-backend/hooks/use-auth-controller-register";
export type { AuthControllerResolveChatUserForAiMutationKey } from "@/gen-backend/hooks/use-auth-controller-resolve-chat-user-for-ai";
export type { AuthControllerTestLoginMutationKey } from "@/gen-backend/hooks/use-auth-controller-test-login";
export type { AuthControllerVerifySessionForAiMutationKey } from "@/gen-backend/hooks/use-auth-controller-verify-session-for-ai";
export type { AuthControllerVerifyMutationKey } from "@/gen-backend/hooks/use-auth-controller-verify";
export type { ChatUsageInternalControllerCommitMutationKey } from "@/gen-backend/hooks/use-chat-usage-internal-controller-commit";
export type { ChatUsageInternalControllerGetSnapshotSuspenseQueryKey } from "@/gen-backend/hooks/use-chat-usage-internal-controller-get-snapshot-suspense";
export type { ChatUsageInternalControllerGetSnapshotQueryKey } from "@/gen-backend/hooks/use-chat-usage-internal-controller-get-snapshot";
export type { CreditControllerGetMeSuspenseQueryKey } from "@/gen-backend/hooks/use-credit-controller-get-me-suspense";
export type { CreditControllerGetMeQueryKey } from "@/gen-backend/hooks/use-credit-controller-get-me";
export type { CreditControllerListLedgerSuspenseQueryKey } from "@/gen-backend/hooks/use-credit-controller-list-ledger-suspense";
export type { CreditControllerListLedgerQueryKey } from "@/gen-backend/hooks/use-credit-controller-list-ledger";
export type { CreditInternalControllerApplyMutationKey } from "@/gen-backend/hooks/use-credit-internal-controller-apply";
export type { CreditPackageControllerListSuspenseQueryKey } from "@/gen-backend/hooks/use-credit-package-controller-list-suspense";
export type { CreditPackageControllerListQueryKey } from "@/gen-backend/hooks/use-credit-package-controller-list";
export type { EmailControllerSendTestEmailMutationKey } from "@/gen-backend/hooks/use-email-controller-send-test-email";
export type { HealthControllerCheckSuspenseQueryKey } from "@/gen-backend/hooks/use-health-controller-check-suspense";
export type { HealthControllerCheckQueryKey } from "@/gen-backend/hooks/use-health-controller-check";
export type { PoolsControllerGetPoolHistorySuspenseQueryKey } from "@/gen-backend/hooks/use-pools-controller-get-pool-history-suspense";
export type { PoolsControllerGetPoolHistoryQueryKey } from "@/gen-backend/hooks/use-pools-controller-get-pool-history";
export type { PoolsControllerGetPoolsSuspenseQueryKey } from "@/gen-backend/hooks/use-pools-controller-get-pools-suspense";
export type { PoolsControllerGetPoolsQueryKey } from "@/gen-backend/hooks/use-pools-controller-get-pools";
export type { PortfolioControllerGetHistorySuspenseQueryKey } from "@/gen-backend/hooks/use-portfolio-controller-get-history-suspense";
export type { PortfolioControllerGetHistoryQueryKey } from "@/gen-backend/hooks/use-portfolio-controller-get-history";
export type { PortfolioControllerRegisterAddressMutationKey } from "@/gen-backend/hooks/use-portfolio-controller-register-address";
export type { ProtocolControllerGetAllApysSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-all-apys-suspense";
export type { ProtocolControllerGetAllApysQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-all-apys";
export type { ProtocolControllerGetAllProtocolsSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-all-protocols-suspense";
export type { ProtocolControllerGetAllProtocolsQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-all-protocols";
export type { ProtocolControllerGetApyByChainSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-apy-by-chain-suspense";
export type { ProtocolControllerGetApyByChainQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-apy-by-chain";
export type { ProtocolControllerGetAvailableAssetsSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-available-assets-suspense";
export type { ProtocolControllerGetAvailableAssetsQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-available-assets";
export type { ProtocolControllerGetLendingApySuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-lending-apy-suspense";
export type { ProtocolControllerGetLendingApyQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-lending-apy";
export type { ProtocolControllerGetUserPositionSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-user-position-suspense";
export type { ProtocolControllerGetUserPositionQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-user-position";
export type { RebalanceControllerGetStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-rebalance-controller-get-status-suspense";
export type { RebalanceControllerGetStatusQueryKey } from "@/gen-backend/hooks/use-rebalance-controller-get-status";
export type { RebalanceControllerHaltMutationKey } from "@/gen-backend/hooks/use-rebalance-controller-halt";
export type { RebalanceControllerResumeMutationKey } from "@/gen-backend/hooks/use-rebalance-controller-resume";
export type { RebalanceControllerRunHarvestManualMutationKey } from "@/gen-backend/hooks/use-rebalance-controller-run-harvest-manual";
export type { RebalanceControllerRunManualMutationKey } from "@/gen-backend/hooks/use-rebalance-controller-run-manual";
export type { UserControllerGetUserSuspenseQueryKey } from "@/gen-backend/hooks/use-user-controller-get-user-suspense";
export type { UserControllerGetUserQueryKey } from "@/gen-backend/hooks/use-user-controller-get-user";
export type { UserMeControllerGetMeSuspenseQueryKey } from "@/gen-backend/hooks/use-user-me-controller-get-me-suspense";
export type { UserMeControllerGetMeQueryKey } from "@/gen-backend/hooks/use-user-me-controller-get-me";
export type { WaitlistControllerAttachContactMutationKey } from "@/gen-backend/hooks/use-waitlist-controller-attach-contact";
export type { WaitlistControllerGetStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-waitlist-controller-get-status-suspense";
export type { WaitlistControllerGetStatusQueryKey } from "@/gen-backend/hooks/use-waitlist-controller-get-status";
export type { WaitlistControllerRegisterWalletMutationKey } from "@/gen-backend/hooks/use-waitlist-controller-register-wallet";
export type { WaitlistControllerRegisterMutationKey } from "@/gen-backend/hooks/use-waitlist-controller-register";
export type { WaitlistControllerRequestChallengeMutationKey } from "@/gen-backend/hooks/use-waitlist-controller-request-challenge";
export type { WaitlistControllerVerifyReferralSuspenseQueryKey } from "@/gen-backend/hooks/use-waitlist-controller-verify-referral-suspense";
export type { WaitlistControllerVerifyReferralQueryKey } from "@/gen-backend/hooks/use-waitlist-controller-verify-referral";
export type { WelcomeRewardControllerGetFullStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-welcome-reward-controller-get-full-status-suspense";
export type { WelcomeRewardControllerGetFullStatusQueryKey } from "@/gen-backend/hooks/use-welcome-reward-controller-get-full-status";
export type { WelcomeRewardControllerGetStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-welcome-reward-controller-get-status-suspense";
export type { WelcomeRewardControllerGetStatusQueryKey } from "@/gen-backend/hooks/use-welcome-reward-controller-get-status";
export type { WelcomeRewardControllerMarkSeenMutationKey } from "@/gen-backend/hooks/use-welcome-reward-controller-mark-seen";
export type { WelcomeRewardControllerScanVolumeMutationKey } from "@/gen-backend/hooks/use-welcome-reward-controller-scan-volume";
export type { WelcomeRewardControllerTrackTransactionMutationKey } from "@/gen-backend/hooks/use-welcome-reward-controller-track-transaction";
export type { AccountControllerBuildDeployTx201, AccountControllerBuildDeployTxMutationRequest, AccountControllerBuildDeployTxMutationResponse, AccountControllerBuildDeployTxMutation } from "@/gen-backend/types/account-controller-build-deploy-tx";
export type { AccountControllerBuildFundTx201, AccountControllerBuildFundTxMutationRequest, AccountControllerBuildFundTxMutationResponse, AccountControllerBuildFundTxMutation } from "@/gen-backend/types/account-controller-build-fund-tx";
export type { AccountControllerBuildReactivateTxs201, AccountControllerBuildReactivateTxsMutationRequest, AccountControllerBuildReactivateTxsMutationResponse, AccountControllerBuildReactivateTxsMutation } from "@/gen-backend/types/account-controller-build-reactivate-txs";
export type { AccountControllerBuildRevokeTx201, AccountControllerBuildRevokeTxMutationRequest, AccountControllerBuildRevokeTxMutationResponse, AccountControllerBuildRevokeTxMutation } from "@/gen-backend/types/account-controller-build-revoke-tx";
export type { AccountControllerBuildSetupTxs201, AccountControllerBuildSetupTxsMutationRequest, AccountControllerBuildSetupTxsMutationResponse, AccountControllerBuildSetupTxsMutation } from "@/gen-backend/types/account-controller-build-setup-txs";
export type { AccountControllerBuildWithdrawTx201, AccountControllerBuildWithdrawTxMutationRequest, AccountControllerBuildWithdrawTxMutationResponse, AccountControllerBuildWithdrawTxMutation } from "@/gen-backend/types/account-controller-build-withdraw-tx";
export type { AccountControllerGetActivityPathParams, AccountControllerGetActivityQueryParams, AccountControllerGetActivity200, AccountControllerGetActivityQueryResponse, AccountControllerGetActivityQuery } from "@/gen-backend/types/account-controller-get-activity";
export type { AccountControllerGetPositionPathParams, AccountControllerGetPosition200, AccountControllerGetPositionQueryResponse, AccountControllerGetPositionQuery } from "@/gen-backend/types/account-controller-get-position";
export type { AccountControllerGetPresetsQueryParams, AccountControllerGetPresets200, AccountControllerGetPresetsQueryResponse, AccountControllerGetPresetsQuery } from "@/gen-backend/types/account-controller-get-presets";
export type { AccountControllerResumeAccountPathParams, AccountControllerResumeAccount201, AccountControllerResumeAccountMutationResponse, AccountControllerResumeAccountMutation } from "@/gen-backend/types/account-controller-resume-account";
export type { AccountControllerSubmitTx201, AccountControllerSubmitTxMutationRequest, AccountControllerSubmitTxMutationResponse, AccountControllerSubmitTxMutation } from "@/gen-backend/types/account-controller-submit-tx";
export type { AccountControllerUpdatePresetPathParams, AccountControllerUpdatePreset200, AccountControllerUpdatePresetMutationRequest, AccountControllerUpdatePresetMutationResponse, AccountControllerUpdatePresetMutation } from "@/gen-backend/types/account-controller-update-preset";
export type { AdminAuthControllerCreateAdmin201, AdminAuthControllerCreateAdminMutationRequest, AdminAuthControllerCreateAdminMutationResponse, AdminAuthControllerCreateAdminMutation } from "@/gen-backend/types/admin-auth-controller-create-admin";
export type { AdminAuthControllerLogin200, AdminAuthControllerLoginMutationRequest, AdminAuthControllerLoginMutationResponse, AdminAuthControllerLoginMutation } from "@/gen-backend/types/admin-auth-controller-login";
export type { AdminControllerGenerateCodes201, AdminControllerGenerateCodesMutationRequest, AdminControllerGenerateCodesMutationResponse, AdminControllerGenerateCodesMutation } from "@/gen-backend/types/admin-controller-generate-codes";
export type { AdminControllerGetCampaignStatusPathParams, AdminControllerGetCampaignStatus200, AdminControllerGetCampaignStatusQueryResponse, AdminControllerGetCampaignStatusQuery } from "@/gen-backend/types/admin-controller-get-campaign-status";
export type { AdminControllerGetDashboard200, AdminControllerGetDashboardQueryResponse, AdminControllerGetDashboardQuery } from "@/gen-backend/types/admin-controller-get-dashboard";
export type { AdminControllerGetRegistrationStatsQueryParams, AdminControllerGetRegistrationStats200, AdminControllerGetRegistrationStatsQueryResponse, AdminControllerGetRegistrationStatsQuery } from "@/gen-backend/types/admin-controller-get-registration-stats";
export type { AdminControllerListCampaigns200, AdminControllerListCampaignsQueryResponse, AdminControllerListCampaignsQuery } from "@/gen-backend/types/admin-controller-list-campaigns";
export type { AdminControllerListCodesQueryParams, AdminControllerListCodes200, AdminControllerListCodesQueryResponse, AdminControllerListCodesQuery } from "@/gen-backend/types/admin-controller-list-codes";
export type { AdminControllerRevokeCodePathParams, AdminControllerRevokeCode200, AdminControllerRevokeCodeMutationResponse, AdminControllerRevokeCodeMutation } from "@/gen-backend/types/admin-controller-revoke-code";
export type { AdminControllerSendCampaign201, AdminControllerSendCampaignMutationRequest, AdminControllerSendCampaignMutationResponse, AdminControllerSendCampaignMutation } from "@/gen-backend/types/admin-controller-send-campaign";
export type { AdminLoginDto } from "@/gen-backend/types/admin-login-dto";
export type { AppControllerGetHello200, AppControllerGetHelloQueryResponse, AppControllerGetHelloQuery } from "@/gen-backend/types/app-controller-get-hello";
export type { ApplyDeltaDtoReasonEnumKey, ApplyDeltaDto } from "@/gen-backend/types/apply-delta-dto";
export type { AttachWaitlistContactDto } from "@/gen-backend/types/attach-waitlist-contact-dto";
export type { AuthControllerChallenge201, AuthControllerChallengeMutationRequest, AuthControllerChallengeMutationResponse, AuthControllerChallengeMutation } from "@/gen-backend/types/auth-controller-challenge";
export type { AuthControllerLogin201, AuthControllerLoginMutationRequest, AuthControllerLoginMutationResponse, AuthControllerLoginMutation } from "@/gen-backend/types/auth-controller-login";
export type { AuthControllerRegister201, AuthControllerRegisterMutationResponse, AuthControllerRegisterMutation } from "@/gen-backend/types/auth-controller-register";
export type { AuthControllerResolveChatUserForAi201, AuthControllerResolveChatUserForAiMutationRequest, AuthControllerResolveChatUserForAiMutationResponse, AuthControllerResolveChatUserForAiMutation } from "@/gen-backend/types/auth-controller-resolve-chat-user-for-ai";
export type { AuthControllerTestLogin201, AuthControllerTestLoginMutationRequest, AuthControllerTestLoginMutationResponse, AuthControllerTestLoginMutation } from "@/gen-backend/types/auth-controller-test-login";
export type { AuthControllerVerifySessionForAi201, AuthControllerVerifySessionForAiMutationRequest, AuthControllerVerifySessionForAiMutationResponse, AuthControllerVerifySessionForAiMutation } from "@/gen-backend/types/auth-controller-verify-session-for-ai";
export type { AuthControllerVerify201, AuthControllerVerifyMutationRequest, AuthControllerVerifyMutationResponse, AuthControllerVerifyMutation } from "@/gen-backend/types/auth-controller-verify";
export type { CampaignSendDto } from "@/gen-backend/types/campaign-send-dto";
export type { ChatUsageInternalControllerCommit201, ChatUsageInternalControllerCommitMutationRequest, ChatUsageInternalControllerCommitMutationResponse, ChatUsageInternalControllerCommitMutation } from "@/gen-backend/types/chat-usage-internal-controller-commit";
export type { ChatUsageInternalControllerGetSnapshotPathParams, ChatUsageInternalControllerGetSnapshot200, ChatUsageInternalControllerGetSnapshotQueryResponse, ChatUsageInternalControllerGetSnapshotQuery } from "@/gen-backend/types/chat-usage-internal-controller-get-snapshot";
export type { CreateAdminDto } from "@/gen-backend/types/create-admin-dto";
export type { CreditControllerGetMe200, CreditControllerGetMeQueryResponse, CreditControllerGetMeQuery } from "@/gen-backend/types/credit-controller-get-me";
export type { CreditControllerListLedgerQueryParams, CreditControllerListLedger200, CreditControllerListLedgerQueryResponse, CreditControllerListLedgerQuery } from "@/gen-backend/types/credit-controller-list-ledger";
export type { CreditInternalControllerApply201, CreditInternalControllerApplyMutationRequest, CreditInternalControllerApplyMutationResponse, CreditInternalControllerApplyMutation } from "@/gen-backend/types/credit-internal-controller-apply";
export type { CreditPackageControllerList200, CreditPackageControllerListQueryResponse, CreditPackageControllerListQuery } from "@/gen-backend/types/credit-package-controller-list";
export type { CreditPackageDto } from "@/gen-backend/types/credit-package-dto";
export type { DeployAccountDto } from "@/gen-backend/types/deploy-account-dto";
export type { EmailControllerSendTestEmail200, EmailControllerSendTestEmailMutationResponse, EmailControllerSendTestEmailMutation } from "@/gen-backend/types/email-controller-send-test-email";
export type { FundAccountDto } from "@/gen-backend/types/fund-account-dto";
export type { GenerateCodesDto } from "@/gen-backend/types/generate-codes-dto";
export type { HealthControllerCheck200, HealthControllerCheckQueryResponse, HealthControllerCheckQuery } from "@/gen-backend/types/health-controller-check";
export type { InternalChatUsageCommitDto } from "@/gen-backend/types/internal-chat-usage-commit-dto";
export type { InternalResolveChatUserDto } from "@/gen-backend/types/internal-resolve-chat-user-dto";
export type { InternalVerifySessionDto } from "@/gen-backend/types/internal-verify-session-dto";
export type { PoolsControllerGetPoolHistoryPathParams, PoolsControllerGetPoolHistory200, PoolsControllerGetPoolHistoryQueryResponse, PoolsControllerGetPoolHistoryQuery } from "@/gen-backend/types/pools-controller-get-pool-history";
export type { PoolsControllerGetPoolsQueryParamsRiskPresetEnumKey, PoolsControllerGetPoolsQueryParams, PoolsControllerGetPools200, PoolsControllerGetPoolsQueryResponse, PoolsControllerGetPoolsQuery } from "@/gen-backend/types/pools-controller-get-pools";
export type { PortfolioControllerGetHistoryPathParams, PortfolioControllerGetHistoryQueryParams, PortfolioControllerGetHistory200, PortfolioControllerGetHistoryQueryResponse, PortfolioControllerGetHistoryQuery } from "@/gen-backend/types/portfolio-controller-get-history";
export type { PortfolioControllerRegisterAddress200, PortfolioControllerRegisterAddressMutationRequest, PortfolioControllerRegisterAddressMutationResponse, PortfolioControllerRegisterAddressMutation } from "@/gen-backend/types/portfolio-controller-register-address";
export type { ProtocolControllerGetAllApysQueryParams, ProtocolControllerGetAllApys200, ProtocolControllerGetAllApysQueryResponse, ProtocolControllerGetAllApysQuery } from "@/gen-backend/types/protocol-controller-get-all-apys";
export type { ProtocolControllerGetAllProtocols200, ProtocolControllerGetAllProtocolsQueryResponse, ProtocolControllerGetAllProtocolsQuery } from "@/gen-backend/types/protocol-controller-get-all-protocols";
export type { ProtocolControllerGetApyByChainQueryParams, ProtocolControllerGetApyByChain200, ProtocolControllerGetApyByChainQueryResponse, ProtocolControllerGetApyByChainQuery } from "@/gen-backend/types/protocol-controller-get-apy-by-chain";
export type { ProtocolControllerGetAvailableAssetsQueryParams, ProtocolControllerGetAvailableAssets200, ProtocolControllerGetAvailableAssetsQueryResponse, ProtocolControllerGetAvailableAssetsQuery } from "@/gen-backend/types/protocol-controller-get-available-assets";
export type { ProtocolControllerGetLendingApyQueryParamsProtocolEnumKey, ProtocolControllerGetLendingApyQueryParamsChainEnumKey, ProtocolControllerGetLendingApyQueryParams, ProtocolControllerGetLendingApy200, ProtocolControllerGetLendingApyQueryResponse, ProtocolControllerGetLendingApyQuery } from "@/gen-backend/types/protocol-controller-get-lending-apy";
export type { ProtocolControllerGetUserPositionQueryParamsProtocolEnumKey, ProtocolControllerGetUserPositionQueryParams, ProtocolControllerGetUserPosition200, ProtocolControllerGetUserPositionQueryResponse, ProtocolControllerGetUserPositionQuery } from "@/gen-backend/types/protocol-controller-get-user-position";
export type { RebalanceControllerGetStatus200, RebalanceControllerGetStatusQueryResponse, RebalanceControllerGetStatusQuery } from "@/gen-backend/types/rebalance-controller-get-status";
export type { RebalanceControllerHalt201, RebalanceControllerHaltMutationResponse, RebalanceControllerHaltMutation } from "@/gen-backend/types/rebalance-controller-halt";
export type { RebalanceControllerResume201, RebalanceControllerResumeMutationResponse, RebalanceControllerResumeMutation } from "@/gen-backend/types/rebalance-controller-resume";
export type { RebalanceControllerRunHarvestManual201, RebalanceControllerRunHarvestManualMutationResponse, RebalanceControllerRunHarvestManualMutation } from "@/gen-backend/types/rebalance-controller-run-harvest-manual";
export type { RebalanceControllerRunManual201, RebalanceControllerRunManualMutationResponse, RebalanceControllerRunManualMutation } from "@/gen-backend/types/rebalance-controller-run-manual";
export type { RegisterWaitlistDto } from "@/gen-backend/types/register-waitlist-dto";
export type { RegisterWalletDtoWalletProviderEnumKey, RegisterWalletDto } from "@/gen-backend/types/register-wallet-dto";
export type { RequestChallengeDto } from "@/gen-backend/types/request-challenge-dto";
export type { SnapshotRequestDto } from "@/gen-backend/types/snapshot-request-dto";
export type { SubmitTxDto } from "@/gen-backend/types/submit-tx-dto";
export type { TrackWelcomeRewardTxDto } from "@/gen-backend/types/track-welcome-reward-tx-dto";
export type { UpdatePresetDto } from "@/gen-backend/types/update-preset-dto";
export type { UserControllerGetUserPathParams, UserControllerGetUser200, UserControllerGetUserQueryResponse, UserControllerGetUserQuery } from "@/gen-backend/types/user-controller-get-user";
export type { UserMeControllerGetMe200, UserMeControllerGetMeQueryResponse, UserMeControllerGetMeQuery } from "@/gen-backend/types/user-me-controller-get-me";
export type { WaitlistControllerAttachContact200, WaitlistControllerAttachContactMutationRequest, WaitlistControllerAttachContactMutationResponse, WaitlistControllerAttachContactMutation } from "@/gen-backend/types/waitlist-controller-attach-contact";
export type { WaitlistControllerGetStatusQueryParams, WaitlistControllerGetStatus200, WaitlistControllerGetStatusQueryResponse, WaitlistControllerGetStatusQuery } from "@/gen-backend/types/waitlist-controller-get-status";
export type { WaitlistControllerRegisterWallet200, WaitlistControllerRegisterWalletMutationRequest, WaitlistControllerRegisterWalletMutationResponse, WaitlistControllerRegisterWalletMutation } from "@/gen-backend/types/waitlist-controller-register-wallet";
export type { WaitlistControllerRegister200, WaitlistControllerRegisterMutationRequest, WaitlistControllerRegisterMutationResponse, WaitlistControllerRegisterMutation } from "@/gen-backend/types/waitlist-controller-register";
export type { WaitlistControllerRequestChallenge200, WaitlistControllerRequestChallengeMutationRequest, WaitlistControllerRequestChallengeMutationResponse, WaitlistControllerRequestChallengeMutation } from "@/gen-backend/types/waitlist-controller-request-challenge";
export type { WaitlistControllerVerifyReferralQueryParams, WaitlistControllerVerifyReferral200, WaitlistControllerVerifyReferralQueryResponse, WaitlistControllerVerifyReferralQuery } from "@/gen-backend/types/waitlist-controller-verify-referral";
export type { WalletAuthDto } from "@/gen-backend/types/wallet-auth-dto";
export type { WalletTestLoginDto } from "@/gen-backend/types/wallet-test-login-dto";
export type { WalletVerifyDto } from "@/gen-backend/types/wallet-verify-dto";
export type { WelcomeRewardControllerGetFullStatus200, WelcomeRewardControllerGetFullStatusQueryResponse, WelcomeRewardControllerGetFullStatusQuery } from "@/gen-backend/types/welcome-reward-controller-get-full-status";
export type { WelcomeRewardControllerGetStatus200, WelcomeRewardControllerGetStatusQueryResponse, WelcomeRewardControllerGetStatusQuery } from "@/gen-backend/types/welcome-reward-controller-get-status";
export type { WelcomeRewardControllerMarkSeen201, WelcomeRewardControllerMarkSeenMutationResponse, WelcomeRewardControllerMarkSeenMutation } from "@/gen-backend/types/welcome-reward-controller-mark-seen";
export type { WelcomeRewardControllerScanVolume201, WelcomeRewardControllerScanVolumeMutationResponse, WelcomeRewardControllerScanVolumeMutation } from "@/gen-backend/types/welcome-reward-controller-scan-volume";
export type { WelcomeRewardControllerTrackTransaction201, WelcomeRewardControllerTrackTransactionMutationRequest, WelcomeRewardControllerTrackTransactionMutationResponse, WelcomeRewardControllerTrackTransactionMutation } from "@/gen-backend/types/welcome-reward-controller-track-transaction";
export type { WithdrawDto } from "@/gen-backend/types/withdraw-dto";
export { accountControllerBuildDeployTx } from "@/gen-backend/client/account-controller-build-deploy-tx";
export { accountControllerBuildFundTx } from "@/gen-backend/client/account-controller-build-fund-tx";
export { accountControllerBuildReactivateTxs } from "@/gen-backend/client/account-controller-build-reactivate-txs";
export { accountControllerBuildRevokeTx } from "@/gen-backend/client/account-controller-build-revoke-tx";
export { accountControllerBuildSetupTxs } from "@/gen-backend/client/account-controller-build-setup-txs";
export { accountControllerBuildWithdrawTx } from "@/gen-backend/client/account-controller-build-withdraw-tx";
export { accountControllerGetActivity } from "@/gen-backend/client/account-controller-get-activity";
export { accountControllerGetPosition } from "@/gen-backend/client/account-controller-get-position";
export { accountControllerGetPresets } from "@/gen-backend/client/account-controller-get-presets";
export { accountControllerResumeAccount } from "@/gen-backend/client/account-controller-resume-account";
export { accountControllerSubmitTx } from "@/gen-backend/client/account-controller-submit-tx";
export { accountControllerUpdatePreset } from "@/gen-backend/client/account-controller-update-preset";
export { adminAuthControllerCreateAdmin } from "@/gen-backend/client/admin-auth-controller-create-admin";
export { adminAuthControllerLogin } from "@/gen-backend/client/admin-auth-controller-login";
export { adminControllerGenerateCodes } from "@/gen-backend/client/admin-controller-generate-codes";
export { adminControllerGetCampaignStatus } from "@/gen-backend/client/admin-controller-get-campaign-status";
export { adminControllerGetDashboard } from "@/gen-backend/client/admin-controller-get-dashboard";
export { adminControllerGetRegistrationStats } from "@/gen-backend/client/admin-controller-get-registration-stats";
export { adminControllerListCampaigns } from "@/gen-backend/client/admin-controller-list-campaigns";
export { adminControllerListCodes } from "@/gen-backend/client/admin-controller-list-codes";
export { adminControllerRevokeCode } from "@/gen-backend/client/admin-controller-revoke-code";
export { adminControllerSendCampaign } from "@/gen-backend/client/admin-controller-send-campaign";
export { appControllerGetHello } from "@/gen-backend/client/app-controller-get-hello";
export { authControllerChallenge } from "@/gen-backend/client/auth-controller-challenge";
export { authControllerLogin } from "@/gen-backend/client/auth-controller-login";
export { authControllerRegister } from "@/gen-backend/client/auth-controller-register";
export { authControllerResolveChatUserForAi } from "@/gen-backend/client/auth-controller-resolve-chat-user-for-ai";
export { authControllerTestLogin } from "@/gen-backend/client/auth-controller-test-login";
export { authControllerVerifySessionForAi } from "@/gen-backend/client/auth-controller-verify-session-for-ai";
export { authControllerVerify } from "@/gen-backend/client/auth-controller-verify";
export { chatUsageInternalControllerCommit } from "@/gen-backend/client/chat-usage-internal-controller-commit";
export { chatUsageInternalControllerGetSnapshot } from "@/gen-backend/client/chat-usage-internal-controller-get-snapshot";
export { creditControllerGetMe } from "@/gen-backend/client/credit-controller-get-me";
export { creditControllerListLedger } from "@/gen-backend/client/credit-controller-list-ledger";
export { creditInternalControllerApply } from "@/gen-backend/client/credit-internal-controller-apply";
export { creditPackageControllerList } from "@/gen-backend/client/credit-package-controller-list";
export { emailControllerSendTestEmail } from "@/gen-backend/client/email-controller-send-test-email";
export { healthControllerCheck } from "@/gen-backend/client/health-controller-check";
export { poolsControllerGetPoolHistory } from "@/gen-backend/client/pools-controller-get-pool-history";
export { poolsControllerGetPools } from "@/gen-backend/client/pools-controller-get-pools";
export { portfolioControllerGetHistory } from "@/gen-backend/client/portfolio-controller-get-history";
export { portfolioControllerRegisterAddress } from "@/gen-backend/client/portfolio-controller-register-address";
export { protocolControllerGetAllApys } from "@/gen-backend/client/protocol-controller-get-all-apys";
export { protocolControllerGetAllProtocols } from "@/gen-backend/client/protocol-controller-get-all-protocols";
export { protocolControllerGetApyByChain } from "@/gen-backend/client/protocol-controller-get-apy-by-chain";
export { protocolControllerGetAvailableAssets } from "@/gen-backend/client/protocol-controller-get-available-assets";
export { protocolControllerGetLendingApy } from "@/gen-backend/client/protocol-controller-get-lending-apy";
export { protocolControllerGetUserPosition } from "@/gen-backend/client/protocol-controller-get-user-position";
export { rebalanceControllerGetStatus } from "@/gen-backend/client/rebalance-controller-get-status";
export { rebalanceControllerHalt } from "@/gen-backend/client/rebalance-controller-halt";
export { rebalanceControllerResume } from "@/gen-backend/client/rebalance-controller-resume";
export { rebalanceControllerRunHarvestManual } from "@/gen-backend/client/rebalance-controller-run-harvest-manual";
export { rebalanceControllerRunManual } from "@/gen-backend/client/rebalance-controller-run-manual";
export { userControllerGetUser } from "@/gen-backend/client/user-controller-get-user";
export { userMeControllerGetMe } from "@/gen-backend/client/user-me-controller-get-me";
export { waitlistControllerAttachContact } from "@/gen-backend/client/waitlist-controller-attach-contact";
export { waitlistControllerGetStatus } from "@/gen-backend/client/waitlist-controller-get-status";
export { waitlistControllerRegisterWallet } from "@/gen-backend/client/waitlist-controller-register-wallet";
export { waitlistControllerRegister } from "@/gen-backend/client/waitlist-controller-register";
export { waitlistControllerRequestChallenge } from "@/gen-backend/client/waitlist-controller-request-challenge";
export { waitlistControllerVerifyReferral } from "@/gen-backend/client/waitlist-controller-verify-referral";
export { welcomeRewardControllerGetFullStatus } from "@/gen-backend/client/welcome-reward-controller-get-full-status";
export { welcomeRewardControllerGetStatus } from "@/gen-backend/client/welcome-reward-controller-get-status";
export { welcomeRewardControllerMarkSeen } from "@/gen-backend/client/welcome-reward-controller-mark-seen";
export { welcomeRewardControllerScanVolume } from "@/gen-backend/client/welcome-reward-controller-scan-volume";
export { welcomeRewardControllerTrackTransaction } from "@/gen-backend/client/welcome-reward-controller-track-transaction";
export { accountControllerBuildDeployTxMutationKey } from "@/gen-backend/hooks/use-account-controller-build-deploy-tx";
export { accountControllerBuildDeployTxMutationOptions } from "@/gen-backend/hooks/use-account-controller-build-deploy-tx";
export { useAccountControllerBuildDeployTx } from "@/gen-backend/hooks/use-account-controller-build-deploy-tx";
export { accountControllerBuildFundTxMutationKey } from "@/gen-backend/hooks/use-account-controller-build-fund-tx";
export { accountControllerBuildFundTxMutationOptions } from "@/gen-backend/hooks/use-account-controller-build-fund-tx";
export { useAccountControllerBuildFundTx } from "@/gen-backend/hooks/use-account-controller-build-fund-tx";
export { accountControllerBuildReactivateTxsMutationKey } from "@/gen-backend/hooks/use-account-controller-build-reactivate-txs";
export { accountControllerBuildReactivateTxsMutationOptions } from "@/gen-backend/hooks/use-account-controller-build-reactivate-txs";
export { useAccountControllerBuildReactivateTxs } from "@/gen-backend/hooks/use-account-controller-build-reactivate-txs";
export { accountControllerBuildRevokeTxMutationKey } from "@/gen-backend/hooks/use-account-controller-build-revoke-tx";
export { accountControllerBuildRevokeTxMutationOptions } from "@/gen-backend/hooks/use-account-controller-build-revoke-tx";
export { useAccountControllerBuildRevokeTx } from "@/gen-backend/hooks/use-account-controller-build-revoke-tx";
export { accountControllerBuildSetupTxsMutationKey } from "@/gen-backend/hooks/use-account-controller-build-setup-txs";
export { accountControllerBuildSetupTxsMutationOptions } from "@/gen-backend/hooks/use-account-controller-build-setup-txs";
export { useAccountControllerBuildSetupTxs } from "@/gen-backend/hooks/use-account-controller-build-setup-txs";
export { accountControllerBuildWithdrawTxMutationKey } from "@/gen-backend/hooks/use-account-controller-build-withdraw-tx";
export { accountControllerBuildWithdrawTxMutationOptions } from "@/gen-backend/hooks/use-account-controller-build-withdraw-tx";
export { useAccountControllerBuildWithdrawTx } from "@/gen-backend/hooks/use-account-controller-build-withdraw-tx";
export { accountControllerGetActivitySuspenseQueryKey } from "@/gen-backend/hooks/use-account-controller-get-activity-suspense";
export { accountControllerGetActivitySuspenseQueryOptions } from "@/gen-backend/hooks/use-account-controller-get-activity-suspense";
export { useAccountControllerGetActivitySuspense } from "@/gen-backend/hooks/use-account-controller-get-activity-suspense";
export { accountControllerGetActivityQueryKey } from "@/gen-backend/hooks/use-account-controller-get-activity";
export { accountControllerGetActivityQueryOptions } from "@/gen-backend/hooks/use-account-controller-get-activity";
export { useAccountControllerGetActivity } from "@/gen-backend/hooks/use-account-controller-get-activity";
export { accountControllerGetPositionSuspenseQueryKey } from "@/gen-backend/hooks/use-account-controller-get-position-suspense";
export { accountControllerGetPositionSuspenseQueryOptions } from "@/gen-backend/hooks/use-account-controller-get-position-suspense";
export { useAccountControllerGetPositionSuspense } from "@/gen-backend/hooks/use-account-controller-get-position-suspense";
export { accountControllerGetPositionQueryKey } from "@/gen-backend/hooks/use-account-controller-get-position";
export { accountControllerGetPositionQueryOptions } from "@/gen-backend/hooks/use-account-controller-get-position";
export { useAccountControllerGetPosition } from "@/gen-backend/hooks/use-account-controller-get-position";
export { accountControllerGetPresetsSuspenseQueryKey } from "@/gen-backend/hooks/use-account-controller-get-presets-suspense";
export { accountControllerGetPresetsSuspenseQueryOptions } from "@/gen-backend/hooks/use-account-controller-get-presets-suspense";
export { useAccountControllerGetPresetsSuspense } from "@/gen-backend/hooks/use-account-controller-get-presets-suspense";
export { accountControllerGetPresetsQueryKey } from "@/gen-backend/hooks/use-account-controller-get-presets";
export { accountControllerGetPresetsQueryOptions } from "@/gen-backend/hooks/use-account-controller-get-presets";
export { useAccountControllerGetPresets } from "@/gen-backend/hooks/use-account-controller-get-presets";
export { accountControllerResumeAccountMutationKey } from "@/gen-backend/hooks/use-account-controller-resume-account";
export { accountControllerResumeAccountMutationOptions } from "@/gen-backend/hooks/use-account-controller-resume-account";
export { useAccountControllerResumeAccount } from "@/gen-backend/hooks/use-account-controller-resume-account";
export { accountControllerSubmitTxMutationKey } from "@/gen-backend/hooks/use-account-controller-submit-tx";
export { accountControllerSubmitTxMutationOptions } from "@/gen-backend/hooks/use-account-controller-submit-tx";
export { useAccountControllerSubmitTx } from "@/gen-backend/hooks/use-account-controller-submit-tx";
export { accountControllerUpdatePresetMutationKey } from "@/gen-backend/hooks/use-account-controller-update-preset";
export { accountControllerUpdatePresetMutationOptions } from "@/gen-backend/hooks/use-account-controller-update-preset";
export { useAccountControllerUpdatePreset } from "@/gen-backend/hooks/use-account-controller-update-preset";
export { adminAuthControllerCreateAdminMutationKey } from "@/gen-backend/hooks/use-admin-auth-controller-create-admin";
export { adminAuthControllerCreateAdminMutationOptions } from "@/gen-backend/hooks/use-admin-auth-controller-create-admin";
export { useAdminAuthControllerCreateAdmin } from "@/gen-backend/hooks/use-admin-auth-controller-create-admin";
export { adminAuthControllerLoginMutationKey } from "@/gen-backend/hooks/use-admin-auth-controller-login";
export { adminAuthControllerLoginMutationOptions } from "@/gen-backend/hooks/use-admin-auth-controller-login";
export { useAdminAuthControllerLogin } from "@/gen-backend/hooks/use-admin-auth-controller-login";
export { adminControllerGenerateCodesMutationKey } from "@/gen-backend/hooks/use-admin-controller-generate-codes";
export { adminControllerGenerateCodesMutationOptions } from "@/gen-backend/hooks/use-admin-controller-generate-codes";
export { useAdminControllerGenerateCodes } from "@/gen-backend/hooks/use-admin-controller-generate-codes";
export { adminControllerGetCampaignStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-campaign-status-suspense";
export { adminControllerGetCampaignStatusSuspenseQueryOptions } from "@/gen-backend/hooks/use-admin-controller-get-campaign-status-suspense";
export { useAdminControllerGetCampaignStatusSuspense } from "@/gen-backend/hooks/use-admin-controller-get-campaign-status-suspense";
export { adminControllerGetCampaignStatusQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-campaign-status";
export { adminControllerGetCampaignStatusQueryOptions } from "@/gen-backend/hooks/use-admin-controller-get-campaign-status";
export { useAdminControllerGetCampaignStatus } from "@/gen-backend/hooks/use-admin-controller-get-campaign-status";
export { adminControllerGetDashboardSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-dashboard-suspense";
export { adminControllerGetDashboardSuspenseQueryOptions } from "@/gen-backend/hooks/use-admin-controller-get-dashboard-suspense";
export { useAdminControllerGetDashboardSuspense } from "@/gen-backend/hooks/use-admin-controller-get-dashboard-suspense";
export { adminControllerGetDashboardQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-dashboard";
export { adminControllerGetDashboardQueryOptions } from "@/gen-backend/hooks/use-admin-controller-get-dashboard";
export { useAdminControllerGetDashboard } from "@/gen-backend/hooks/use-admin-controller-get-dashboard";
export { adminControllerGetRegistrationStatsSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-registration-stats-suspense";
export { adminControllerGetRegistrationStatsSuspenseQueryOptions } from "@/gen-backend/hooks/use-admin-controller-get-registration-stats-suspense";
export { useAdminControllerGetRegistrationStatsSuspense } from "@/gen-backend/hooks/use-admin-controller-get-registration-stats-suspense";
export { adminControllerGetRegistrationStatsQueryKey } from "@/gen-backend/hooks/use-admin-controller-get-registration-stats";
export { adminControllerGetRegistrationStatsQueryOptions } from "@/gen-backend/hooks/use-admin-controller-get-registration-stats";
export { useAdminControllerGetRegistrationStats } from "@/gen-backend/hooks/use-admin-controller-get-registration-stats";
export { adminControllerListCampaignsSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-list-campaigns-suspense";
export { adminControllerListCampaignsSuspenseQueryOptions } from "@/gen-backend/hooks/use-admin-controller-list-campaigns-suspense";
export { useAdminControllerListCampaignsSuspense } from "@/gen-backend/hooks/use-admin-controller-list-campaigns-suspense";
export { adminControllerListCampaignsQueryKey } from "@/gen-backend/hooks/use-admin-controller-list-campaigns";
export { adminControllerListCampaignsQueryOptions } from "@/gen-backend/hooks/use-admin-controller-list-campaigns";
export { useAdminControllerListCampaigns } from "@/gen-backend/hooks/use-admin-controller-list-campaigns";
export { adminControllerListCodesSuspenseQueryKey } from "@/gen-backend/hooks/use-admin-controller-list-codes-suspense";
export { adminControllerListCodesSuspenseQueryOptions } from "@/gen-backend/hooks/use-admin-controller-list-codes-suspense";
export { useAdminControllerListCodesSuspense } from "@/gen-backend/hooks/use-admin-controller-list-codes-suspense";
export { adminControllerListCodesQueryKey } from "@/gen-backend/hooks/use-admin-controller-list-codes";
export { adminControllerListCodesQueryOptions } from "@/gen-backend/hooks/use-admin-controller-list-codes";
export { useAdminControllerListCodes } from "@/gen-backend/hooks/use-admin-controller-list-codes";
export { adminControllerRevokeCodeMutationKey } from "@/gen-backend/hooks/use-admin-controller-revoke-code";
export { adminControllerRevokeCodeMutationOptions } from "@/gen-backend/hooks/use-admin-controller-revoke-code";
export { useAdminControllerRevokeCode } from "@/gen-backend/hooks/use-admin-controller-revoke-code";
export { adminControllerSendCampaignMutationKey } from "@/gen-backend/hooks/use-admin-controller-send-campaign";
export { adminControllerSendCampaignMutationOptions } from "@/gen-backend/hooks/use-admin-controller-send-campaign";
export { useAdminControllerSendCampaign } from "@/gen-backend/hooks/use-admin-controller-send-campaign";
export { appControllerGetHelloSuspenseQueryKey } from "@/gen-backend/hooks/use-app-controller-get-hello-suspense";
export { appControllerGetHelloSuspenseQueryOptions } from "@/gen-backend/hooks/use-app-controller-get-hello-suspense";
export { useAppControllerGetHelloSuspense } from "@/gen-backend/hooks/use-app-controller-get-hello-suspense";
export { appControllerGetHelloQueryKey } from "@/gen-backend/hooks/use-app-controller-get-hello";
export { appControllerGetHelloQueryOptions } from "@/gen-backend/hooks/use-app-controller-get-hello";
export { useAppControllerGetHello } from "@/gen-backend/hooks/use-app-controller-get-hello";
export { authControllerChallengeMutationKey } from "@/gen-backend/hooks/use-auth-controller-challenge";
export { authControllerChallengeMutationOptions } from "@/gen-backend/hooks/use-auth-controller-challenge";
export { useAuthControllerChallenge } from "@/gen-backend/hooks/use-auth-controller-challenge";
export { authControllerLoginMutationKey } from "@/gen-backend/hooks/use-auth-controller-login";
export { authControllerLoginMutationOptions } from "@/gen-backend/hooks/use-auth-controller-login";
export { useAuthControllerLogin } from "@/gen-backend/hooks/use-auth-controller-login";
export { authControllerRegisterMutationKey } from "@/gen-backend/hooks/use-auth-controller-register";
export { authControllerRegisterMutationOptions } from "@/gen-backend/hooks/use-auth-controller-register";
export { useAuthControllerRegister } from "@/gen-backend/hooks/use-auth-controller-register";
export { authControllerResolveChatUserForAiMutationKey } from "@/gen-backend/hooks/use-auth-controller-resolve-chat-user-for-ai";
export { authControllerResolveChatUserForAiMutationOptions } from "@/gen-backend/hooks/use-auth-controller-resolve-chat-user-for-ai";
export { useAuthControllerResolveChatUserForAi } from "@/gen-backend/hooks/use-auth-controller-resolve-chat-user-for-ai";
export { authControllerTestLoginMutationKey } from "@/gen-backend/hooks/use-auth-controller-test-login";
export { authControllerTestLoginMutationOptions } from "@/gen-backend/hooks/use-auth-controller-test-login";
export { useAuthControllerTestLogin } from "@/gen-backend/hooks/use-auth-controller-test-login";
export { authControllerVerifySessionForAiMutationKey } from "@/gen-backend/hooks/use-auth-controller-verify-session-for-ai";
export { authControllerVerifySessionForAiMutationOptions } from "@/gen-backend/hooks/use-auth-controller-verify-session-for-ai";
export { useAuthControllerVerifySessionForAi } from "@/gen-backend/hooks/use-auth-controller-verify-session-for-ai";
export { authControllerVerifyMutationKey } from "@/gen-backend/hooks/use-auth-controller-verify";
export { authControllerVerifyMutationOptions } from "@/gen-backend/hooks/use-auth-controller-verify";
export { useAuthControllerVerify } from "@/gen-backend/hooks/use-auth-controller-verify";
export { chatUsageInternalControllerCommitMutationKey } from "@/gen-backend/hooks/use-chat-usage-internal-controller-commit";
export { chatUsageInternalControllerCommitMutationOptions } from "@/gen-backend/hooks/use-chat-usage-internal-controller-commit";
export { useChatUsageInternalControllerCommit } from "@/gen-backend/hooks/use-chat-usage-internal-controller-commit";
export { chatUsageInternalControllerGetSnapshotSuspenseQueryKey } from "@/gen-backend/hooks/use-chat-usage-internal-controller-get-snapshot-suspense";
export { chatUsageInternalControllerGetSnapshotSuspenseQueryOptions } from "@/gen-backend/hooks/use-chat-usage-internal-controller-get-snapshot-suspense";
export { useChatUsageInternalControllerGetSnapshotSuspense } from "@/gen-backend/hooks/use-chat-usage-internal-controller-get-snapshot-suspense";
export { chatUsageInternalControllerGetSnapshotQueryKey } from "@/gen-backend/hooks/use-chat-usage-internal-controller-get-snapshot";
export { chatUsageInternalControllerGetSnapshotQueryOptions } from "@/gen-backend/hooks/use-chat-usage-internal-controller-get-snapshot";
export { useChatUsageInternalControllerGetSnapshot } from "@/gen-backend/hooks/use-chat-usage-internal-controller-get-snapshot";
export { creditControllerGetMeSuspenseQueryKey } from "@/gen-backend/hooks/use-credit-controller-get-me-suspense";
export { creditControllerGetMeSuspenseQueryOptions } from "@/gen-backend/hooks/use-credit-controller-get-me-suspense";
export { useCreditControllerGetMeSuspense } from "@/gen-backend/hooks/use-credit-controller-get-me-suspense";
export { creditControllerGetMeQueryKey } from "@/gen-backend/hooks/use-credit-controller-get-me";
export { creditControllerGetMeQueryOptions } from "@/gen-backend/hooks/use-credit-controller-get-me";
export { useCreditControllerGetMe } from "@/gen-backend/hooks/use-credit-controller-get-me";
export { creditControllerListLedgerSuspenseQueryKey } from "@/gen-backend/hooks/use-credit-controller-list-ledger-suspense";
export { creditControllerListLedgerSuspenseQueryOptions } from "@/gen-backend/hooks/use-credit-controller-list-ledger-suspense";
export { useCreditControllerListLedgerSuspense } from "@/gen-backend/hooks/use-credit-controller-list-ledger-suspense";
export { creditControllerListLedgerQueryKey } from "@/gen-backend/hooks/use-credit-controller-list-ledger";
export { creditControllerListLedgerQueryOptions } from "@/gen-backend/hooks/use-credit-controller-list-ledger";
export { useCreditControllerListLedger } from "@/gen-backend/hooks/use-credit-controller-list-ledger";
export { creditInternalControllerApplyMutationKey } from "@/gen-backend/hooks/use-credit-internal-controller-apply";
export { creditInternalControllerApplyMutationOptions } from "@/gen-backend/hooks/use-credit-internal-controller-apply";
export { useCreditInternalControllerApply } from "@/gen-backend/hooks/use-credit-internal-controller-apply";
export { creditPackageControllerListSuspenseQueryKey } from "@/gen-backend/hooks/use-credit-package-controller-list-suspense";
export { creditPackageControllerListSuspenseQueryOptions } from "@/gen-backend/hooks/use-credit-package-controller-list-suspense";
export { useCreditPackageControllerListSuspense } from "@/gen-backend/hooks/use-credit-package-controller-list-suspense";
export { creditPackageControllerListQueryKey } from "@/gen-backend/hooks/use-credit-package-controller-list";
export { creditPackageControllerListQueryOptions } from "@/gen-backend/hooks/use-credit-package-controller-list";
export { useCreditPackageControllerList } from "@/gen-backend/hooks/use-credit-package-controller-list";
export { emailControllerSendTestEmailMutationKey } from "@/gen-backend/hooks/use-email-controller-send-test-email";
export { emailControllerSendTestEmailMutationOptions } from "@/gen-backend/hooks/use-email-controller-send-test-email";
export { useEmailControllerSendTestEmail } from "@/gen-backend/hooks/use-email-controller-send-test-email";
export { healthControllerCheckSuspenseQueryKey } from "@/gen-backend/hooks/use-health-controller-check-suspense";
export { healthControllerCheckSuspenseQueryOptions } from "@/gen-backend/hooks/use-health-controller-check-suspense";
export { useHealthControllerCheckSuspense } from "@/gen-backend/hooks/use-health-controller-check-suspense";
export { healthControllerCheckQueryKey } from "@/gen-backend/hooks/use-health-controller-check";
export { healthControllerCheckQueryOptions } from "@/gen-backend/hooks/use-health-controller-check";
export { useHealthControllerCheck } from "@/gen-backend/hooks/use-health-controller-check";
export { poolsControllerGetPoolHistorySuspenseQueryKey } from "@/gen-backend/hooks/use-pools-controller-get-pool-history-suspense";
export { poolsControllerGetPoolHistorySuspenseQueryOptions } from "@/gen-backend/hooks/use-pools-controller-get-pool-history-suspense";
export { usePoolsControllerGetPoolHistorySuspense } from "@/gen-backend/hooks/use-pools-controller-get-pool-history-suspense";
export { poolsControllerGetPoolHistoryQueryKey } from "@/gen-backend/hooks/use-pools-controller-get-pool-history";
export { poolsControllerGetPoolHistoryQueryOptions } from "@/gen-backend/hooks/use-pools-controller-get-pool-history";
export { usePoolsControllerGetPoolHistory } from "@/gen-backend/hooks/use-pools-controller-get-pool-history";
export { poolsControllerGetPoolsSuspenseQueryKey } from "@/gen-backend/hooks/use-pools-controller-get-pools-suspense";
export { poolsControllerGetPoolsSuspenseQueryOptions } from "@/gen-backend/hooks/use-pools-controller-get-pools-suspense";
export { usePoolsControllerGetPoolsSuspense } from "@/gen-backend/hooks/use-pools-controller-get-pools-suspense";
export { poolsControllerGetPoolsQueryKey } from "@/gen-backend/hooks/use-pools-controller-get-pools";
export { poolsControllerGetPoolsQueryOptions } from "@/gen-backend/hooks/use-pools-controller-get-pools";
export { usePoolsControllerGetPools } from "@/gen-backend/hooks/use-pools-controller-get-pools";
export { portfolioControllerGetHistorySuspenseQueryKey } from "@/gen-backend/hooks/use-portfolio-controller-get-history-suspense";
export { portfolioControllerGetHistorySuspenseQueryOptions } from "@/gen-backend/hooks/use-portfolio-controller-get-history-suspense";
export { usePortfolioControllerGetHistorySuspense } from "@/gen-backend/hooks/use-portfolio-controller-get-history-suspense";
export { portfolioControllerGetHistoryQueryKey } from "@/gen-backend/hooks/use-portfolio-controller-get-history";
export { portfolioControllerGetHistoryQueryOptions } from "@/gen-backend/hooks/use-portfolio-controller-get-history";
export { usePortfolioControllerGetHistory } from "@/gen-backend/hooks/use-portfolio-controller-get-history";
export { portfolioControllerRegisterAddressMutationKey } from "@/gen-backend/hooks/use-portfolio-controller-register-address";
export { portfolioControllerRegisterAddressMutationOptions } from "@/gen-backend/hooks/use-portfolio-controller-register-address";
export { usePortfolioControllerRegisterAddress } from "@/gen-backend/hooks/use-portfolio-controller-register-address";
export { protocolControllerGetAllApysSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-all-apys-suspense";
export { protocolControllerGetAllApysSuspenseQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-all-apys-suspense";
export { useProtocolControllerGetAllApysSuspense } from "@/gen-backend/hooks/use-protocol-controller-get-all-apys-suspense";
export { protocolControllerGetAllApysQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-all-apys";
export { protocolControllerGetAllApysQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-all-apys";
export { useProtocolControllerGetAllApys } from "@/gen-backend/hooks/use-protocol-controller-get-all-apys";
export { protocolControllerGetAllProtocolsSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-all-protocols-suspense";
export { protocolControllerGetAllProtocolsSuspenseQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-all-protocols-suspense";
export { useProtocolControllerGetAllProtocolsSuspense } from "@/gen-backend/hooks/use-protocol-controller-get-all-protocols-suspense";
export { protocolControllerGetAllProtocolsQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-all-protocols";
export { protocolControllerGetAllProtocolsQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-all-protocols";
export { useProtocolControllerGetAllProtocols } from "@/gen-backend/hooks/use-protocol-controller-get-all-protocols";
export { protocolControllerGetApyByChainSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-apy-by-chain-suspense";
export { protocolControllerGetApyByChainSuspenseQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-apy-by-chain-suspense";
export { useProtocolControllerGetApyByChainSuspense } from "@/gen-backend/hooks/use-protocol-controller-get-apy-by-chain-suspense";
export { protocolControllerGetApyByChainQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-apy-by-chain";
export { protocolControllerGetApyByChainQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-apy-by-chain";
export { useProtocolControllerGetApyByChain } from "@/gen-backend/hooks/use-protocol-controller-get-apy-by-chain";
export { protocolControllerGetAvailableAssetsSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-available-assets-suspense";
export { protocolControllerGetAvailableAssetsSuspenseQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-available-assets-suspense";
export { useProtocolControllerGetAvailableAssetsSuspense } from "@/gen-backend/hooks/use-protocol-controller-get-available-assets-suspense";
export { protocolControllerGetAvailableAssetsQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-available-assets";
export { protocolControllerGetAvailableAssetsQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-available-assets";
export { useProtocolControllerGetAvailableAssets } from "@/gen-backend/hooks/use-protocol-controller-get-available-assets";
export { protocolControllerGetLendingApySuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-lending-apy-suspense";
export { protocolControllerGetLendingApySuspenseQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-lending-apy-suspense";
export { useProtocolControllerGetLendingApySuspense } from "@/gen-backend/hooks/use-protocol-controller-get-lending-apy-suspense";
export { protocolControllerGetLendingApyQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-lending-apy";
export { protocolControllerGetLendingApyQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-lending-apy";
export { useProtocolControllerGetLendingApy } from "@/gen-backend/hooks/use-protocol-controller-get-lending-apy";
export { protocolControllerGetUserPositionSuspenseQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-user-position-suspense";
export { protocolControllerGetUserPositionSuspenseQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-user-position-suspense";
export { useProtocolControllerGetUserPositionSuspense } from "@/gen-backend/hooks/use-protocol-controller-get-user-position-suspense";
export { protocolControllerGetUserPositionQueryKey } from "@/gen-backend/hooks/use-protocol-controller-get-user-position";
export { protocolControllerGetUserPositionQueryOptions } from "@/gen-backend/hooks/use-protocol-controller-get-user-position";
export { useProtocolControllerGetUserPosition } from "@/gen-backend/hooks/use-protocol-controller-get-user-position";
export { rebalanceControllerGetStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-rebalance-controller-get-status-suspense";
export { rebalanceControllerGetStatusSuspenseQueryOptions } from "@/gen-backend/hooks/use-rebalance-controller-get-status-suspense";
export { useRebalanceControllerGetStatusSuspense } from "@/gen-backend/hooks/use-rebalance-controller-get-status-suspense";
export { rebalanceControllerGetStatusQueryKey } from "@/gen-backend/hooks/use-rebalance-controller-get-status";
export { rebalanceControllerGetStatusQueryOptions } from "@/gen-backend/hooks/use-rebalance-controller-get-status";
export { useRebalanceControllerGetStatus } from "@/gen-backend/hooks/use-rebalance-controller-get-status";
export { rebalanceControllerHaltMutationKey } from "@/gen-backend/hooks/use-rebalance-controller-halt";
export { rebalanceControllerHaltMutationOptions } from "@/gen-backend/hooks/use-rebalance-controller-halt";
export { useRebalanceControllerHalt } from "@/gen-backend/hooks/use-rebalance-controller-halt";
export { rebalanceControllerResumeMutationKey } from "@/gen-backend/hooks/use-rebalance-controller-resume";
export { rebalanceControllerResumeMutationOptions } from "@/gen-backend/hooks/use-rebalance-controller-resume";
export { useRebalanceControllerResume } from "@/gen-backend/hooks/use-rebalance-controller-resume";
export { rebalanceControllerRunHarvestManualMutationKey } from "@/gen-backend/hooks/use-rebalance-controller-run-harvest-manual";
export { rebalanceControllerRunHarvestManualMutationOptions } from "@/gen-backend/hooks/use-rebalance-controller-run-harvest-manual";
export { useRebalanceControllerRunHarvestManual } from "@/gen-backend/hooks/use-rebalance-controller-run-harvest-manual";
export { rebalanceControllerRunManualMutationKey } from "@/gen-backend/hooks/use-rebalance-controller-run-manual";
export { rebalanceControllerRunManualMutationOptions } from "@/gen-backend/hooks/use-rebalance-controller-run-manual";
export { useRebalanceControllerRunManual } from "@/gen-backend/hooks/use-rebalance-controller-run-manual";
export { userControllerGetUserSuspenseQueryKey } from "@/gen-backend/hooks/use-user-controller-get-user-suspense";
export { userControllerGetUserSuspenseQueryOptions } from "@/gen-backend/hooks/use-user-controller-get-user-suspense";
export { useUserControllerGetUserSuspense } from "@/gen-backend/hooks/use-user-controller-get-user-suspense";
export { userControllerGetUserQueryKey } from "@/gen-backend/hooks/use-user-controller-get-user";
export { userControllerGetUserQueryOptions } from "@/gen-backend/hooks/use-user-controller-get-user";
export { useUserControllerGetUser } from "@/gen-backend/hooks/use-user-controller-get-user";
export { userMeControllerGetMeSuspenseQueryKey } from "@/gen-backend/hooks/use-user-me-controller-get-me-suspense";
export { userMeControllerGetMeSuspenseQueryOptions } from "@/gen-backend/hooks/use-user-me-controller-get-me-suspense";
export { useUserMeControllerGetMeSuspense } from "@/gen-backend/hooks/use-user-me-controller-get-me-suspense";
export { userMeControllerGetMeQueryKey } from "@/gen-backend/hooks/use-user-me-controller-get-me";
export { userMeControllerGetMeQueryOptions } from "@/gen-backend/hooks/use-user-me-controller-get-me";
export { useUserMeControllerGetMe } from "@/gen-backend/hooks/use-user-me-controller-get-me";
export { waitlistControllerAttachContactMutationKey } from "@/gen-backend/hooks/use-waitlist-controller-attach-contact";
export { waitlistControllerAttachContactMutationOptions } from "@/gen-backend/hooks/use-waitlist-controller-attach-contact";
export { useWaitlistControllerAttachContact } from "@/gen-backend/hooks/use-waitlist-controller-attach-contact";
export { waitlistControllerGetStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-waitlist-controller-get-status-suspense";
export { waitlistControllerGetStatusSuspenseQueryOptions } from "@/gen-backend/hooks/use-waitlist-controller-get-status-suspense";
export { useWaitlistControllerGetStatusSuspense } from "@/gen-backend/hooks/use-waitlist-controller-get-status-suspense";
export { waitlistControllerGetStatusQueryKey } from "@/gen-backend/hooks/use-waitlist-controller-get-status";
export { waitlistControllerGetStatusQueryOptions } from "@/gen-backend/hooks/use-waitlist-controller-get-status";
export { useWaitlistControllerGetStatus } from "@/gen-backend/hooks/use-waitlist-controller-get-status";
export { waitlistControllerRegisterWalletMutationKey } from "@/gen-backend/hooks/use-waitlist-controller-register-wallet";
export { waitlistControllerRegisterWalletMutationOptions } from "@/gen-backend/hooks/use-waitlist-controller-register-wallet";
export { useWaitlistControllerRegisterWallet } from "@/gen-backend/hooks/use-waitlist-controller-register-wallet";
export { waitlistControllerRegisterMutationKey } from "@/gen-backend/hooks/use-waitlist-controller-register";
export { waitlistControllerRegisterMutationOptions } from "@/gen-backend/hooks/use-waitlist-controller-register";
export { useWaitlistControllerRegister } from "@/gen-backend/hooks/use-waitlist-controller-register";
export { waitlistControllerRequestChallengeMutationKey } from "@/gen-backend/hooks/use-waitlist-controller-request-challenge";
export { waitlistControllerRequestChallengeMutationOptions } from "@/gen-backend/hooks/use-waitlist-controller-request-challenge";
export { useWaitlistControllerRequestChallenge } from "@/gen-backend/hooks/use-waitlist-controller-request-challenge";
export { waitlistControllerVerifyReferralSuspenseQueryKey } from "@/gen-backend/hooks/use-waitlist-controller-verify-referral-suspense";
export { waitlistControllerVerifyReferralSuspenseQueryOptions } from "@/gen-backend/hooks/use-waitlist-controller-verify-referral-suspense";
export { useWaitlistControllerVerifyReferralSuspense } from "@/gen-backend/hooks/use-waitlist-controller-verify-referral-suspense";
export { waitlistControllerVerifyReferralQueryKey } from "@/gen-backend/hooks/use-waitlist-controller-verify-referral";
export { waitlistControllerVerifyReferralQueryOptions } from "@/gen-backend/hooks/use-waitlist-controller-verify-referral";
export { useWaitlistControllerVerifyReferral } from "@/gen-backend/hooks/use-waitlist-controller-verify-referral";
export { welcomeRewardControllerGetFullStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-welcome-reward-controller-get-full-status-suspense";
export { welcomeRewardControllerGetFullStatusSuspenseQueryOptions } from "@/gen-backend/hooks/use-welcome-reward-controller-get-full-status-suspense";
export { useWelcomeRewardControllerGetFullStatusSuspense } from "@/gen-backend/hooks/use-welcome-reward-controller-get-full-status-suspense";
export { welcomeRewardControllerGetFullStatusQueryKey } from "@/gen-backend/hooks/use-welcome-reward-controller-get-full-status";
export { welcomeRewardControllerGetFullStatusQueryOptions } from "@/gen-backend/hooks/use-welcome-reward-controller-get-full-status";
export { useWelcomeRewardControllerGetFullStatus } from "@/gen-backend/hooks/use-welcome-reward-controller-get-full-status";
export { welcomeRewardControllerGetStatusSuspenseQueryKey } from "@/gen-backend/hooks/use-welcome-reward-controller-get-status-suspense";
export { welcomeRewardControllerGetStatusSuspenseQueryOptions } from "@/gen-backend/hooks/use-welcome-reward-controller-get-status-suspense";
export { useWelcomeRewardControllerGetStatusSuspense } from "@/gen-backend/hooks/use-welcome-reward-controller-get-status-suspense";
export { welcomeRewardControllerGetStatusQueryKey } from "@/gen-backend/hooks/use-welcome-reward-controller-get-status";
export { welcomeRewardControllerGetStatusQueryOptions } from "@/gen-backend/hooks/use-welcome-reward-controller-get-status";
export { useWelcomeRewardControllerGetStatus } from "@/gen-backend/hooks/use-welcome-reward-controller-get-status";
export { welcomeRewardControllerMarkSeenMutationKey } from "@/gen-backend/hooks/use-welcome-reward-controller-mark-seen";
export { welcomeRewardControllerMarkSeenMutationOptions } from "@/gen-backend/hooks/use-welcome-reward-controller-mark-seen";
export { useWelcomeRewardControllerMarkSeen } from "@/gen-backend/hooks/use-welcome-reward-controller-mark-seen";
export { welcomeRewardControllerScanVolumeMutationKey } from "@/gen-backend/hooks/use-welcome-reward-controller-scan-volume";
export { welcomeRewardControllerScanVolumeMutationOptions } from "@/gen-backend/hooks/use-welcome-reward-controller-scan-volume";
export { useWelcomeRewardControllerScanVolume } from "@/gen-backend/hooks/use-welcome-reward-controller-scan-volume";
export { welcomeRewardControllerTrackTransactionMutationKey } from "@/gen-backend/hooks/use-welcome-reward-controller-track-transaction";
export { welcomeRewardControllerTrackTransactionMutationOptions } from "@/gen-backend/hooks/use-welcome-reward-controller-track-transaction";
export { useWelcomeRewardControllerTrackTransaction } from "@/gen-backend/hooks/use-welcome-reward-controller-track-transaction";
export { applyDeltaDtoReasonEnum } from "@/gen-backend/types/apply-delta-dto";
export { poolsControllerGetPoolsQueryParamsRiskPresetEnum } from "@/gen-backend/types/pools-controller-get-pools";
export { protocolControllerGetLendingApyQueryParamsProtocolEnum } from "@/gen-backend/types/protocol-controller-get-lending-apy";
export { protocolControllerGetLendingApyQueryParamsChainEnum } from "@/gen-backend/types/protocol-controller-get-lending-apy";
export { protocolControllerGetUserPositionQueryParamsProtocolEnum } from "@/gen-backend/types/protocol-controller-get-user-position";
export { registerWalletDtoWalletProviderEnum } from "@/gen-backend/types/register-wallet-dto";