/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SocialAccountsControllerFindAllQueryResponse } from "@/gen-quest/types/social-accounts-controller-find-all";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { socialAccountsControllerFindAll } from "@/gen-quest/client/social-accounts-controller-find-all";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const socialAccountsControllerFindAllQueryKey = () => [{ url: '/api/users/me/social-accounts' }] as const

export type SocialAccountsControllerFindAllQueryKey = ReturnType<typeof socialAccountsControllerFindAllQueryKey>

export function socialAccountsControllerFindAllQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = socialAccountsControllerFindAllQueryKey()
        return queryOptions<SocialAccountsControllerFindAllQueryResponse, ResponseErrorConfig<Error>, SocialAccountsControllerFindAllQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return socialAccountsControllerFindAll({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get all linked social accounts
 * {@link /api/users/me/social-accounts}
 */
export function useSocialAccountsControllerFindAll<TData = SocialAccountsControllerFindAllQueryResponse, TQueryData = SocialAccountsControllerFindAllQueryResponse, TQueryKey extends QueryKey = SocialAccountsControllerFindAllQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<SocialAccountsControllerFindAllQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? socialAccountsControllerFindAllQueryKey()
         

         const query = useQuery({
          ...socialAccountsControllerFindAllQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}