/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AccountControllerDepositExecuteMutationResponse } from "@/gen-quest/types/account-controller-deposit-execute";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAccountControllerDepositExecuteUrl() {
  const res = { method: 'POST', url: `/api/account/deposit-trading/execute` as const }
  return res
}

/**
 * @summary Bot deposits the funded keeper into the strategy (call after fund confirms)
 * {@link /api/account/deposit-trading/execute}
 */
export async function accountControllerDepositExecute(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AccountControllerDepositExecuteMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getAccountControllerDepositExecuteUrl().url.toString(), ... requestConfig })
  return res.data
}