/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AdminControllerCreateCampaignMutationRequest,
  AdminControllerCreateCampaignMutationResponse,
} from "@/gen-quest/types/admin-controller-create-campaign";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getAdminControllerCreateCampaignUrl() {
  const res = { method: "POST", url: `/api/quest/admin/campaigns` as const };
  return res;
}

/**
 * {@link /api/quest/admin/campaigns}
 */
export async function adminControllerCreateCampaign(
  data: AdminControllerCreateCampaignMutationRequest,
  config: Partial<RequestConfig<AdminControllerCreateCampaignMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AdminControllerCreateCampaignMutationResponse,
    ResponseErrorConfig<Error>,
    AdminControllerCreateCampaignMutationRequest
  >({
    method: "POST",
    url: getAdminControllerCreateCampaignUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
