/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminControllerRemoveTaskMutationResponse, AdminControllerRemoveTaskPathParams } from "@/gen-quest/types/admin-controller-remove-task";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getAdminControllerRemoveTaskUrl(taskId: AdminControllerRemoveTaskPathParams["taskId"]) {
  const res = { method: 'DELETE', url: `/api/admin/tasks/${taskId}` as const }
  return res
}

/**
 * {@link /api/admin/tasks/:taskId}
 */
export async function adminControllerRemoveTask(taskId: AdminControllerRemoveTaskPathParams["taskId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerRemoveTaskMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getAdminControllerRemoveTaskUrl(taskId).url.toString(), ... requestConfig })
  return res.data
}