/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  AdminControllerUpdateReferralConfigMutationRequest,
  AdminControllerUpdateReferralConfigMutationResponse,
  AdminControllerUpdateReferralConfigPathParams,
} from "@/gen-quest/types/admin-controller-update-referral-config";

function getAdminControllerUpdateReferralConfigUrl(
  layer: AdminControllerUpdateReferralConfigPathParams["layer"]
) {
  const res = { method: "PATCH", url: `/api/quest/admin/referral/config/${layer}` as const };
  return res;
}

/**
 * {@link /api/quest/admin/referral/config/:layer}
 */
export async function adminControllerUpdateReferralConfig(
  layer: AdminControllerUpdateReferralConfigPathParams["layer"],
  data: AdminControllerUpdateReferralConfigMutationRequest,
  config: Partial<RequestConfig<AdminControllerUpdateReferralConfigMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AdminControllerUpdateReferralConfigMutationResponse,
    ResponseErrorConfig<Error>,
    AdminControllerUpdateReferralConfigMutationRequest
  >({
    method: "PATCH",
    url: getAdminControllerUpdateReferralConfigUrl(layer).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
