/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminControllerApproveUserTaskMutationResponse, AdminControllerApproveUserTaskPathParams } from "@/gen-quest/types/admin-controller-approve-user-task";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminControllerApproveUserTaskUrl(id: AdminControllerApproveUserTaskPathParams["id"]) {
  const res = { method: 'POST', url: `/api/quest/admin/user-tasks/${id}/approve` as const }
  return res
}

/**
 * {@link /api/quest/admin/user-tasks/:id/approve}
 */
export async function adminControllerApproveUserTask(id: AdminControllerApproveUserTaskPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerApproveUserTaskMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getAdminControllerApproveUserTaskUrl(id).url.toString(), ... requestConfig })
  return res.data
}