/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AnalyticsControllerActivityFeedQueryResponse } from "@/gen-quest/types/analytics-controller-activity-feed";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAnalyticsControllerActivityFeedUrl() {
  const res = { method: 'GET', url: `/api/quest/leaderboard/activity` as const }
  return res
}

/**
 * {@link /api/quest/leaderboard/activity}
 */
export async function analyticsControllerActivityFeed(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AnalyticsControllerActivityFeedQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getAnalyticsControllerActivityFeedUrl().url.toString(), ... requestConfig })
  return res.data
}