/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AnalyticsControllerGlobalLeaderboardQueryResponse } from "@/gen-quest/types/analytics-controller-global-leaderboard";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAnalyticsControllerGlobalLeaderboardUrl() {
  const res = { method: 'GET', url: `/api/quest/leaderboard/global` as const }
  return res
}

/**
 * {@link /api/quest/leaderboard/global}
 */
export async function analyticsControllerGlobalLeaderboard(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AnalyticsControllerGlobalLeaderboardQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getAnalyticsControllerGlobalLeaderboardUrl().url.toString(), ... requestConfig })
  return res.data
}