/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  AuthControllerGetWalletNonceMutationRequest,
  AuthControllerGetWalletNonceMutationResponse,
} from "@/gen-quest/types/auth-controller-get-wallet-nonce";

function getAuthControllerGetWalletNonceUrl() {
  const res = { method: "POST", url: `/api/auth/challenge` as const };
  return res;
}

/**
 * {@link /api/auth/challenge}
 */
export async function authControllerGetWalletNonce(
  data: AuthControllerGetWalletNonceMutationRequest,
  config: Partial<RequestConfig<AuthControllerGetWalletNonceMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AuthControllerGetWalletNonceMutationResponse,
    ResponseErrorConfig<Error>,
    AuthControllerGetWalletNonceMutationRequest
  >({
    method: "POST",
    url: getAuthControllerGetWalletNonceUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
