/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CampaignsControllerJoinCampaignMutationResponse,
  CampaignsControllerJoinCampaignPathParams,
} from "@/gen-quest/types/campaigns-controller-join-campaign";

function getCampaignsControllerJoinCampaignUrl(
  id: CampaignsControllerJoinCampaignPathParams["id"]
) {
  const res = { method: "POST", url: `/api/campaigns/${id}/join` as const };
  return res;
}

/**
 * {@link /api/campaigns/:id/join}
 */
export async function campaignsControllerJoinCampaign(
  id: CampaignsControllerJoinCampaignPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CampaignsControllerJoinCampaignMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getCampaignsControllerJoinCampaignUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
