/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CampaignsControllerFindAllQueryParams,
  CampaignsControllerFindAllQueryResponse,
} from "@/gen-quest/types/campaigns-controller-find-all";

function getCampaignsControllerFindAllUrl() {
  const res = { method: "GET", url: `/api/quest/campaigns` as const };
  return res;
}

/**
 * {@link /api/quest/campaigns}
 */
export async function campaignsControllerFindAll(
  params?: CampaignsControllerFindAllQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CampaignsControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getCampaignsControllerFindAllUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
