/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CampaignsControllerClaimCampaignMutationResponse,
  CampaignsControllerClaimCampaignPathParams,
} from "@/gen-quest/types/campaigns-controller-claim-campaign";

function getCampaignsControllerClaimCampaignUrl(
  id: CampaignsControllerClaimCampaignPathParams["id"]
) {
  const res = { method: "POST", url: `/api/campaigns/${id}/claim` as const };
  return res;
}

/**
 * {@link /api/campaigns/:id/claim}
 */
export async function campaignsControllerClaimCampaign(
  id: CampaignsControllerClaimCampaignPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CampaignsControllerClaimCampaignMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getCampaignsControllerClaimCampaignUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
