/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  CampaignsControllerGetTasksPathParams,
  CampaignsControllerGetTasksQueryResponse,
} from "@/gen-quest/types/campaigns-controller-get-tasks";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getCampaignsControllerGetTasksUrl(id: CampaignsControllerGetTasksPathParams["id"]) {
  const res = { method: "GET", url: `/api/quest/campaigns/${id}/tasks` as const };
  return res;
}

/**
 * {@link /api/quest/campaigns/:id/tasks}
 */
export async function campaignsControllerGetTasks(
  id: CampaignsControllerGetTasksPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CampaignsControllerGetTasksQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getCampaignsControllerGetTasksUrl(id).url.toString(), ...requestConfig });
  return res.data;
}
