/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatUsageControllerDeductMutationResponse } from "@/gen-quest/types/chat-usage-controller-deduct";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getChatUsageControllerDeductUrl() {
  const res = { method: "POST", url: `/api/chat-usage/deduct` as const };
  return res;
}

/**
 * @summary Deduct one chat turn for the authenticated user
 * {@link /api/chat-usage/deduct}
 */
export async function chatUsageControllerDeduct(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ChatUsageControllerDeductMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "POST", url: getChatUsageControllerDeductUrl().url.toString(), ...requestConfig });
  return res.data;
}
