/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { DailyMissionsControllerListQueryResponse } from "@/gen-quest/types/daily-missions-controller-list";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getDailyMissionsControllerListUrl() {
  const res = { method: 'GET', url: `/api/quest/daily-missions` as const }
  return res
}

/**
 * {@link /api/quest/daily-missions}
 */
export async function dailyMissionsControllerList(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DailyMissionsControllerListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getDailyMissionsControllerListUrl().url.toString(), ... requestConfig })
  return res.data
}