/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  FomoAdminControllerRemoveMutationResponse,
  FomoAdminControllerRemovePathParams,
} from "@/gen-quest/types/fomo-admin-controller-remove";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getFomoAdminControllerRemoveUrl(id: FomoAdminControllerRemovePathParams["id"]) {
  const res = { method: "DELETE", url: `/api/quest/admin/fomo/${id}` as const };
  return res;
}

/**
 * {@link /api/quest/admin/fomo/:id}
 */
export async function fomoAdminControllerRemove(
  id: FomoAdminControllerRemovePathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FomoAdminControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getFomoAdminControllerRemoveUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
