/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FomoControllerGetActiveQueryResponse } from "@/gen-quest/types/fomo-controller-get-active";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getFomoControllerGetActiveUrl() {
  const res = { method: "GET", url: `/api/quest/fomo/active` as const };
  return res;
}

/**
 * {@link /api/quest/fomo/active}
 */
export async function fomoControllerGetActive(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FomoControllerGetActiveQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getFomoControllerGetActiveUrl().url.toString(), ...requestConfig });
  return res.data;
}
