/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerGetFeeBalanceQueryResponse } from "@/gen-quest/types/marketplace-controller-get-fee-balance";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerGetFeeBalanceUrl() {
  const res = { method: 'GET', url: `/api/marketplace/fees/balance` as const }
  return res
}

/**
 * @summary Get publisher's claimable fee balance
 * {@link /api/marketplace/fees/balance}
 */
export async function marketplaceControllerGetFeeBalance(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerGetFeeBalanceQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getMarketplaceControllerGetFeeBalanceUrl().url.toString(), ... requestConfig })
  return res.data
}