/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketplaceControllerGetPublishedStrategiesQueryResponse } from "@/gen-quest/types/marketplace-controller-get-published-strategies";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getMarketplaceControllerGetPublishedStrategiesUrl() {
  const res = { method: "GET", url: `/api/marketplace/publisher/strategies` as const };
  return res;
}

/**
 * @summary List strategies published by the authenticated wallet
 * {@link /api/marketplace/publisher/strategies}
 */
export async function marketplaceControllerGetPublishedStrategies(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MarketplaceControllerGetPublishedStrategiesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getMarketplaceControllerGetPublishedStrategiesUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
