/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerBuildActivateTxMutationResponse, MarketplaceControllerBuildActivateTxPathParams } from "@/gen-quest/types/marketplace-controller-build-activate-tx";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerBuildActivateTxUrl(id: MarketplaceControllerBuildActivateTxPathParams["id"]) {
  const res = { method: 'POST', url: `/api/marketplace/strategies/${id}/activate/request` as const }
  return res
}

/**
 * @summary Build unsigned activate XDR for user to sign
 * {@link /api/marketplace/strategies/:id/activate/request}
 */
export async function marketplaceControllerBuildActivateTx(id: MarketplaceControllerBuildActivateTxPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerBuildActivateTxMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getMarketplaceControllerBuildActivateTxUrl(id).url.toString(), ... requestConfig })
  return res.data
}