/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerApproveStrategyMutationResponse, MarketplaceControllerApproveStrategyPathParams } from "@/gen-quest/types/marketplace-controller-approve-strategy";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerApproveStrategyUrl(id: MarketplaceControllerApproveStrategyPathParams["id"]) {
  const res = { method: 'POST', url: `/api/marketplace/strategies/${id}/approve` as const }
  return res
}

/**
 * @summary Admin: approve a published strategy for the marketplace
 * {@link /api/marketplace/strategies/:id/approve}
 */
export async function marketplaceControllerApproveStrategy(id: MarketplaceControllerApproveStrategyPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerApproveStrategyMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getMarketplaceControllerApproveStrategyUrl(id).url.toString(), ... requestConfig })
  return res.data
}