/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  MarketplaceControllerListStrategiesQueryParams,
  MarketplaceControllerListStrategiesQueryResponse,
} from "@/gen-quest/types/marketplace-controller-list-strategies";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getMarketplaceControllerListStrategiesUrl() {
  const res = { method: "GET", url: `/api/marketplace/strategies` as const };
  return res;
}

/**
 * @summary List approved marketplace strategies
 * {@link /api/marketplace/strategies}
 */
export async function marketplaceControllerListStrategies(
  params: MarketplaceControllerListStrategiesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MarketplaceControllerListStrategiesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getMarketplaceControllerListStrategiesUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
