/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerConfirmActivateMutationResponse, MarketplaceControllerConfirmActivatePathParams } from "@/gen-quest/types/marketplace-controller-confirm-activate";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerConfirmActivateUrl(id: MarketplaceControllerConfirmActivatePathParams["id"]) {
  const res = { method: 'POST', url: `/api/marketplace/strategies/${id}/activate/confirm` as const }
  return res
}

/**
 * @summary Confirm activation after user signs TX
 * {@link /api/marketplace/strategies/:id/activate/confirm}
 */
export async function marketplaceControllerConfirmActivate(id: MarketplaceControllerConfirmActivatePathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerConfirmActivateMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getMarketplaceControllerConfirmActivateUrl(id).url.toString(), ... requestConfig })
  return res.data
}