/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  MarketplaceControllerUnpauseConfirmMutationResponse,
  MarketplaceControllerUnpauseConfirmPathParams,
} from "@/gen-quest/types/marketplace-controller-unpause-confirm";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getMarketplaceControllerUnpauseConfirmUrl(
  id: MarketplaceControllerUnpauseConfirmPathParams["id"]
) {
  const res = { method: "POST", url: `/api/marketplace/strategies/${id}/unpause/confirm` as const };
  return res;
}

/**
 * @summary Confirm unpause after publisher signs
 * {@link /api/marketplace/strategies/:id/unpause/confirm}
 */
export async function marketplaceControllerUnpauseConfirm(
  id: MarketplaceControllerUnpauseConfirmPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MarketplaceControllerUnpauseConfirmMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getMarketplaceControllerUnpauseConfirmUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
