/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  NotificationsControllerSendMutationRequest,
  NotificationsControllerSendMutationResponse,
} from "@/gen-quest/types/notifications-controller-send";

function getNotificationsControllerSendUrl() {
  const res = { method: "POST", url: `/api/notifications/send` as const };
  return res;
}

/**
 * {@link /api/notifications/send}
 */
export async function notificationsControllerSend(
  data: NotificationsControllerSendMutationRequest,
  config: Partial<RequestConfig<NotificationsControllerSendMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    NotificationsControllerSendMutationResponse,
    ResponseErrorConfig<Error>,
    NotificationsControllerSendMutationRequest
  >({
    method: "POST",
    url: getNotificationsControllerSendUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
