/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReferralControllerGetTreeQueryResponse } from "@/gen-quest/types/referral-controller-get-tree";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getReferralControllerGetTreeUrl() {
  const res = { method: 'GET', url: `/api/referral/tree` as const }
  return res
}

/**
 * {@link /api/referral/tree}
 */
export async function referralControllerGetTree(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ReferralControllerGetTreeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getReferralControllerGetTreeUrl().url.toString(), ... requestConfig })
  return res.data
}