/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { SeasonsControllerRevealAckMutationResponse } from "@/gen-quest/types/seasons-controller-reveal-ack";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getSeasonsControllerRevealAckUrl() {
  const res = { method: 'POST', url: `/api/quest/seasons/me/reveal-ack` as const }
  return res
}

/**
 * {@link /api/quest/seasons/me/reveal-ack}
 */
export async function seasonsControllerRevealAck(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<SeasonsControllerRevealAckMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getSeasonsControllerRevealAckUrl().url.toString(), ... requestConfig })
  return res.data
}