/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SeasonsControllerClaimRewardMutationResponse,
  SeasonsControllerClaimRewardPathParams,
} from "@/gen-quest/types/seasons-controller-claim-reward";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getSeasonsControllerClaimRewardUrl(id: SeasonsControllerClaimRewardPathParams["id"]) {
  const res = { method: "POST", url: `/api/quest/seasons/${id}/claim` as const };
  return res;
}

/**
 * {@link /api/quest/seasons/:id/claim}
 */
export async function seasonsControllerClaimReward(
  id: SeasonsControllerClaimRewardPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SeasonsControllerClaimRewardMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getSeasonsControllerClaimRewardUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
