/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { SponsorAdminControllerGetConfigQueryResponse } from "@/gen-quest/types/sponsor-admin-controller-get-config";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getSponsorAdminControllerGetConfigUrl() {
  const res = { method: 'GET', url: `/api/admin/sponsor/config` as const }
  return res
}

/**
 * @summary Get current sponsor config and used slot count
 * {@link /api/admin/sponsor/config}
 */
export async function sponsorAdminControllerGetConfig(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<SponsorAdminControllerGetConfigQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getSponsorAdminControllerGetConfigUrl().url.toString(), ... requestConfig })
  return res.data
}