/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TasksControllerSubmitProofMutationRequest, TasksControllerSubmitProofMutationResponse, TasksControllerSubmitProofPathParams } from "@/gen-quest/types/tasks-controller-submit-proof";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getTasksControllerSubmitProofUrl(id: TasksControllerSubmitProofPathParams["id"]) {
  const res = { method: 'POST', url: `/api/tasks/${id}/submit-proof` as const }
  return res
}

/**
 * {@link /api/tasks/:id/submit-proof}
 */
export async function tasksControllerSubmitProof(id: TasksControllerSubmitProofPathParams["id"], data: TasksControllerSubmitProofMutationRequest, config: Partial<RequestConfig<TasksControllerSubmitProofMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<TasksControllerSubmitProofMutationResponse, ResponseErrorConfig<Error>, TasksControllerSubmitProofMutationRequest>({ method : "POST", url : getTasksControllerSubmitProofUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}