/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { TasksControllerGetClaimStatusQueryResponse, TasksControllerGetClaimStatusPathParams } from "@/gen-quest/types/tasks-controller-get-claim-status";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getTasksControllerGetClaimStatusUrl(id: TasksControllerGetClaimStatusPathParams["id"]) {
  const res = { method: 'GET', url: `/api/quest/tasks/${id}/claim/status` as const }
  return res
}

/**
 * {@link /api/quest/tasks/:id/claim/status}
 */
export async function tasksControllerGetClaimStatus(id: TasksControllerGetClaimStatusPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TasksControllerGetClaimStatusQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getTasksControllerGetClaimStatusUrl(id).url.toString(), ... requestConfig })
  return res.data
}