/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  TasksControllerGetStatusPathParams,
  TasksControllerGetStatusQueryResponse,
} from "@/gen-quest/types/tasks-controller-get-status";

function getTasksControllerGetStatusUrl(id: TasksControllerGetStatusPathParams["id"]) {
  const res = { method: "GET", url: `/api/quest/tasks/${id}/status` as const };
  return res;
}

/**
 * {@link /api/quest/tasks/:id/status}
 */
export async function tasksControllerGetStatus(
  id: TasksControllerGetStatusPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    TasksControllerGetStatusQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getTasksControllerGetStatusUrl(id).url.toString(), ...requestConfig });
  return res.data;
}
