/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TasksControllerClaimTaskMutationResponse, TasksControllerClaimTaskPathParams } from "@/gen-quest/types/tasks-controller-claim-task";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getTasksControllerClaimTaskUrl(id: TasksControllerClaimTaskPathParams["id"]) {
  const res = { method: 'POST', url: `/api/tasks/${id}/claim` as const }
  return res
}

/**
 * {@link /api/tasks/:id/claim}
 */
export async function tasksControllerClaimTask(id: TasksControllerClaimTaskPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TasksControllerClaimTaskMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getTasksControllerClaimTaskUrl(id).url.toString(), ... requestConfig })
  return res.data
}