/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type { TasksControllerCompleteByActionMutationResponse } from "@/gen-quest/types/tasks-controller-complete-by-action";

function getTasksControllerCompleteByActionUrl() {
  const res = { method: "POST", url: `/api/tasks/complete-by-action` as const };
  return res;
}

/**
 * {@link /api/tasks/complete-by-action}
 */
export async function tasksControllerCompleteByAction(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    TasksControllerCompleteByActionMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getTasksControllerCompleteByActionUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
