/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  TasksControllerGetClaimStatusPathParams,
  TasksControllerGetClaimStatusQueryResponse,
} from "@/gen-quest/types/tasks-controller-get-claim-status";

function getTasksControllerGetClaimStatusUrl(id: TasksControllerGetClaimStatusPathParams["id"]) {
  const res = { method: "GET", url: `/api/tasks/${id}/claim/status` as const };
  return res;
}

/**
 * {@link /api/tasks/:id/claim/status}
 */
export async function tasksControllerGetClaimStatus(
  id: TasksControllerGetClaimStatusPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    TasksControllerGetClaimStatusQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getTasksControllerGetClaimStatusUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
