/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { UsersControllerSetEmailMutationRequest, UsersControllerSetEmailMutationResponse } from "@/gen-quest/types/users-controller-set-email";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getUsersControllerSetEmailUrl() {
  const res = { method: 'POST', url: `/api/quest/users/me/email` as const }
  return res
}

/**
 * {@link /api/quest/users/me/email}
 */
export async function usersControllerSetEmail(data: UsersControllerSetEmailMutationRequest, config: Partial<RequestConfig<UsersControllerSetEmailMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<UsersControllerSetEmailMutationResponse, ResponseErrorConfig<Error>, UsersControllerSetEmailMutationRequest>({ method : "POST", url : getUsersControllerSetEmailUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}