/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UsersControllerGetUserPathParams,
  UsersControllerGetUserQueryResponse,
} from "@/gen-quest/types/users-controller-get-user";

function getUsersControllerGetUserUrl(id: UsersControllerGetUserPathParams["id"]) {
  const res = { method: "GET", url: `/api/users/${id}` as const };
  return res;
}

/**
 * {@link /api/users/:id}
 */
export async function usersControllerGetUser(
  id: UsersControllerGetUserPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    UsersControllerGetUserQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getUsersControllerGetUserUrl(id).url.toString(), ...requestConfig });
  return res.data;
}
