/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { UsersControllerDailyLoginMutationResponse } from "@/gen-quest/types/users-controller-daily-login";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getUsersControllerDailyLoginUrl() {
  const res = { method: 'POST', url: `/api/quest/users/me/daily-login` as const }
  return res
}

/**
 * {@link /api/quest/users/me/daily-login}
 */
export async function usersControllerDailyLogin(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<UsersControllerDailyLoginMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getUsersControllerDailyLoginUrl().url.toString(), ... requestConfig })
  return res.data
}