/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  VolumeIntentControllerCreateIntentMutationRequest,
  VolumeIntentControllerCreateIntentMutationResponse,
} from "@/gen-quest/types/volume-intent-controller-create-intent";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getVolumeIntentControllerCreateIntentUrl() {
  const res = { method: "POST", url: `/api/volume/intent` as const };
  return res;
}

/**
 * @summary Register a volume intent
 * {@link /api/volume/intent}
 */
export async function volumeIntentControllerCreateIntent(
  data: VolumeIntentControllerCreateIntentMutationRequest,
  config: Partial<RequestConfig<VolumeIntentControllerCreateIntentMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    VolumeIntentControllerCreateIntentMutationResponse,
    ResponseErrorConfig<Error>,
    VolumeIntentControllerCreateIntentMutationRequest
  >({
    method: "POST",
    url: getVolumeIntentControllerCreateIntentUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
