/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerUsernameLogin } from "@/gen-quest/client/auth-controller-username-login";
import type {
  AuthControllerUsernameLoginMutationRequest,
  AuthControllerUsernameLoginMutationResponse,
} from "@/gen-quest/types/auth-controller-username-login";

export const authControllerUsernameLoginMutationKey = () => [{ url: "/api/auth/login" }] as const;

export type AuthControllerUsernameLoginMutationKey = ReturnType<
  typeof authControllerUsernameLoginMutationKey
>;

export function authControllerUsernameLoginMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AuthControllerUsernameLoginMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = authControllerUsernameLoginMutationKey();
  return mutationOptions<
    AuthControllerUsernameLoginMutationResponse,
    ResponseErrorConfig<Error>,
    { data: AuthControllerUsernameLoginMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return authControllerUsernameLogin(data, config);
    },
  });
}

/**
 * {@link /api/auth/login}
 */
export function useAuthControllerUsernameLogin<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AuthControllerUsernameLoginMutationResponse,
      ResponseErrorConfig<Error>,
      { data: AuthControllerUsernameLoginMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AuthControllerUsernameLoginMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authControllerUsernameLoginMutationKey();

  const baseOptions = authControllerUsernameLoginMutationOptions(config) as UseMutationOptions<
    AuthControllerUsernameLoginMutationResponse,
    ResponseErrorConfig<Error>,
    { data: AuthControllerUsernameLoginMutationRequest },
    TContext
  >;

  return useMutation<
    AuthControllerUsernameLoginMutationResponse,
    ResponseErrorConfig<Error>,
    { data: AuthControllerUsernameLoginMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AuthControllerUsernameLoginMutationResponse,
    ResponseErrorConfig<Error>,
    { data: AuthControllerUsernameLoginMutationRequest },
    TContext
  >;
}
