/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AnalyticsControllerActivityFeedQueryResponse } from "@/gen-quest/types/analytics-controller-activity-feed";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { analyticsControllerActivityFeed } from "@/gen-quest/client/analytics-controller-activity-feed";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const analyticsControllerActivityFeedSuspenseQueryKey = () => [{ url: '/api/quest/leaderboard/activity' }] as const

export type AnalyticsControllerActivityFeedSuspenseQueryKey = ReturnType<typeof analyticsControllerActivityFeedSuspenseQueryKey>

export function analyticsControllerActivityFeedSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = analyticsControllerActivityFeedSuspenseQueryKey()
        return queryOptions<AnalyticsControllerActivityFeedQueryResponse, ResponseErrorConfig<Error>, AnalyticsControllerActivityFeedQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return analyticsControllerActivityFeed({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/quest/leaderboard/activity}
 */
export function useAnalyticsControllerActivityFeedSuspense<TData = AnalyticsControllerActivityFeedQueryResponse, TQueryKey extends QueryKey = AnalyticsControllerActivityFeedSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AnalyticsControllerActivityFeedQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? analyticsControllerActivityFeedSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...analyticsControllerActivityFeedSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}