/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DebugLogControllerLogMutationResponse } from "@/gen-quest/types/debug-log-controller-log";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { debugLogControllerLog } from "@/gen-quest/client/debug-log-controller-log";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const debugLogControllerLogMutationKey = () => [{ url: '/api/internal/debug-log' }] as const

export type DebugLogControllerLogMutationKey = ReturnType<typeof debugLogControllerLogMutationKey>

export function debugLogControllerLogMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = debugLogControllerLogMutationKey()
        return mutationOptions<DebugLogControllerLogMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return debugLogControllerLog(config)
          },
        })

}

/**
 * {@link /api/internal/debug-log}
 */
export function useDebugLogControllerLog<TContext>(options: 
{
  mutation?: UseMutationOptions<DebugLogControllerLogMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? debugLogControllerLogMutationKey()

          const baseOptions = debugLogControllerLogMutationOptions(config) as UseMutationOptions<DebugLogControllerLogMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<DebugLogControllerLogMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DebugLogControllerLogMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}