/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SponsorAdminControllerGetStatsQueryResponse } from "@/gen-quest/types/sponsor-admin-controller-get-stats";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { sponsorAdminControllerGetStats } from "@/gen-quest/client/sponsor-admin-controller-get-stats";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const sponsorAdminControllerGetStatsSuspenseQueryKey = () => [{ url: '/api/admin/sponsor/stats' }] as const

export type SponsorAdminControllerGetStatsSuspenseQueryKey = ReturnType<typeof sponsorAdminControllerGetStatsSuspenseQueryKey>

export function sponsorAdminControllerGetStatsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = sponsorAdminControllerGetStatsSuspenseQueryKey()
        return queryOptions<SponsorAdminControllerGetStatsQueryResponse, ResponseErrorConfig<Error>, SponsorAdminControllerGetStatsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return sponsorAdminControllerGetStats({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get sponsor statistics (total sponsored TXs, fees, slot usage)
 * {@link /api/admin/sponsor/stats}
 */
export function useSponsorAdminControllerGetStatsSuspense<TData = SponsorAdminControllerGetStatsQueryResponse, TQueryKey extends QueryKey = SponsorAdminControllerGetStatsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<SponsorAdminControllerGetStatsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? sponsorAdminControllerGetStatsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...sponsorAdminControllerGetStatsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}