/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceControllerGetLeaderboardQueryResponse, MarketplaceControllerGetLeaderboardQueryParams } from "@/gen-quest/types/marketplace-controller-get-leaderboard";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { marketplaceControllerGetLeaderboard } from "@/gen-quest/client/marketplace-controller-get-leaderboard";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const marketplaceControllerGetLeaderboardQueryKey = (params: MarketplaceControllerGetLeaderboardQueryParams) => [{ url: '/api/marketplace/leaderboard' }, ...(params ? [params] : [])] as const

export type MarketplaceControllerGetLeaderboardQueryKey = ReturnType<typeof marketplaceControllerGetLeaderboardQueryKey>

export function marketplaceControllerGetLeaderboardQueryOptions(params: MarketplaceControllerGetLeaderboardQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceControllerGetLeaderboardQueryKey(params)
        return queryOptions<MarketplaceControllerGetLeaderboardQueryResponse, ResponseErrorConfig<Error>, MarketplaceControllerGetLeaderboardQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceControllerGetLeaderboard(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Strategy performance leaderboard
 * {@link /api/marketplace/leaderboard}
 */
export function useMarketplaceControllerGetLeaderboard<TData = MarketplaceControllerGetLeaderboardQueryResponse, TQueryData = MarketplaceControllerGetLeaderboardQueryResponse, TQueryKey extends QueryKey = MarketplaceControllerGetLeaderboardQueryKey>(params: MarketplaceControllerGetLeaderboardQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<MarketplaceControllerGetLeaderboardQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceControllerGetLeaderboardQueryKey(params)
         

         const query = useQuery({
          ...marketplaceControllerGetLeaderboardQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}