/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceControllerConfirmPublishMutationResponse } from "@/gen-quest/types/marketplace-controller-confirm-publish";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { marketplaceControllerConfirmPublish } from "@/gen-quest/client/marketplace-controller-confirm-publish";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const marketplaceControllerConfirmPublishMutationKey = () => [{ url: '/api/marketplace/strategies/build/confirm' }] as const

export type MarketplaceControllerConfirmPublishMutationKey = ReturnType<typeof marketplaceControllerConfirmPublishMutationKey>

export function marketplaceControllerConfirmPublishMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = marketplaceControllerConfirmPublishMutationKey()
        return mutationOptions<MarketplaceControllerConfirmPublishMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return marketplaceControllerConfirmPublish(config)
          },
        })

}

/**
 * @summary Confirm strategy publish after publisher signs TX
 * {@link /api/marketplace/strategies/build/confirm}
 */
export function useMarketplaceControllerConfirmPublish<TContext>(options: 
{
  mutation?: UseMutationOptions<MarketplaceControllerConfirmPublishMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? marketplaceControllerConfirmPublishMutationKey()

          const baseOptions = marketplaceControllerConfirmPublishMutationOptions(config) as UseMutationOptions<MarketplaceControllerConfirmPublishMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<MarketplaceControllerConfirmPublishMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarketplaceControllerConfirmPublishMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}