/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { marketplaceControllerListStrategies } from "@/gen-quest/client/marketplace-controller-list-strategies";
import type {
  MarketplaceControllerListStrategiesQueryParams,
  MarketplaceControllerListStrategiesQueryResponse,
} from "@/gen-quest/types/marketplace-controller-list-strategies";

export const marketplaceControllerListStrategiesQueryKey = (
  params: MarketplaceControllerListStrategiesQueryParams
) => [{ url: "/api/marketplace/strategies" }, ...(params ? [params] : [])] as const;

export type MarketplaceControllerListStrategiesQueryKey = ReturnType<
  typeof marketplaceControllerListStrategiesQueryKey
>;

export function marketplaceControllerListStrategiesQueryOptions(
  params: MarketplaceControllerListStrategiesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketplaceControllerListStrategiesQueryKey(params);
  return queryOptions<
    MarketplaceControllerListStrategiesQueryResponse,
    ResponseErrorConfig<Error>,
    MarketplaceControllerListStrategiesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketplaceControllerListStrategies(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List approved marketplace strategies
 * {@link /api/marketplace/strategies}
 */
export function useMarketplaceControllerListStrategies<
  TData = MarketplaceControllerListStrategiesQueryResponse,
  TQueryData = MarketplaceControllerListStrategiesQueryResponse,
  TQueryKey extends QueryKey = MarketplaceControllerListStrategiesQueryKey,
>(
  params: MarketplaceControllerListStrategiesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        MarketplaceControllerListStrategiesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? marketplaceControllerListStrategiesQueryKey(params);

  const query = useQuery(
    {
      ...marketplaceControllerListStrategiesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
