/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { adminControllerGetWaitlistEntryDispatches } from "@/gen-quest/client/admin-controller-get-waitlist-entry-dispatches";
import type {
  AdminControllerGetWaitlistEntryDispatchesPathParams,
  AdminControllerGetWaitlistEntryDispatchesQueryResponse,
} from "@/gen-quest/types/admin-controller-get-waitlist-entry-dispatches";

export const adminControllerGetWaitlistEntryDispatchesQueryKey = (
  id: AdminControllerGetWaitlistEntryDispatchesPathParams["id"] | undefined
) => [{ url: "/api/admin/waitlist/entries/:id/dispatches", params: { id: id } }] as const;

export type AdminControllerGetWaitlistEntryDispatchesQueryKey = ReturnType<
  typeof adminControllerGetWaitlistEntryDispatchesQueryKey
>;

export function adminControllerGetWaitlistEntryDispatchesQueryOptions(
  id: AdminControllerGetWaitlistEntryDispatchesPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = adminControllerGetWaitlistEntryDispatchesQueryKey(id);
  return queryOptions<
    AdminControllerGetWaitlistEntryDispatchesQueryResponse,
    ResponseErrorConfig<Error>,
    AdminControllerGetWaitlistEntryDispatchesQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return adminControllerGetWaitlistEntryDispatches(id!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get email dispatch history for a waitlist entry
 * {@link /api/admin/waitlist/entries/:id/dispatches}
 */
export function useAdminControllerGetWaitlistEntryDispatches<
  TData = AdminControllerGetWaitlistEntryDispatchesQueryResponse,
  TQueryData = AdminControllerGetWaitlistEntryDispatchesQueryResponse,
  TQueryKey extends QueryKey = AdminControllerGetWaitlistEntryDispatchesQueryKey,
>(
  id: AdminControllerGetWaitlistEntryDispatchesPathParams["id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        AdminControllerGetWaitlistEntryDispatchesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? adminControllerGetWaitlistEntryDispatchesQueryKey(id);

  const query = useQuery(
    {
      ...adminControllerGetWaitlistEntryDispatchesQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
