/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceControllerBuildClaimTxMutationResponse } from "@/gen-quest/types/marketplace-controller-build-claim-tx";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { marketplaceControllerBuildClaimTx } from "@/gen-quest/client/marketplace-controller-build-claim-tx";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const marketplaceControllerBuildClaimTxMutationKey = () => [{ url: '/api/marketplace/fees/claim/request' }] as const

export type MarketplaceControllerBuildClaimTxMutationKey = ReturnType<typeof marketplaceControllerBuildClaimTxMutationKey>

export function marketplaceControllerBuildClaimTxMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = marketplaceControllerBuildClaimTxMutationKey()
        return mutationOptions<MarketplaceControllerBuildClaimTxMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return marketplaceControllerBuildClaimTx(config)
          },
        })

}

/**
 * @summary Build unsigned claim XDR for publisher to sign
 * {@link /api/marketplace/fees/claim/request}
 */
export function useMarketplaceControllerBuildClaimTx<TContext>(options: 
{
  mutation?: UseMutationOptions<MarketplaceControllerBuildClaimTxMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? marketplaceControllerBuildClaimTxMutationKey()

          const baseOptions = marketplaceControllerBuildClaimTxMutationOptions(config) as UseMutationOptions<MarketplaceControllerBuildClaimTxMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<MarketplaceControllerBuildClaimTxMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarketplaceControllerBuildClaimTxMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}