/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerListReferralConfigQueryResponse } from "@/gen-quest/types/admin-controller-list-referral-config";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminControllerListReferralConfig } from "@/gen-quest/client/admin-controller-list-referral-config";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminControllerListReferralConfigSuspenseQueryKey = () => [{ url: '/api/quest/admin/referral/config' }] as const

export type AdminControllerListReferralConfigSuspenseQueryKey = ReturnType<typeof adminControllerListReferralConfigSuspenseQueryKey>

export function adminControllerListReferralConfigSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerListReferralConfigSuspenseQueryKey()
        return queryOptions<AdminControllerListReferralConfigQueryResponse, ResponseErrorConfig<Error>, AdminControllerListReferralConfigQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerListReferralConfig({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/quest/admin/referral/config}
 */
export function useAdminControllerListReferralConfigSuspense<TData = AdminControllerListReferralConfigQueryResponse, TQueryKey extends QueryKey = AdminControllerListReferralConfigSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminControllerListReferralConfigQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerListReferralConfigSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...adminControllerListReferralConfigSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}