/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceControllerListPendingStrategiesQueryResponse } from "@/gen-quest/types/marketplace-controller-list-pending-strategies";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { marketplaceControllerListPendingStrategies } from "@/gen-quest/client/marketplace-controller-list-pending-strategies";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const marketplaceControllerListPendingStrategiesQueryKey = () => [{ url: '/api/marketplace/admin/pending' }] as const

export type MarketplaceControllerListPendingStrategiesQueryKey = ReturnType<typeof marketplaceControllerListPendingStrategiesQueryKey>

export function marketplaceControllerListPendingStrategiesQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceControllerListPendingStrategiesQueryKey()
        return queryOptions<MarketplaceControllerListPendingStrategiesQueryResponse, ResponseErrorConfig<Error>, MarketplaceControllerListPendingStrategiesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceControllerListPendingStrategies({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Admin: list strategies awaiting approval
 * {@link /api/marketplace/admin/pending}
 */
export function useMarketplaceControllerListPendingStrategies<TData = MarketplaceControllerListPendingStrategiesQueryResponse, TQueryData = MarketplaceControllerListPendingStrategiesQueryResponse, TQueryKey extends QueryKey = MarketplaceControllerListPendingStrategiesQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<MarketplaceControllerListPendingStrategiesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceControllerListPendingStrategiesQueryKey()
         

         const query = useQuery({
          ...marketplaceControllerListPendingStrategiesQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}