/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CampaignsControllerGetClaimsQueryResponse, CampaignsControllerGetClaimsPathParams } from "@/gen-quest/types/campaigns-controller-get-claims";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { campaignsControllerGetClaims } from "@/gen-quest/client/campaigns-controller-get-claims";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const campaignsControllerGetClaimsQueryKey = (id: CampaignsControllerGetClaimsPathParams["id"] | undefined) => [{ url: '/api/campaigns/:id/claims', params: {id:id} }] as const

export type CampaignsControllerGetClaimsQueryKey = ReturnType<typeof campaignsControllerGetClaimsQueryKey>

export function campaignsControllerGetClaimsQueryOptions(id: CampaignsControllerGetClaimsPathParams["id"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = campaignsControllerGetClaimsQueryKey(id)
        return queryOptions<CampaignsControllerGetClaimsQueryResponse, ResponseErrorConfig<Error>, CampaignsControllerGetClaimsQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return campaignsControllerGetClaims(id!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/campaigns/:id/claims}
 */
export function useCampaignsControllerGetClaims<TData = CampaignsControllerGetClaimsQueryResponse, TQueryData = CampaignsControllerGetClaimsQueryResponse, TQueryKey extends QueryKey = CampaignsControllerGetClaimsQueryKey>(id: CampaignsControllerGetClaimsPathParams["id"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<CampaignsControllerGetClaimsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? campaignsControllerGetClaimsQueryKey(id)
         

         const query = useQuery({
          ...campaignsControllerGetClaimsQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}