/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReferralControllerGetTreeQueryResponse } from "@/gen-quest/types/referral-controller-get-tree";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { referralControllerGetTree } from "@/gen-quest/client/referral-controller-get-tree";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const referralControllerGetTreeQueryKey = () => [{ url: '/api/quest/referral/tree' }] as const

export type ReferralControllerGetTreeQueryKey = ReturnType<typeof referralControllerGetTreeQueryKey>

export function referralControllerGetTreeQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = referralControllerGetTreeQueryKey()
        return queryOptions<ReferralControllerGetTreeQueryResponse, ResponseErrorConfig<Error>, ReferralControllerGetTreeQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return referralControllerGetTree({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/quest/referral/tree}
 */
export function useReferralControllerGetTree<TData = ReferralControllerGetTreeQueryResponse, TQueryData = ReferralControllerGetTreeQueryResponse, TQueryKey extends QueryKey = ReferralControllerGetTreeQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ReferralControllerGetTreeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? referralControllerGetTreeQueryKey()
         

         const query = useQuery({
          ...referralControllerGetTreeQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}