/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { waitlistControllerRequestChallenge } from "@/gen-quest/client/waitlist-controller-request-challenge";
import type {
  WaitlistControllerRequestChallengeMutationRequest,
  WaitlistControllerRequestChallengeMutationResponse,
} from "@/gen-quest/types/waitlist-controller-request-challenge";

export const waitlistControllerRequestChallengeMutationKey = () =>
  [{ url: "/api/waitlist/challenge" }] as const;

export type WaitlistControllerRequestChallengeMutationKey = ReturnType<
  typeof waitlistControllerRequestChallengeMutationKey
>;

export function waitlistControllerRequestChallengeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<WaitlistControllerRequestChallengeMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = waitlistControllerRequestChallengeMutationKey();
  return mutationOptions<
    WaitlistControllerRequestChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WaitlistControllerRequestChallengeMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return waitlistControllerRequestChallenge(data, config);
    },
  });
}

/**
 * @summary Request wallet ownership challenge
 * {@link /api/waitlist/challenge}
 */
export function useWaitlistControllerRequestChallenge<TContext>(
  options: {
    mutation?: UseMutationOptions<
      WaitlistControllerRequestChallengeMutationResponse,
      ResponseErrorConfig<Error>,
      { data: WaitlistControllerRequestChallengeMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<WaitlistControllerRequestChallengeMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? waitlistControllerRequestChallengeMutationKey();

  const baseOptions = waitlistControllerRequestChallengeMutationOptions(
    config
  ) as UseMutationOptions<
    WaitlistControllerRequestChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WaitlistControllerRequestChallengeMutationRequest },
    TContext
  >;

  return useMutation<
    WaitlistControllerRequestChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WaitlistControllerRequestChallengeMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    WaitlistControllerRequestChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WaitlistControllerRequestChallengeMutationRequest },
    TContext
  >;
}
