/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { fomoAdminControllerList } from "@/gen-quest/client/fomo-admin-controller-list";
import type { FomoAdminControllerListQueryResponse } from "@/gen-quest/types/fomo-admin-controller-list";

export const fomoAdminControllerListSuspenseQueryKey = () =>
  [{ url: "/api/quest/admin/fomo" }] as const;

export type FomoAdminControllerListSuspenseQueryKey = ReturnType<
  typeof fomoAdminControllerListSuspenseQueryKey
>;

export function fomoAdminControllerListSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = fomoAdminControllerListSuspenseQueryKey();
  return queryOptions<
    FomoAdminControllerListQueryResponse,
    ResponseErrorConfig<Error>,
    FomoAdminControllerListQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return fomoAdminControllerList({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * {@link /api/quest/admin/fomo}
 */
export function useFomoAdminControllerListSuspense<
  TData = FomoAdminControllerListQueryResponse,
  TQueryKey extends QueryKey = FomoAdminControllerListSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        FomoAdminControllerListQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? fomoAdminControllerListSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...fomoAdminControllerListSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
