/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { adminControllerGetQuestStats } from "@/gen-quest/client/admin-controller-get-quest-stats";
import type { AdminControllerGetQuestStatsQueryResponse } from "@/gen-quest/types/admin-controller-get-quest-stats";

export const adminControllerGetQuestStatsQueryKey = () =>
  [{ url: "/api/admin/quest-stats" }] as const;

export type AdminControllerGetQuestStatsQueryKey = ReturnType<
  typeof adminControllerGetQuestStatsQueryKey
>;

export function adminControllerGetQuestStatsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = adminControllerGetQuestStatsQueryKey();
  return queryOptions<
    AdminControllerGetQuestStatsQueryResponse,
    ResponseErrorConfig<Error>,
    AdminControllerGetQuestStatsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return adminControllerGetQuestStats({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get quest statistics
 * {@link /api/admin/quest-stats}
 */
export function useAdminControllerGetQuestStats<
  TData = AdminControllerGetQuestStatsQueryResponse,
  TQueryData = AdminControllerGetQuestStatsQueryResponse,
  TQueryKey extends QueryKey = AdminControllerGetQuestStatsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        AdminControllerGetQuestStatsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? adminControllerGetQuestStatsQueryKey();

  const query = useQuery(
    {
      ...adminControllerGetQuestStatsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
