/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminSeasonsControllerSetRankRewardsMutationRequest, AdminSeasonsControllerSetRankRewardsMutationResponse, AdminSeasonsControllerSetRankRewardsPathParams } from "@/gen-quest/types/admin-seasons-controller-set-rank-rewards";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminSeasonsControllerSetRankRewards } from "@/gen-quest/client/admin-seasons-controller-set-rank-rewards";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminSeasonsControllerSetRankRewardsMutationKey = () => [{ url: '/api/quest/admin/seasons/:id/rank-rewards' }] as const

export type AdminSeasonsControllerSetRankRewardsMutationKey = ReturnType<typeof adminSeasonsControllerSetRankRewardsMutationKey>

export function adminSeasonsControllerSetRankRewardsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminSeasonsControllerSetRankRewardsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminSeasonsControllerSetRankRewardsMutationKey()
        return mutationOptions<AdminSeasonsControllerSetRankRewardsMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerSetRankRewardsPathParams["id"], data: AdminSeasonsControllerSetRankRewardsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return adminSeasonsControllerSetRankRewards(id, data, config)
          },
        })

}

/**
 * {@link /api/quest/admin/seasons/:id/rank-rewards}
 */
export function useAdminSeasonsControllerSetRankRewards<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminSeasonsControllerSetRankRewardsMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerSetRankRewardsPathParams["id"], data: AdminSeasonsControllerSetRankRewardsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminSeasonsControllerSetRankRewardsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminSeasonsControllerSetRankRewardsMutationKey()

          const baseOptions = adminSeasonsControllerSetRankRewardsMutationOptions(config) as UseMutationOptions<AdminSeasonsControllerSetRankRewardsMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerSetRankRewardsPathParams["id"], data: AdminSeasonsControllerSetRankRewardsMutationRequest}, TContext>
          

          return useMutation<AdminSeasonsControllerSetRankRewardsMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerSetRankRewardsPathParams["id"], data: AdminSeasonsControllerSetRankRewardsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminSeasonsControllerSetRankRewardsMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerSetRankRewardsPathParams["id"], data: AdminSeasonsControllerSetRankRewardsMutationRequest}, TContext>
      
}