/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SponsorAdminControllerGetConfigQueryResponse } from "@/gen-quest/types/sponsor-admin-controller-get-config";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { sponsorAdminControllerGetConfig } from "@/gen-quest/client/sponsor-admin-controller-get-config";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const sponsorAdminControllerGetConfigQueryKey = () => [{ url: '/api/admin/sponsor/config' }] as const

export type SponsorAdminControllerGetConfigQueryKey = ReturnType<typeof sponsorAdminControllerGetConfigQueryKey>

export function sponsorAdminControllerGetConfigQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = sponsorAdminControllerGetConfigQueryKey()
        return queryOptions<SponsorAdminControllerGetConfigQueryResponse, ResponseErrorConfig<Error>, SponsorAdminControllerGetConfigQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return sponsorAdminControllerGetConfig({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get current sponsor config and used slot count
 * {@link /api/admin/sponsor/config}
 */
export function useSponsorAdminControllerGetConfig<TData = SponsorAdminControllerGetConfigQueryResponse, TQueryData = SponsorAdminControllerGetConfigQueryResponse, TQueryKey extends QueryKey = SponsorAdminControllerGetConfigQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<SponsorAdminControllerGetConfigQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? sponsorAdminControllerGetConfigQueryKey()
         

         const query = useQuery({
          ...sponsorAdminControllerGetConfigQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}