/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FomoAdminControllerUpdateMutationRequest, FomoAdminControllerUpdateMutationResponse, FomoAdminControllerUpdatePathParams } from "@/gen-quest/types/fomo-admin-controller-update";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { fomoAdminControllerUpdate } from "@/gen-quest/client/fomo-admin-controller-update";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const fomoAdminControllerUpdateMutationKey = () => [{ url: '/api/quest/admin/fomo/:id' }] as const

export type FomoAdminControllerUpdateMutationKey = ReturnType<typeof fomoAdminControllerUpdateMutationKey>

export function fomoAdminControllerUpdateMutationOptions<TContext = unknown>(config: Partial<RequestConfig<FomoAdminControllerUpdateMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = fomoAdminControllerUpdateMutationKey()
        return mutationOptions<FomoAdminControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: FomoAdminControllerUpdatePathParams["id"], data: FomoAdminControllerUpdateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return fomoAdminControllerUpdate(id, data, config)
          },
        })

}

/**
 * {@link /api/quest/admin/fomo/:id}
 */
export function useFomoAdminControllerUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<FomoAdminControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: FomoAdminControllerUpdatePathParams["id"], data: FomoAdminControllerUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<FomoAdminControllerUpdateMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? fomoAdminControllerUpdateMutationKey()

          const baseOptions = fomoAdminControllerUpdateMutationOptions(config) as UseMutationOptions<FomoAdminControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: FomoAdminControllerUpdatePathParams["id"], data: FomoAdminControllerUpdateMutationRequest}, TContext>
          

          return useMutation<FomoAdminControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: FomoAdminControllerUpdatePathParams["id"], data: FomoAdminControllerUpdateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<FomoAdminControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: FomoAdminControllerUpdatePathParams["id"], data: FomoAdminControllerUpdateMutationRequest}, TContext>
      
}