/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TierRewardsControllerClaimMutationResponse, TierRewardsControllerClaimPathParams } from "@/gen-quest/types/tier-rewards-controller-claim";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { tierRewardsControllerClaim } from "@/gen-quest/client/tier-rewards-controller-claim";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const tierRewardsControllerClaimMutationKey = () => [{ url: '/api/quest/users/me/tier-rewards/:tier/claim' }] as const

export type TierRewardsControllerClaimMutationKey = ReturnType<typeof tierRewardsControllerClaimMutationKey>

export function tierRewardsControllerClaimMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = tierRewardsControllerClaimMutationKey()
        return mutationOptions<TierRewardsControllerClaimMutationResponse, ResponseErrorConfig<Error>, {tier: TierRewardsControllerClaimPathParams["tier"]}, TContext>({
          mutationKey,
          mutationFn: async({ tier }) => {
            return tierRewardsControllerClaim(tier, config)
          },
        })

}

/**
 * {@link /api/quest/users/me/tier-rewards/:tier/claim}
 */
export function useTierRewardsControllerClaim<TContext>(options: 
{
  mutation?: UseMutationOptions<TierRewardsControllerClaimMutationResponse, ResponseErrorConfig<Error>, {tier: TierRewardsControllerClaimPathParams["tier"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? tierRewardsControllerClaimMutationKey()

          const baseOptions = tierRewardsControllerClaimMutationOptions(config) as UseMutationOptions<TierRewardsControllerClaimMutationResponse, ResponseErrorConfig<Error>, {tier: TierRewardsControllerClaimPathParams["tier"]}, TContext>
          

          return useMutation<TierRewardsControllerClaimMutationResponse, ResponseErrorConfig<Error>, {tier: TierRewardsControllerClaimPathParams["tier"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<TierRewardsControllerClaimMutationResponse, ResponseErrorConfig<Error>, {tier: TierRewardsControllerClaimPathParams["tier"]}, TContext>
      
}