/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { adminControllerRemoveTask } from "@/gen-quest/client/admin-controller-remove-task";
import type {
  AdminControllerRemoveTaskMutationResponse,
  AdminControllerRemoveTaskPathParams,
} from "@/gen-quest/types/admin-controller-remove-task";

export const adminControllerRemoveTaskMutationKey = () =>
  [{ url: "/api/admin/tasks/:taskId" }] as const;

export type AdminControllerRemoveTaskMutationKey = ReturnType<
  typeof adminControllerRemoveTaskMutationKey
>;

export function adminControllerRemoveTaskMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = adminControllerRemoveTaskMutationKey();
  return mutationOptions<
    AdminControllerRemoveTaskMutationResponse,
    ResponseErrorConfig<Error>,
    { taskId: AdminControllerRemoveTaskPathParams["taskId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ taskId }) => {
      return adminControllerRemoveTask(taskId, config);
    },
  });
}

/**
 * {@link /api/admin/tasks/:taskId}
 */
export function useAdminControllerRemoveTask<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AdminControllerRemoveTaskMutationResponse,
      ResponseErrorConfig<Error>,
      { taskId: AdminControllerRemoveTaskPathParams["taskId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? adminControllerRemoveTaskMutationKey();

  const baseOptions = adminControllerRemoveTaskMutationOptions(config) as UseMutationOptions<
    AdminControllerRemoveTaskMutationResponse,
    ResponseErrorConfig<Error>,
    { taskId: AdminControllerRemoveTaskPathParams["taskId"] },
    TContext
  >;

  return useMutation<
    AdminControllerRemoveTaskMutationResponse,
    ResponseErrorConfig<Error>,
    { taskId: AdminControllerRemoveTaskPathParams["taskId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AdminControllerRemoveTaskMutationResponse,
    ResponseErrorConfig<Error>,
    { taskId: AdminControllerRemoveTaskPathParams["taskId"] },
    TContext
  >;
}
