/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { socialAccountsControllerUnlinkAccount } from "@/gen-quest/client/social-accounts-controller-unlink-account";
import type {
  SocialAccountsControllerUnlinkAccount404,
  SocialAccountsControllerUnlinkAccountMutationResponse,
  SocialAccountsControllerUnlinkAccountPathParams,
} from "@/gen-quest/types/social-accounts-controller-unlink-account";

export const socialAccountsControllerUnlinkAccountMutationKey = () =>
  [{ url: "/api/quest/users/me/social-accounts/:platform" }] as const;

export type SocialAccountsControllerUnlinkAccountMutationKey = ReturnType<
  typeof socialAccountsControllerUnlinkAccountMutationKey
>;

export function socialAccountsControllerUnlinkAccountMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = socialAccountsControllerUnlinkAccountMutationKey();
  return mutationOptions<
    SocialAccountsControllerUnlinkAccountMutationResponse,
    ResponseErrorConfig<SocialAccountsControllerUnlinkAccount404>,
    { platform: SocialAccountsControllerUnlinkAccountPathParams["platform"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ platform }) => {
      return socialAccountsControllerUnlinkAccount(platform, config);
    },
  });
}

/**
 * @summary Unlink a social account
 * {@link /api/quest/users/me/social-accounts/:platform}
 */
export function useSocialAccountsControllerUnlinkAccount<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SocialAccountsControllerUnlinkAccountMutationResponse,
      ResponseErrorConfig<SocialAccountsControllerUnlinkAccount404>,
      { platform: SocialAccountsControllerUnlinkAccountPathParams["platform"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? socialAccountsControllerUnlinkAccountMutationKey();

  const baseOptions = socialAccountsControllerUnlinkAccountMutationOptions(
    config
  ) as UseMutationOptions<
    SocialAccountsControllerUnlinkAccountMutationResponse,
    ResponseErrorConfig<SocialAccountsControllerUnlinkAccount404>,
    { platform: SocialAccountsControllerUnlinkAccountPathParams["platform"] },
    TContext
  >;

  return useMutation<
    SocialAccountsControllerUnlinkAccountMutationResponse,
    ResponseErrorConfig<SocialAccountsControllerUnlinkAccount404>,
    { platform: SocialAccountsControllerUnlinkAccountPathParams["platform"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    SocialAccountsControllerUnlinkAccountMutationResponse,
    ResponseErrorConfig<SocialAccountsControllerUnlinkAccount404>,
    { platform: SocialAccountsControllerUnlinkAccountPathParams["platform"] },
    TContext
  >;
}
