/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceControllerGetStrategyQueryResponse, MarketplaceControllerGetStrategyPathParams } from "@/gen-quest/types/marketplace-controller-get-strategy";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { marketplaceControllerGetStrategy } from "@/gen-quest/client/marketplace-controller-get-strategy";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const marketplaceControllerGetStrategySuspenseQueryKey = (id: MarketplaceControllerGetStrategyPathParams["id"] | undefined) => [{ url: '/api/marketplace/strategies/:id', params: {id:id} }] as const

export type MarketplaceControllerGetStrategySuspenseQueryKey = ReturnType<typeof marketplaceControllerGetStrategySuspenseQueryKey>

export function marketplaceControllerGetStrategySuspenseQueryOptions(id: MarketplaceControllerGetStrategyPathParams["id"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceControllerGetStrategySuspenseQueryKey(id)
        return queryOptions<MarketplaceControllerGetStrategyQueryResponse, ResponseErrorConfig<Error>, MarketplaceControllerGetStrategyQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceControllerGetStrategy(id!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get strategy detail
 * {@link /api/marketplace/strategies/:id}
 */
export function useMarketplaceControllerGetStrategySuspense<TData = MarketplaceControllerGetStrategyQueryResponse, TQueryKey extends QueryKey = MarketplaceControllerGetStrategySuspenseQueryKey>(id: MarketplaceControllerGetStrategyPathParams["id"] | undefined, options: 
{
  query?: Partial<UseSuspenseQueryOptions<MarketplaceControllerGetStrategyQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceControllerGetStrategySuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...marketplaceControllerGetStrategySuspenseQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}