/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SponsorAdminControllerResetSponsorSlotsMutationResponse } from "@/gen-quest/types/sponsor-admin-controller-reset-sponsor-slots";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { sponsorAdminControllerResetSponsorSlots } from "@/gen-quest/client/sponsor-admin-controller-reset-sponsor-slots";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const sponsorAdminControllerResetSponsorSlotsMutationKey = () => [{ url: '/api/admin/sponsor/reset-slots' }] as const

export type SponsorAdminControllerResetSponsorSlotsMutationKey = ReturnType<typeof sponsorAdminControllerResetSponsorSlotsMutationKey>

export function sponsorAdminControllerResetSponsorSlotsMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = sponsorAdminControllerResetSponsorSlotsMutationKey()
        return mutationOptions<SponsorAdminControllerResetSponsorSlotsMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return sponsorAdminControllerResetSponsorSlots(config)
          },
        })

}

/**
 * @summary Reset Redis slot counter to 0 for active sponsor config
 * {@link /api/admin/sponsor/reset-slots}
 */
export function useSponsorAdminControllerResetSponsorSlots<TContext>(options: 
{
  mutation?: UseMutationOptions<SponsorAdminControllerResetSponsorSlotsMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? sponsorAdminControllerResetSponsorSlotsMutationKey()

          const baseOptions = sponsorAdminControllerResetSponsorSlotsMutationOptions(config) as UseMutationOptions<SponsorAdminControllerResetSponsorSlotsMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<SponsorAdminControllerResetSponsorSlotsMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<SponsorAdminControllerResetSponsorSlotsMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}