/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsersControllerGetCheckInStatusQueryResponse } from "@/gen-quest/types/users-controller-get-check-in-status";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { usersControllerGetCheckInStatus } from "@/gen-quest/client/users-controller-get-check-in-status";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const usersControllerGetCheckInStatusQueryKey = () => [{ url: '/api/quest/users/me/check-in-status' }] as const

export type UsersControllerGetCheckInStatusQueryKey = ReturnType<typeof usersControllerGetCheckInStatusQueryKey>

export function usersControllerGetCheckInStatusQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = usersControllerGetCheckInStatusQueryKey()
        return queryOptions<UsersControllerGetCheckInStatusQueryResponse, ResponseErrorConfig<Error>, UsersControllerGetCheckInStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return usersControllerGetCheckInStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/quest/users/me/check-in-status}
 */
export function useUsersControllerGetCheckInStatus<TData = UsersControllerGetCheckInStatusQueryResponse, TQueryData = UsersControllerGetCheckInStatusQueryResponse, TQueryKey extends QueryKey = UsersControllerGetCheckInStatusQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<UsersControllerGetCheckInStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? usersControllerGetCheckInStatusQueryKey()
         

         const query = useQuery({
          ...usersControllerGetCheckInStatusQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}