/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { seasonsControllerRevealAck } from "@/gen-quest/client/seasons-controller-reveal-ack";
import type { SeasonsControllerRevealAckMutationResponse } from "@/gen-quest/types/seasons-controller-reveal-ack";

export const seasonsControllerRevealAckMutationKey = () =>
  [{ url: "/api/quest/seasons/me/reveal-ack" }] as const;

export type SeasonsControllerRevealAckMutationKey = ReturnType<
  typeof seasonsControllerRevealAckMutationKey
>;

export function seasonsControllerRevealAckMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = seasonsControllerRevealAckMutationKey();
  return mutationOptions<
    SeasonsControllerRevealAckMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return seasonsControllerRevealAck(config);
    },
  });
}

/**
 * {@link /api/quest/seasons/me/reveal-ack}
 */
export function useSeasonsControllerRevealAck<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SeasonsControllerRevealAckMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? seasonsControllerRevealAckMutationKey();

  const baseOptions = seasonsControllerRevealAckMutationOptions(config) as UseMutationOptions<
    SeasonsControllerRevealAckMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;

  return useMutation<
    SeasonsControllerRevealAckMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    SeasonsControllerRevealAckMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;
}
