/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { welcomeRewardControllerScanVolume } from "@/gen-quest/client/welcome-reward-controller-scan-volume";
import type { WelcomeRewardControllerScanVolumeMutationResponse } from "@/gen-quest/types/welcome-reward-controller-scan-volume";

export const welcomeRewardControllerScanVolumeMutationKey = () =>
  [{ url: "/api/welcome-reward/scan" }] as const;

export type WelcomeRewardControllerScanVolumeMutationKey = ReturnType<
  typeof welcomeRewardControllerScanVolumeMutationKey
>;

export function welcomeRewardControllerScanVolumeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = welcomeRewardControllerScanVolumeMutationKey();
  return mutationOptions<
    WelcomeRewardControllerScanVolumeMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return welcomeRewardControllerScanVolume(config);
    },
  });
}

/**
 * @summary Scan all Horizon transactions for volume memos and sync volume
 * {@link /api/welcome-reward/scan}
 */
export function useWelcomeRewardControllerScanVolume<TContext>(
  options: {
    mutation?: UseMutationOptions<
      WelcomeRewardControllerScanVolumeMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? welcomeRewardControllerScanVolumeMutationKey();

  const baseOptions = welcomeRewardControllerScanVolumeMutationOptions(
    config
  ) as UseMutationOptions<
    WelcomeRewardControllerScanVolumeMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;

  return useMutation<
    WelcomeRewardControllerScanVolumeMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    WelcomeRewardControllerScanVolumeMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;
}
