/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { campaignsControllerGetNotJoinedCampaigns } from "@/gen-quest/client/campaigns-controller-get-not-joined-campaigns";
import type {
  CampaignsControllerGetNotJoinedCampaignsQueryParams,
  CampaignsControllerGetNotJoinedCampaignsQueryResponse,
} from "@/gen-quest/types/campaigns-controller-get-not-joined-campaigns";

export const campaignsControllerGetNotJoinedCampaignsSuspenseQueryKey = (
  params?: CampaignsControllerGetNotJoinedCampaignsQueryParams
) => [{ url: "/api/quest/campaigns/not-joined" }, ...(params ? [params] : [])] as const;

export type CampaignsControllerGetNotJoinedCampaignsSuspenseQueryKey = ReturnType<
  typeof campaignsControllerGetNotJoinedCampaignsSuspenseQueryKey
>;

export function campaignsControllerGetNotJoinedCampaignsSuspenseQueryOptions(
  params?: CampaignsControllerGetNotJoinedCampaignsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = campaignsControllerGetNotJoinedCampaignsSuspenseQueryKey(params);
  return queryOptions<
    CampaignsControllerGetNotJoinedCampaignsQueryResponse,
    ResponseErrorConfig<Error>,
    CampaignsControllerGetNotJoinedCampaignsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return campaignsControllerGetNotJoinedCampaigns(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/quest/campaigns/not-joined}
 */
export function useCampaignsControllerGetNotJoinedCampaignsSuspense<
  TData = CampaignsControllerGetNotJoinedCampaignsQueryResponse,
  TQueryKey extends QueryKey = CampaignsControllerGetNotJoinedCampaignsSuspenseQueryKey,
>(
  params?: CampaignsControllerGetNotJoinedCampaignsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        CampaignsControllerGetNotJoinedCampaignsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? campaignsControllerGetNotJoinedCampaignsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...campaignsControllerGetNotJoinedCampaignsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
