/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { analyticsControllerPrizePool } from "@/gen-quest/client/analytics-controller-prize-pool";
import type { AnalyticsControllerPrizePoolQueryResponse } from "@/gen-quest/types/analytics-controller-prize-pool";

export const analyticsControllerPrizePoolSuspenseQueryKey = () =>
  [{ url: "/api/quest/leaderboard/prize-pool" }] as const;

export type AnalyticsControllerPrizePoolSuspenseQueryKey = ReturnType<
  typeof analyticsControllerPrizePoolSuspenseQueryKey
>;

export function analyticsControllerPrizePoolSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = analyticsControllerPrizePoolSuspenseQueryKey();
  return queryOptions<
    AnalyticsControllerPrizePoolQueryResponse,
    ResponseErrorConfig<Error>,
    AnalyticsControllerPrizePoolQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return analyticsControllerPrizePool({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * {@link /api/quest/leaderboard/prize-pool}
 */
export function useAnalyticsControllerPrizePoolSuspense<
  TData = AnalyticsControllerPrizePoolQueryResponse,
  TQueryKey extends QueryKey = AnalyticsControllerPrizePoolSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        AnalyticsControllerPrizePoolQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? analyticsControllerPrizePoolSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...analyticsControllerPrizePoolSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
