/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminSeasonsControllerEndMutationResponse, AdminSeasonsControllerEndPathParams } from "@/gen-quest/types/admin-seasons-controller-end";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminSeasonsControllerEnd } from "@/gen-quest/client/admin-seasons-controller-end";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminSeasonsControllerEndMutationKey = () => [{ url: '/api/admin/quest-seasons/:id/end' }] as const

export type AdminSeasonsControllerEndMutationKey = ReturnType<typeof adminSeasonsControllerEndMutationKey>

export function adminSeasonsControllerEndMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = adminSeasonsControllerEndMutationKey()
        return mutationOptions<AdminSeasonsControllerEndMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerEndPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return adminSeasonsControllerEnd(id, config)
          },
        })

}

/**
 * {@link /api/admin/quest-seasons/:id/end}
 */
export function useAdminSeasonsControllerEnd<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminSeasonsControllerEndMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerEndPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminSeasonsControllerEndMutationKey()

          const baseOptions = adminSeasonsControllerEndMutationOptions(config) as UseMutationOptions<AdminSeasonsControllerEndMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerEndPathParams["id"]}, TContext>
          

          return useMutation<AdminSeasonsControllerEndMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerEndPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminSeasonsControllerEndMutationResponse, ResponseErrorConfig<Error>, {id: AdminSeasonsControllerEndPathParams["id"]}, TContext>
      
}