/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { tierRewardsAdminControllerSetRewards } from "@/gen-quest/client/tier-rewards-admin-controller-set-rewards";
import type {
  TierRewardsAdminControllerSetRewardsMutationRequest,
  TierRewardsAdminControllerSetRewardsMutationResponse,
} from "@/gen-quest/types/tier-rewards-admin-controller-set-rewards";

export const tierRewardsAdminControllerSetRewardsMutationKey = () =>
  [{ url: "/api/quest/admin/tier-rewards" }] as const;

export type TierRewardsAdminControllerSetRewardsMutationKey = ReturnType<
  typeof tierRewardsAdminControllerSetRewardsMutationKey
>;

export function tierRewardsAdminControllerSetRewardsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<TierRewardsAdminControllerSetRewardsMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = tierRewardsAdminControllerSetRewardsMutationKey();
  return mutationOptions<
    TierRewardsAdminControllerSetRewardsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: TierRewardsAdminControllerSetRewardsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return tierRewardsAdminControllerSetRewards(data, config);
    },
  });
}

/**
 * {@link /api/quest/admin/tier-rewards}
 */
export function useTierRewardsAdminControllerSetRewards<TContext>(
  options: {
    mutation?: UseMutationOptions<
      TierRewardsAdminControllerSetRewardsMutationResponse,
      ResponseErrorConfig<Error>,
      { data: TierRewardsAdminControllerSetRewardsMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<TierRewardsAdminControllerSetRewardsMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? tierRewardsAdminControllerSetRewardsMutationKey();

  const baseOptions = tierRewardsAdminControllerSetRewardsMutationOptions(
    config
  ) as UseMutationOptions<
    TierRewardsAdminControllerSetRewardsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: TierRewardsAdminControllerSetRewardsMutationRequest },
    TContext
  >;

  return useMutation<
    TierRewardsAdminControllerSetRewardsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: TierRewardsAdminControllerSetRewardsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    TierRewardsAdminControllerSetRewardsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: TierRewardsAdminControllerSetRewardsMutationRequest },
    TContext
  >;
}
