/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { marketplaceControllerConfirmActivate } from "@/gen-quest/client/marketplace-controller-confirm-activate";
import type {
  MarketplaceControllerConfirmActivateMutationResponse,
  MarketplaceControllerConfirmActivatePathParams,
} from "@/gen-quest/types/marketplace-controller-confirm-activate";

export const marketplaceControllerConfirmActivateMutationKey = () =>
  [{ url: "/api/marketplace/strategies/:id/activate/confirm" }] as const;

export type MarketplaceControllerConfirmActivateMutationKey = ReturnType<
  typeof marketplaceControllerConfirmActivateMutationKey
>;

export function marketplaceControllerConfirmActivateMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = marketplaceControllerConfirmActivateMutationKey();
  return mutationOptions<
    MarketplaceControllerConfirmActivateMutationResponse,
    ResponseErrorConfig<Error>,
    { id: MarketplaceControllerConfirmActivatePathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return marketplaceControllerConfirmActivate(id, config);
    },
  });
}

/**
 * @summary Confirm activation after user signs TX
 * {@link /api/marketplace/strategies/:id/activate/confirm}
 */
export function useMarketplaceControllerConfirmActivate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      MarketplaceControllerConfirmActivateMutationResponse,
      ResponseErrorConfig<Error>,
      { id: MarketplaceControllerConfirmActivatePathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? marketplaceControllerConfirmActivateMutationKey();

  const baseOptions = marketplaceControllerConfirmActivateMutationOptions(
    config
  ) as UseMutationOptions<
    MarketplaceControllerConfirmActivateMutationResponse,
    ResponseErrorConfig<Error>,
    { id: MarketplaceControllerConfirmActivatePathParams["id"] },
    TContext
  >;

  return useMutation<
    MarketplaceControllerConfirmActivateMutationResponse,
    ResponseErrorConfig<Error>,
    { id: MarketplaceControllerConfirmActivatePathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    MarketplaceControllerConfirmActivateMutationResponse,
    ResponseErrorConfig<Error>,
    { id: MarketplaceControllerConfirmActivatePathParams["id"] },
    TContext
  >;
}
