/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { chatUsageControllerDeduct } from "@/gen-quest/client/chat-usage-controller-deduct";
import type { ChatUsageControllerDeductMutationResponse } from "@/gen-quest/types/chat-usage-controller-deduct";

export const chatUsageControllerDeductMutationKey = () =>
  [{ url: "/api/chat-usage/deduct" }] as const;

export type ChatUsageControllerDeductMutationKey = ReturnType<
  typeof chatUsageControllerDeductMutationKey
>;

export function chatUsageControllerDeductMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = chatUsageControllerDeductMutationKey();
  return mutationOptions<
    ChatUsageControllerDeductMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return chatUsageControllerDeduct(config);
    },
  });
}

/**
 * @summary Deduct one chat turn for the authenticated user
 * {@link /api/chat-usage/deduct}
 */
export function useChatUsageControllerDeduct<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ChatUsageControllerDeductMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? chatUsageControllerDeductMutationKey();

  const baseOptions = chatUsageControllerDeductMutationOptions(config) as UseMutationOptions<
    ChatUsageControllerDeductMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;

  return useMutation<
    ChatUsageControllerDeductMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    ChatUsageControllerDeductMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;
}
