/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { adminControllerUpdateTask } from "@/gen-quest/client/admin-controller-update-task";
import type {
  AdminControllerUpdateTaskMutationRequest,
  AdminControllerUpdateTaskMutationResponse,
  AdminControllerUpdateTaskPathParams,
} from "@/gen-quest/types/admin-controller-update-task";

export const adminControllerUpdateTaskMutationKey = () =>
  [{ url: "/api/quest/admin/tasks/:taskId" }] as const;

export type AdminControllerUpdateTaskMutationKey = ReturnType<
  typeof adminControllerUpdateTaskMutationKey
>;

export function adminControllerUpdateTaskMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AdminControllerUpdateTaskMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = adminControllerUpdateTaskMutationKey();
  return mutationOptions<
    AdminControllerUpdateTaskMutationResponse,
    ResponseErrorConfig<Error>,
    {
      taskId: AdminControllerUpdateTaskPathParams["taskId"];
      data: AdminControllerUpdateTaskMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ taskId, data }) => {
      return adminControllerUpdateTask(taskId, data, config);
    },
  });
}

/**
 * {@link /api/quest/admin/tasks/:taskId}
 */
export function useAdminControllerUpdateTask<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AdminControllerUpdateTaskMutationResponse,
      ResponseErrorConfig<Error>,
      {
        taskId: AdminControllerUpdateTaskPathParams["taskId"];
        data: AdminControllerUpdateTaskMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AdminControllerUpdateTaskMutationRequest>> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? adminControllerUpdateTaskMutationKey();

  const baseOptions = adminControllerUpdateTaskMutationOptions(config) as UseMutationOptions<
    AdminControllerUpdateTaskMutationResponse,
    ResponseErrorConfig<Error>,
    {
      taskId: AdminControllerUpdateTaskPathParams["taskId"];
      data: AdminControllerUpdateTaskMutationRequest;
    },
    TContext
  >;

  return useMutation<
    AdminControllerUpdateTaskMutationResponse,
    ResponseErrorConfig<Error>,
    {
      taskId: AdminControllerUpdateTaskPathParams["taskId"];
      data: AdminControllerUpdateTaskMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AdminControllerUpdateTaskMutationResponse,
    ResponseErrorConfig<Error>,
    {
      taskId: AdminControllerUpdateTaskPathParams["taskId"];
      data: AdminControllerUpdateTaskMutationRequest;
    },
    TContext
  >;
}
