/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { marketplaceControllerGetFeeBalance } from "@/gen-quest/client/marketplace-controller-get-fee-balance";
import type { MarketplaceControllerGetFeeBalanceQueryResponse } from "@/gen-quest/types/marketplace-controller-get-fee-balance";

export const marketplaceControllerGetFeeBalanceSuspenseQueryKey = () =>
  [{ url: "/api/marketplace/fees/balance" }] as const;

export type MarketplaceControllerGetFeeBalanceSuspenseQueryKey = ReturnType<
  typeof marketplaceControllerGetFeeBalanceSuspenseQueryKey
>;

export function marketplaceControllerGetFeeBalanceSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketplaceControllerGetFeeBalanceSuspenseQueryKey();
  return queryOptions<
    MarketplaceControllerGetFeeBalanceQueryResponse,
    ResponseErrorConfig<Error>,
    MarketplaceControllerGetFeeBalanceQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketplaceControllerGetFeeBalance({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get publisher's claimable fee balance
 * {@link /api/marketplace/fees/balance}
 */
export function useMarketplaceControllerGetFeeBalanceSuspense<
  TData = MarketplaceControllerGetFeeBalanceQueryResponse,
  TQueryKey extends QueryKey = MarketplaceControllerGetFeeBalanceSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        MarketplaceControllerGetFeeBalanceQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? marketplaceControllerGetFeeBalanceSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...marketplaceControllerGetFeeBalanceSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
