/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TasksControllerGetClaimStatusQueryResponse, TasksControllerGetClaimStatusPathParams } from "@/gen-quest/types/tasks-controller-get-claim-status";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { tasksControllerGetClaimStatus } from "@/gen-quest/client/tasks-controller-get-claim-status";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const tasksControllerGetClaimStatusSuspenseQueryKey = (id: TasksControllerGetClaimStatusPathParams["id"] | undefined) => [{ url: '/api/tasks/:id/claim/status', params: {id:id} }] as const

export type TasksControllerGetClaimStatusSuspenseQueryKey = ReturnType<typeof tasksControllerGetClaimStatusSuspenseQueryKey>

export function tasksControllerGetClaimStatusSuspenseQueryOptions(id: TasksControllerGetClaimStatusPathParams["id"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = tasksControllerGetClaimStatusSuspenseQueryKey(id)
        return queryOptions<TasksControllerGetClaimStatusQueryResponse, ResponseErrorConfig<Error>, TasksControllerGetClaimStatusQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return tasksControllerGetClaimStatus(id!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/tasks/:id/claim/status}
 */
export function useTasksControllerGetClaimStatusSuspense<TData = TasksControllerGetClaimStatusQueryResponse, TQueryKey extends QueryKey = TasksControllerGetClaimStatusSuspenseQueryKey>(id: TasksControllerGetClaimStatusPathParams["id"] | undefined, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TasksControllerGetClaimStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? tasksControllerGetClaimStatusSuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...tasksControllerGetClaimStatusSuspenseQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}