/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { tasksControllerGetClaimStatus } from "@/gen-quest/client/tasks-controller-get-claim-status";
import type {
  TasksControllerGetClaimStatusPathParams,
  TasksControllerGetClaimStatusQueryResponse,
} from "@/gen-quest/types/tasks-controller-get-claim-status";

export const tasksControllerGetClaimStatusQueryKey = (
  id: TasksControllerGetClaimStatusPathParams["id"] | undefined
) => [{ url: "/api/quest/tasks/:id/claim/status", params: { id: id } }] as const;

export type TasksControllerGetClaimStatusQueryKey = ReturnType<
  typeof tasksControllerGetClaimStatusQueryKey
>;

export function tasksControllerGetClaimStatusQueryOptions(
  id: TasksControllerGetClaimStatusPathParams["id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = tasksControllerGetClaimStatusQueryKey(id);
  return queryOptions<
    TasksControllerGetClaimStatusQueryResponse,
    ResponseErrorConfig<Error>,
    TasksControllerGetClaimStatusQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return tasksControllerGetClaimStatus(id!, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * {@link /api/quest/tasks/:id/claim/status}
 */
export function useTasksControllerGetClaimStatus<
  TData = TasksControllerGetClaimStatusQueryResponse,
  TQueryData = TasksControllerGetClaimStatusQueryResponse,
  TQueryKey extends QueryKey = TasksControllerGetClaimStatusQueryKey,
>(
  id: TasksControllerGetClaimStatusPathParams["id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        TasksControllerGetClaimStatusQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? tasksControllerGetClaimStatusQueryKey(id);

  const query = useQuery(
    {
      ...tasksControllerGetClaimStatusQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
