/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { adminControllerUpdateQuestTask } from "@/gen-quest/client/admin-controller-update-quest-task";
import type {
  AdminControllerUpdateQuestTaskMutationRequest,
  AdminControllerUpdateQuestTaskMutationResponse,
  AdminControllerUpdateQuestTaskPathParams,
} from "@/gen-quest/types/admin-controller-update-quest-task";

export const adminControllerUpdateQuestTaskMutationKey = () =>
  [{ url: "/api/admin/quest-campaigns/:id/tasks/:taskId" }] as const;

export type AdminControllerUpdateQuestTaskMutationKey = ReturnType<
  typeof adminControllerUpdateQuestTaskMutationKey
>;

export function adminControllerUpdateQuestTaskMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AdminControllerUpdateQuestTaskMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = adminControllerUpdateQuestTaskMutationKey();
  return mutationOptions<
    AdminControllerUpdateQuestTaskMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: AdminControllerUpdateQuestTaskPathParams["id"];
      taskId: AdminControllerUpdateQuestTaskPathParams["taskId"];
      data: AdminControllerUpdateQuestTaskMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, taskId, data }) => {
      return adminControllerUpdateQuestTask(id, taskId, data, config);
    },
  });
}

/**
 * @summary Update quest task
 * {@link /api/admin/quest-campaigns/:id/tasks/:taskId}
 */
export function useAdminControllerUpdateQuestTask<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AdminControllerUpdateQuestTaskMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: AdminControllerUpdateQuestTaskPathParams["id"];
        taskId: AdminControllerUpdateQuestTaskPathParams["taskId"];
        data: AdminControllerUpdateQuestTaskMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AdminControllerUpdateQuestTaskMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? adminControllerUpdateQuestTaskMutationKey();

  const baseOptions = adminControllerUpdateQuestTaskMutationOptions(config) as UseMutationOptions<
    AdminControllerUpdateQuestTaskMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: AdminControllerUpdateQuestTaskPathParams["id"];
      taskId: AdminControllerUpdateQuestTaskPathParams["taskId"];
      data: AdminControllerUpdateQuestTaskMutationRequest;
    },
    TContext
  >;

  return useMutation<
    AdminControllerUpdateQuestTaskMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: AdminControllerUpdateQuestTaskPathParams["id"];
      taskId: AdminControllerUpdateQuestTaskPathParams["taskId"];
      data: AdminControllerUpdateQuestTaskMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AdminControllerUpdateQuestTaskMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: AdminControllerUpdateQuestTaskPathParams["id"];
      taskId: AdminControllerUpdateQuestTaskPathParams["taskId"];
      data: AdminControllerUpdateQuestTaskMutationRequest;
    },
    TContext
  >;
}
