/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AccountControllerGetActivityPathParams,
  AccountControllerGetActivityQueryParams,
  AccountControllerGetActivityQueryResponse,
} from "@/gen-backend/types/account-controller-get-activity";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getAccountControllerGetActivityUrl(
  publicKey: AccountControllerGetActivityPathParams["publicKey"]
) {
  const res = { method: "GET", url: `/api/account/activity/${publicKey}` as const };
  return res;
}

/**
 * @summary Get recent activity log for a managed account
 * {@link /api/account/activity/:publicKey}
 */
export async function accountControllerGetActivity(
  publicKey: AccountControllerGetActivityPathParams["publicKey"],
  params: AccountControllerGetActivityQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AccountControllerGetActivityQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getAccountControllerGetActivityUrl(publicKey).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
