/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AccountControllerBuildSetupTradingTxMutationResponse } from "@/gen-backend/types/account-controller-build-setup-trading-tx";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAccountControllerBuildSetupTradingTxUrl() {
  const res = { method: 'POST', url: `/api/account/setup-trading` as const }
  return res
}

/**
 * @summary Build unsigned setup TX for harvest-only session key on trading account
 * {@link /api/account/setup-trading}
 */
export async function accountControllerBuildSetupTradingTx(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AccountControllerBuildSetupTradingTxMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getAccountControllerBuildSetupTradingTxUrl().url.toString(), ... requestConfig })
  return res.data
}