/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminSeasonsControllerSetRankRewardsMutationRequest, AdminSeasonsControllerSetRankRewardsMutationResponse, AdminSeasonsControllerSetRankRewardsPathParams } from "@/gen-backend/types/admin-seasons-controller-set-rank-rewards";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminSeasonsControllerSetRankRewardsUrl(id: AdminSeasonsControllerSetRankRewardsPathParams["id"]) {
  const res = { method: 'PUT', url: `/api/quest/admin/seasons/${id}/rank-rewards` as const }
  return res
}

/**
 * {@link /api/quest/admin/seasons/:id/rank-rewards}
 */
export async function adminSeasonsControllerSetRankRewards(id: AdminSeasonsControllerSetRankRewardsPathParams["id"], data: AdminSeasonsControllerSetRankRewardsMutationRequest, config: Partial<RequestConfig<AdminSeasonsControllerSetRankRewardsMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminSeasonsControllerSetRankRewardsMutationResponse, ResponseErrorConfig<Error>, AdminSeasonsControllerSetRankRewardsMutationRequest>({ method : "PUT", url : getAdminSeasonsControllerSetRankRewardsUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}