/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminControllerGetTransactionsQueryResponse, AdminControllerGetTransactionsQueryParams } from "@/gen-backend/types/admin-controller-get-transactions";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminControllerGetTransactionsUrl() {
  const res = { method: 'GET', url: `/api/admin/analytics/transactions` as const }
  return res
}

/**
 * @summary Transaction log for the analytics page
 * {@link /api/admin/analytics/transactions}
 */
export async function adminControllerGetTransactions(params?: AdminControllerGetTransactionsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerGetTransactionsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getAdminControllerGetTransactionsUrl().url.toString(), params, ... requestConfig })
  return res.data
}