/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminControllerExportCodesQueryResponse } from "@/gen-backend/types/admin-controller-export-codes";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminControllerExportCodesUrl() {
  const res = { method: 'GET', url: `/api/admin/codes/export` as const }
  return res
}

/**
 * @summary Export all EARLY_ACCESS codes as CSV
 * {@link /api/admin/codes/export}
 */
export async function adminControllerExportCodes(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerExportCodesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getAdminControllerExportCodesUrl().url.toString(), ... requestConfig })
  return res.data
}