/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminControllerUpdateFomoEventMutationRequest, AdminControllerUpdateFomoEventMutationResponse, AdminControllerUpdateFomoEventPathParams } from "@/gen-backend/types/admin-controller-update-fomo-event";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminControllerUpdateFomoEventUrl(id: AdminControllerUpdateFomoEventPathParams["id"]) {
  const res = { method: 'PATCH', url: `/api/admin/quest-fomo/${id}` as const }
  return res
}

/**
 * @summary Update a FOMO event
 * {@link /api/admin/quest-fomo/:id}
 */
export async function adminControllerUpdateFomoEvent(id: AdminControllerUpdateFomoEventPathParams["id"], data: AdminControllerUpdateFomoEventMutationRequest, config: Partial<RequestConfig<AdminControllerUpdateFomoEventMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminControllerUpdateFomoEventMutationResponse, ResponseErrorConfig<Error>, AdminControllerUpdateFomoEventMutationRequest>({ method : "PATCH", url : getAdminControllerUpdateFomoEventUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}