/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminControllerGetWalletsQueryResponse, AdminControllerGetWalletsQueryParams } from "@/gen-backend/types/admin-controller-get-wallets";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminControllerGetWalletsUrl() {
  const res = { method: 'GET', url: `/api/admin/analytics/wallets` as const }
  return res
}

/**
 * @summary Trade-volume keeper-wallet table for the analytics page
 * {@link /api/admin/analytics/wallets}
 */
export async function adminControllerGetWallets(params?: AdminControllerGetWalletsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerGetWalletsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getAdminControllerGetWalletsUrl().url.toString(), params, ... requestConfig })
  return res.data
}