/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminControllerExportQuestWalletsQueryResponse } from "@/gen-backend/types/admin-controller-export-quest-wallets";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminControllerExportQuestWalletsUrl() {
  const res = { method: 'GET', url: `/api/admin/quest-wallets/export` as const }
  return res
}

/**
 * @summary Export full quest wallet leaderboard as CSV
 * {@link /api/admin/quest-wallets/export}
 */
export async function adminControllerExportQuestWallets(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerExportQuestWalletsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getAdminControllerExportQuestWalletsUrl().url.toString(), ... requestConfig })
  return res.data
}