/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminSeasonsControllerCreateMutationRequest, AdminSeasonsControllerCreateMutationResponse } from "@/gen-backend/types/admin-seasons-controller-create";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminSeasonsControllerCreateUrl() {
  const res = { method: 'POST', url: `/api/quest/admin/seasons` as const }
  return res
}

/**
 * {@link /api/quest/admin/seasons}
 */
export async function adminSeasonsControllerCreate(data: AdminSeasonsControllerCreateMutationRequest, config: Partial<RequestConfig<AdminSeasonsControllerCreateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminSeasonsControllerCreateMutationResponse, ResponseErrorConfig<Error>, AdminSeasonsControllerCreateMutationRequest>({ method : "POST", url : getAdminSeasonsControllerCreateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}