/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminControllerSetReferralUserSegmentMutationRequest, AdminControllerSetReferralUserSegmentMutationResponse, AdminControllerSetReferralUserSegmentPathParams } from "@/gen-backend/types/admin-controller-set-referral-user-segment";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminControllerSetReferralUserSegmentUrl(userId: AdminControllerSetReferralUserSegmentPathParams["userId"]) {
  const res = { method: 'PATCH', url: `/api/admin/quest-referral/users/${userId}/segment` as const }
  return res
}

/**
 * @summary Assign a user segment (NORMAL/KOL/INFLUENCER)
 * {@link /api/admin/quest-referral/users/:userId/segment}
 */
export async function adminControllerSetReferralUserSegment(userId: AdminControllerSetReferralUserSegmentPathParams["userId"], data: AdminControllerSetReferralUserSegmentMutationRequest, config: Partial<RequestConfig<AdminControllerSetReferralUserSegmentMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AdminControllerSetReferralUserSegmentMutationResponse, ResponseErrorConfig<Error>, AdminControllerSetReferralUserSegmentMutationRequest>({ method : "PATCH", url : getAdminControllerSetReferralUserSegmentUrl(userId).url.toString(), data : requestData, ... requestConfig })
  return res.data
}