/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AdminControllerGenerateCodesMutationRequest,
  AdminControllerGenerateCodesMutationResponse,
} from "@/gen-backend/types/admin-controller-generate-codes";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getAdminControllerGenerateCodesUrl() {
  const res = { method: "POST", url: `/api/admin/codes/generate` as const };
  return res;
}

/**
 * @summary Bulk generate EARLY_ACCESS codes
 * {@link /api/admin/codes/generate}
 */
export async function adminControllerGenerateCodes(
  data: AdminControllerGenerateCodesMutationRequest,
  config: Partial<RequestConfig<AdminControllerGenerateCodesMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AdminControllerGenerateCodesMutationResponse,
    ResponseErrorConfig<Error>,
    AdminControllerGenerateCodesMutationRequest
  >({
    method: "POST",
    url: getAdminControllerGenerateCodesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
