/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AdminControllerGetVolumeTvlQueryResponse, AdminControllerGetVolumeTvlQueryParams } from "@/gen-backend/types/admin-controller-get-volume-tvl";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAdminControllerGetVolumeTvlUrl() {
  const res = { method: 'GET', url: `/api/admin/analytics/volume-tvl` as const }
  return res
}

/**
 * @summary Volume and cumulative TVL time series for the analytics page
 * {@link /api/admin/analytics/volume-tvl}
 */
export async function adminControllerGetVolumeTvl(params?: AdminControllerGetVolumeTvlQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerGetVolumeTvlQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getAdminControllerGetVolumeTvlUrl().url.toString(), params, ... requestConfig })
  return res.data
}