/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AuthControllerLoginMutationRequest,
  AuthControllerLoginMutationResponse,
} from "@/gen-backend/types/auth-controller-login";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getAuthControllerLoginUrl() {
  const res = { method: "POST", url: `/api/auth/login` as const };
  return res;
}

/**
 * @summary Admin login with username/password
 * {@link /api/auth/login}
 */
export async function authControllerLogin(
  data: AuthControllerLoginMutationRequest,
  config: Partial<RequestConfig<AuthControllerLoginMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AuthControllerLoginMutationResponse,
    ResponseErrorConfig<Error>,
    AuthControllerLoginMutationRequest
  >({
    method: "POST",
    url: getAuthControllerLoginUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
