/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { AuthControllerChallengeMutationRequest, AuthControllerChallengeMutationResponse } from "@/gen-backend/types/auth-controller-challenge";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getAuthControllerChallengeUrl() {
  const res = { method: 'POST', url: `/api/auth/challenge` as const }
  return res
}

/**
 * @summary Request a challenge nonce for wallet authentication
 * {@link /api/auth/challenge}
 */
export async function authControllerChallenge(data: AuthControllerChallengeMutationRequest, config: Partial<RequestConfig<AuthControllerChallengeMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AuthControllerChallengeMutationResponse, ResponseErrorConfig<Error>, AuthControllerChallengeMutationRequest>({ method : "POST", url : getAuthControllerChallengeUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}