/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AuthControllerVerifyMutationRequest,
  AuthControllerVerifyMutationResponse,
} from "@/gen-backend/types/auth-controller-verify";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getAuthControllerVerifyUrl() {
  const res = { method: "POST", url: `/api/auth/verify` as const };
  return res;
}

/**
 * @summary Verify signed challenge and authenticate with Stellar wallet
 * {@link /api/auth/verify}
 */
export async function authControllerVerify(
  data?: AuthControllerVerifyMutationRequest,
  config: Partial<RequestConfig<AuthControllerVerifyMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AuthControllerVerifyMutationResponse,
    ResponseErrorConfig<Error>,
    AuthControllerVerifyMutationRequest
  >({
    method: "POST",
    url: getAuthControllerVerifyUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
