/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { CampaignsControllerGetClaimsQueryResponse, CampaignsControllerGetClaimsPathParams } from "@/gen-backend/types/campaigns-controller-get-claims";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getCampaignsControllerGetClaimsUrl(id: CampaignsControllerGetClaimsPathParams["id"]) {
  const res = { method: 'GET', url: `/api/quest/campaigns/${id}/claims` as const }
  return res
}

/**
 * {@link /api/quest/campaigns/:id/claims}
 */
export async function campaignsControllerGetClaims(id: CampaignsControllerGetClaimsPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CampaignsControllerGetClaimsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getCampaignsControllerGetClaimsUrl(id).url.toString(), ... requestConfig })
  return res.data
}