/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { ChatUsageInternalControllerGetSnapshotQueryResponse, ChatUsageInternalControllerGetSnapshotPathParams } from "@/gen-backend/types/chat-usage-internal-controller-get-snapshot";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getChatUsageInternalControllerGetSnapshotUrl(userId: ChatUsageInternalControllerGetSnapshotPathParams["userId"]) {
  const res = { method: 'GET', url: `/api/internal/chat-usage/snapshot/${userId}` as const }
  return res
}

/**
 * {@link /api/internal/chat-usage/snapshot/:userId}
 */
export async function chatUsageInternalControllerGetSnapshot(userId: ChatUsageInternalControllerGetSnapshotPathParams["userId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ChatUsageInternalControllerGetSnapshotQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getChatUsageInternalControllerGetSnapshotUrl(userId).url.toString(), ... requestConfig })
  return res.data
}