/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreditControllerGetMeQueryResponse } from "@/gen-backend/types/credit-controller-get-me";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getCreditControllerGetMeUrl() {
  const res = { method: "GET", url: `/api/credit/me` as const };
  return res;
}

/**
 * @summary Get the authenticated user credit snapshot
 * {@link /api/credit/me}
 */
export async function creditControllerGetMe(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CreditControllerGetMeQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getCreditControllerGetMeUrl().url.toString(), ...requestConfig });
  return res.data;
}
