/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { GasSponsorshipControllerMarkSeenMutationResponse } from "@/gen-backend/types/gas-sponsorship-controller-mark-seen";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getGasSponsorshipControllerMarkSeenUrl() {
  const res = { method: 'POST', url: `/api/sponsorship/modal-seen` as const }
  return res
}

/**
 * {@link /api/sponsorship/modal-seen}
 */
export async function gasSponsorshipControllerMarkSeen(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GasSponsorshipControllerMarkSeenMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getGasSponsorshipControllerMarkSeenUrl().url.toString(), ... requestConfig })
  return res.data
}