/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerDeactivateStrategyMutationResponse, MarketplaceControllerDeactivateStrategyPathParams } from "@/gen-backend/types/marketplace-controller-deactivate-strategy";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerDeactivateStrategyUrl(id: MarketplaceControllerDeactivateStrategyPathParams["id"]) {
  const res = { method: 'POST', url: `/api/marketplace/strategies/${id}/deactivate` as const }
  return res
}

/**
 * @summary Deactivate strategy on user's vault
 * {@link /api/marketplace/strategies/:id/deactivate}
 */
export async function marketplaceControllerDeactivateStrategy(id: MarketplaceControllerDeactivateStrategyPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerDeactivateStrategyMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getMarketplaceControllerDeactivateStrategyUrl(id).url.toString(), ... requestConfig })
  return res.data
}