/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerConfirmPublishMutationResponse } from "@/gen-backend/types/marketplace-controller-confirm-publish";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerConfirmPublishUrl() {
  const res = { method: 'POST', url: `/api/marketplace/strategies/build/confirm` as const }
  return res
}

/**
 * @summary Confirm strategy publish after publisher signs TX
 * {@link /api/marketplace/strategies/build/confirm}
 */
export async function marketplaceControllerConfirmPublish(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerConfirmPublishMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getMarketplaceControllerConfirmPublishUrl().url.toString(), ... requestConfig })
  return res.data
}