/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerGetPublisherClaimsQueryResponse } from "@/gen-backend/types/marketplace-controller-get-publisher-claims";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerGetPublisherClaimsUrl() {
  const res = { method: 'GET', url: `/api/marketplace/publisher/claims` as const }
  return res
}

/**
 * @summary Authenticated publisher's fee-claim history
 * {@link /api/marketplace/publisher/claims}
 */
export async function marketplaceControllerGetPublisherClaims(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerGetPublisherClaimsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getMarketplaceControllerGetPublisherClaimsUrl().url.toString(), ... requestConfig })
  return res.data
}