/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerConfirmClaimMutationResponse } from "@/gen-backend/types/marketplace-controller-confirm-claim";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerConfirmClaimUrl() {
  const res = { method: 'POST', url: `/api/marketplace/fees/claim/confirm` as const }
  return res
}

/**
 * @summary Confirm claim after publisher signs TX
 * {@link /api/marketplace/fees/claim/confirm}
 */
export async function marketplaceControllerConfirmClaim(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerConfirmClaimMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getMarketplaceControllerConfirmClaimUrl().url.toString(), ... requestConfig })
  return res.data
}