/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { MarketplaceControllerGetMyStrategiesQueryResponse } from "@/gen-backend/types/marketplace-controller-get-my-strategies";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getMarketplaceControllerGetMyStrategiesUrl() {
  const res = { method: 'GET', url: `/api/marketplace/my-strategies` as const }
  return res
}

/**
 * @summary Get strategies activated on user's vaults
 * {@link /api/marketplace/my-strategies}
 */
export async function marketplaceControllerGetMyStrategies(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketplaceControllerGetMyStrategiesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getMarketplaceControllerGetMyStrategiesUrl().url.toString(), ... requestConfig })
  return res.data
}