/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { PoolsControllerGetPoolsQueryResponse, PoolsControllerGetPoolsQueryParams } from "@/gen-backend/types/pools-controller-get-pools";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getPoolsControllerGetPoolsUrl() {
  const res = { method: 'GET', url: `/api/pools` as const }
  return res
}

/**
 * {@link /api/pools}
 */
export async function poolsControllerGetPools(params?: PoolsControllerGetPoolsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PoolsControllerGetPoolsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPoolsControllerGetPoolsUrl().url.toString(), params, ... requestConfig })
  return res.data
}