/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PortfolioControllerRegisterAddressMutationRequest,
  PortfolioControllerRegisterAddressMutationResponse,
} from "@/gen-backend/types/portfolio-controller-register-address";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getPortfolioControllerRegisterAddressUrl() {
  const res = { method: "POST", url: `/api/portfolio/snapshot` as const };
  return res;
}

/**
 * @summary Register a wallet address for portfolio tracking
 * {@link /api/portfolio/snapshot}
 */
export async function portfolioControllerRegisterAddress(
  data: PortfolioControllerRegisterAddressMutationRequest,
  config: Partial<RequestConfig<PortfolioControllerRegisterAddressMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PortfolioControllerRegisterAddressMutationResponse,
    ResponseErrorConfig<Error>,
    PortfolioControllerRegisterAddressMutationRequest
  >({
    method: "POST",
    url: getPortfolioControllerRegisterAddressUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
