/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ProtocolControllerGetLendingApyQueryParams,
  ProtocolControllerGetLendingApyQueryResponse,
} from "@/gen-backend/types/protocol-controller-get-lending-apy";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getProtocolControllerGetLendingApyUrl() {
  const res = { method: "GET", url: `/api/protocol/apy` as const };
  return res;
}

/**
 * @summary Get lending APY for a protocol
 * {@link /api/protocol/apy}
 */
export async function protocolControllerGetLendingApy(
  params: ProtocolControllerGetLendingApyQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ProtocolControllerGetLendingApyQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getProtocolControllerGetLendingApyUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
