/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { ProtocolControllerGetAllApysQueryResponse, ProtocolControllerGetAllApysQueryParams } from "@/gen-backend/types/protocol-controller-get-all-apys";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getProtocolControllerGetAllApysUrl() {
  const res = { method: 'GET', url: `/api/protocol/apy/all` as const }
  return res
}

/**
 * @summary Get APY for all protocols across all chains
 * {@link /api/protocol/apy/all}
 */
export async function protocolControllerGetAllApys(params: ProtocolControllerGetAllApysQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ProtocolControllerGetAllApysQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getProtocolControllerGetAllApysUrl().url.toString(), params, ... requestConfig })
  return res.data
}