/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { ProtocolControllerGetUserPositionQueryResponse, ProtocolControllerGetUserPositionQueryParams } from "@/gen-backend/types/protocol-controller-get-user-position";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getProtocolControllerGetUserPositionUrl() {
  const res = { method: 'GET', url: `/api/protocol/position` as const }
  return res
}

/**
 * @summary Get user position in a protocol
 * {@link /api/protocol/position}
 */
export async function protocolControllerGetUserPosition(params: ProtocolControllerGetUserPositionQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ProtocolControllerGetUserPositionQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getProtocolControllerGetUserPositionUrl().url.toString(), params, ... requestConfig })
  return res.data
}