/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PublicControllerGetQuestVolumeQueryParams,
  PublicControllerGetQuestVolumeQueryResponse,
} from "@/gen-backend/types/public-controller-get-quest-volume";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getPublicControllerGetQuestVolumeUrl() {
  const res = { method: "GET", url: `/api/public/quest-volume` as const };
  return res;
}

/**
 * @summary List individual quest-volume transactions (paginated, newest first)
 * {@link /api/public/quest-volume}
 */
export async function publicControllerGetQuestVolume(
  params?: PublicControllerGetQuestVolumeQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PublicControllerGetQuestVolumeQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getPublicControllerGetQuestVolumeUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
