/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { RebalanceControllerGetStatusQueryResponse } from "@/gen-backend/types/rebalance-controller-get-status";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getRebalanceControllerGetStatusUrl() {
  const res = { method: 'GET', url: `/api/rebalance/status` as const }
  return res
}

/**
 * @summary Get rebalance bot status
 * {@link /api/rebalance/status}
 */
export async function rebalanceControllerGetStatus(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<RebalanceControllerGetStatusQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getRebalanceControllerGetStatusUrl().url.toString(), ... requestConfig })
  return res.data
}