/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RebalanceControllerRunManualMutationResponse } from "@/gen-backend/types/rebalance-controller-run-manual";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getRebalanceControllerRunManualUrl() {
  const res = { method: "POST", url: `/api/rebalance/run` as const };
  return res;
}

/**
 * @summary Manually run allocation cycle immediately
 * {@link /api/rebalance/run}
 */
export async function rebalanceControllerRunManual(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    RebalanceControllerRunManualMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "POST", url: getRebalanceControllerRunManualUrl().url.toString(), ...requestConfig });
  return res.data;
}
