/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { ReferralControllerCheckCodeQueryResponse, ReferralControllerCheckCodePathParams } from "@/gen-backend/types/referral-controller-check-code";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getReferralControllerCheckCodeUrl(code: ReferralControllerCheckCodePathParams["code"]) {
  const res = { method: 'GET', url: `/api/quest/referral/check/${code}` as const }
  return res
}

/**
 * {@link /api/quest/referral/check/:code}
 */
export async function referralControllerCheckCode(code: ReferralControllerCheckCodePathParams["code"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ReferralControllerCheckCodeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getReferralControllerCheckCodeUrl(code).url.toString(), ... requestConfig })
  return res.data
}