/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { ReferralControllerLinkXStartMutationResponse } from "@/gen-backend/types/referral-controller-link-xstart";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getReferralControllerLinkXStartUrl() {
  const res = { method: 'POST', url: `/api/referral/link-x/start` as const }
  return res
}

/**
 * @summary Issue a one-time nonce so the caller can post a verification tweet
 * {@link /api/referral/link-x/start}
 */
export async function referralControllerLinkXStart(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ReferralControllerLinkXStartMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getReferralControllerLinkXStartUrl().url.toString(), ... requestConfig })
  return res.data
}