/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { ReferralControllerVerifyShareMutationRequest, ReferralControllerVerifyShareMutationResponse } from "@/gen-backend/types/referral-controller-verify-share";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getReferralControllerVerifyShareUrl() {
  const res = { method: 'POST', url: `/api/referral/verify-share` as const }
  return res
}

/**
 * @summary Verify a tweet share and award X-share credits (501 when flag off)
 * {@link /api/referral/verify-share}
 */
export async function referralControllerVerifyShare(data: ReferralControllerVerifyShareMutationRequest, config: Partial<RequestConfig<ReferralControllerVerifyShareMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ReferralControllerVerifyShareMutationResponse, ResponseErrorConfig<Error>, ReferralControllerVerifyShareMutationRequest>({ method : "POST", url : getReferralControllerVerifyShareUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}