/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { SponsorAdminControllerExportLogsQueryResponse } from "@/gen-backend/types/sponsor-admin-controller-export-logs";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getSponsorAdminControllerExportLogsUrl() {
  const res = { method: 'GET', url: `/api/admin/sponsor/logs/export` as const }
  return res
}

/**
 * @summary Export all sponsor transaction logs as CSV
 * {@link /api/admin/sponsor/logs/export}
 */
export async function sponsorAdminControllerExportLogs(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<SponsorAdminControllerExportLogsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getSponsorAdminControllerExportLogsUrl().url.toString(), ... requestConfig })
  return res.data
}