/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { TopupAdminControllerListQueryResponse, TopupAdminControllerListQueryParams } from "@/gen-backend/types/topup-admin-controller-list";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getTopupAdminControllerListUrl() {
  const res = { method: 'GET', url: `/api/admin/topups` as const }
  return res
}

/**
 * @summary List pending fiat topups (admin reconcile queue)
 * {@link /api/admin/topups}
 */
export async function topupAdminControllerList(params?: TopupAdminControllerListQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TopupAdminControllerListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getTopupAdminControllerListUrl().url.toString(), params, ... requestConfig })
  return res.data
}