/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { TxSubmitControllerSubmitMutationRequest, TxSubmitControllerSubmitMutationResponse } from "@/gen-backend/types/tx-submit-controller-submit";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getTxSubmitControllerSubmitUrl() {
  const res = { method: 'POST', url: `/api/tx/submit-with-sponsor` as const }
  return res
}

/**
 * {@link /api/tx/submit-with-sponsor}
 */
export async function txSubmitControllerSubmit(data: TxSubmitControllerSubmitMutationRequest, config: Partial<RequestConfig<TxSubmitControllerSubmitMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<TxSubmitControllerSubmitMutationResponse, ResponseErrorConfig<Error>, TxSubmitControllerSubmitMutationRequest>({ method : "POST", url : getTxSubmitControllerSubmitUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}