/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-backend-client";
import type { UsersControllerUpdateAvatarMutationResponse } from "@/gen-backend/types/users-controller-update-avatar";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";

function getUsersControllerUpdateAvatarUrl() {
  const res = { method: 'POST', url: `/api/quest/users/me/avatar` as const }
  return res
}

/**
 * {@link /api/quest/users/me/avatar}
 */
export async function usersControllerUpdateAvatar(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<UsersControllerUpdateAvatarMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getUsersControllerUpdateAvatarUrl().url.toString(), ... requestConfig })
  return res.data
}