/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  WaitlistControllerRegisterMutationRequest,
  WaitlistControllerRegisterMutationResponse,
} from "@/gen-backend/types/waitlist-controller-register";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/kubb-backend-client";
import fetch from "@/lib/kubb-backend-client";

function getWaitlistControllerRegisterUrl() {
  const res = { method: "POST", url: `/api/waitlist/register` as const };
  return res;
}

/**
 * @summary Register for early access waitlist (email legacy)
 * {@link /api/waitlist/register}
 */
export async function waitlistControllerRegister(
  data: WaitlistControllerRegisterMutationRequest,
  config: Partial<RequestConfig<WaitlistControllerRegisterMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    WaitlistControllerRegisterMutationResponse,
    ResponseErrorConfig<Error>,
    WaitlistControllerRegisterMutationRequest
  >({
    method: "POST",
    url: getWaitlistControllerRegisterUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
