/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountControllerDepositFundMutationResponse } from "@/gen-backend/types/account-controller-deposit-fund";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { accountControllerDepositFund } from "@/gen-backend/client/account-controller-deposit-fund";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const accountControllerDepositFundMutationKey = () => [{ url: '/api/account/deposit-trading/fund' }] as const

export type AccountControllerDepositFundMutationKey = ReturnType<typeof accountControllerDepositFundMutationKey>

export function accountControllerDepositFundMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = accountControllerDepositFundMutationKey()
        return mutationOptions<AccountControllerDepositFundMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return accountControllerDepositFund(config)
          },
        })

}

/**
 * @summary Build XDR to fund the trading keeper with token_in (user signs)
 * {@link /api/account/deposit-trading/fund}
 */
export function useAccountControllerDepositFund<TContext>(options: 
{
  mutation?: UseMutationOptions<AccountControllerDepositFundMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? accountControllerDepositFundMutationKey()

          const baseOptions = accountControllerDepositFundMutationOptions(config) as UseMutationOptions<AccountControllerDepositFundMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<AccountControllerDepositFundMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AccountControllerDepositFundMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}