/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerListFomoEventsQueryResponse } from "@/gen-backend/types/admin-controller-list-fomo-events";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminControllerListFomoEvents } from "@/gen-backend/client/admin-controller-list-fomo-events";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminControllerListFomoEventsQueryKey = () => [{ url: '/api/admin/quest-fomo' }] as const

export type AdminControllerListFomoEventsQueryKey = ReturnType<typeof adminControllerListFomoEventsQueryKey>

export function adminControllerListFomoEventsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerListFomoEventsQueryKey()
        return queryOptions<AdminControllerListFomoEventsQueryResponse, ResponseErrorConfig<Error>, AdminControllerListFomoEventsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerListFomoEvents({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List FOMO events (admin)
 * {@link /api/admin/quest-fomo}
 */
export function useAdminControllerListFomoEvents<TData = AdminControllerListFomoEventsQueryResponse, TQueryData = AdminControllerListFomoEventsQueryResponse, TQueryKey extends QueryKey = AdminControllerListFomoEventsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AdminControllerListFomoEventsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerListFomoEventsQueryKey()
         

         const query = useQuery({
          ...adminControllerListFomoEventsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}