/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SponsorAdminControllerGetConfigQueryResponse } from "@/gen-backend/types/sponsor-admin-controller-get-config";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { sponsorAdminControllerGetConfig } from "@/gen-backend/client/sponsor-admin-controller-get-config";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const sponsorAdminControllerGetConfigSuspenseQueryKey = () => [{ url: '/api/admin/sponsor/config' }] as const

export type SponsorAdminControllerGetConfigSuspenseQueryKey = ReturnType<typeof sponsorAdminControllerGetConfigSuspenseQueryKey>

export function sponsorAdminControllerGetConfigSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = sponsorAdminControllerGetConfigSuspenseQueryKey()
        return queryOptions<SponsorAdminControllerGetConfigQueryResponse, ResponseErrorConfig<Error>, SponsorAdminControllerGetConfigQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return sponsorAdminControllerGetConfig({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get current sponsor config and used slot count
 * {@link /api/admin/sponsor/config}
 */
export function useSponsorAdminControllerGetConfigSuspense<TData = SponsorAdminControllerGetConfigQueryResponse, TQueryKey extends QueryKey = SponsorAdminControllerGetConfigSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<SponsorAdminControllerGetConfigQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? sponsorAdminControllerGetConfigSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...sponsorAdminControllerGetConfigSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}