/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { accountControllerGetActivity } from "@/gen-backend/client/account-controller-get-activity";
import type {
  AccountControllerGetActivityPathParams,
  AccountControllerGetActivityQueryParams,
  AccountControllerGetActivityQueryResponse,
} from "@/gen-backend/types/account-controller-get-activity";

export const accountControllerGetActivityQueryKey = (
  publicKey: AccountControllerGetActivityPathParams["publicKey"],
  params: AccountControllerGetActivityQueryParams
) =>
  [
    { url: "/api/account/activity/:publicKey", params: { publicKey: publicKey } },
    ...(params ? [params] : []),
  ] as const;

export type AccountControllerGetActivityQueryKey = ReturnType<
  typeof accountControllerGetActivityQueryKey
>;

export function accountControllerGetActivityQueryOptions(
  publicKey: AccountControllerGetActivityPathParams["publicKey"],
  params: AccountControllerGetActivityQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = accountControllerGetActivityQueryKey(publicKey, params);
  return queryOptions<
    AccountControllerGetActivityQueryResponse,
    ResponseErrorConfig<Error>,
    AccountControllerGetActivityQueryResponse,
    typeof queryKey
  >({
    enabled: !!(publicKey && params),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return accountControllerGetActivity(publicKey, params, config);
    },
  });
}

/**
 * @summary Get recent activity log for a managed account
 * {@link /api/account/activity/:publicKey}
 */
export function useAccountControllerGetActivity<
  TData = AccountControllerGetActivityQueryResponse,
  TQueryData = AccountControllerGetActivityQueryResponse,
  TQueryKey extends QueryKey = AccountControllerGetActivityQueryKey,
>(
  publicKey: AccountControllerGetActivityPathParams["publicKey"],
  params: AccountControllerGetActivityQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        AccountControllerGetActivityQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? accountControllerGetActivityQueryKey(publicKey, params);

  const query = useQuery(
    {
      ...accountControllerGetActivityQueryOptions(publicKey, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
