/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CampaignsControllerFindOneQueryResponse, CampaignsControllerFindOnePathParams } from "@/gen-backend/types/campaigns-controller-find-one";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { campaignsControllerFindOne } from "@/gen-backend/client/campaigns-controller-find-one";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const campaignsControllerFindOneQueryKey = (id: CampaignsControllerFindOnePathParams["id"] | undefined) => [{ url: '/api/quest/campaigns/:id', params: {id:id} }] as const

export type CampaignsControllerFindOneQueryKey = ReturnType<typeof campaignsControllerFindOneQueryKey>

export function campaignsControllerFindOneQueryOptions(id: CampaignsControllerFindOnePathParams["id"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = campaignsControllerFindOneQueryKey(id)
        return queryOptions<CampaignsControllerFindOneQueryResponse, ResponseErrorConfig<Error>, CampaignsControllerFindOneQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return campaignsControllerFindOne(id!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/quest/campaigns/:id}
 */
export function useCampaignsControllerFindOne<TData = CampaignsControllerFindOneQueryResponse, TQueryData = CampaignsControllerFindOneQueryResponse, TQueryKey extends QueryKey = CampaignsControllerFindOneQueryKey>(id: CampaignsControllerFindOnePathParams["id"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<CampaignsControllerFindOneQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? campaignsControllerFindOneQueryKey(id)
         

         const query = useQuery({
          ...campaignsControllerFindOneQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}