/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountControllerSubmitTxMutationRequest, AccountControllerSubmitTxMutationResponse } from "@/gen-backend/types/account-controller-submit-tx";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { accountControllerSubmitTx } from "@/gen-backend/client/account-controller-submit-tx";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const accountControllerSubmitTxMutationKey = () => [{ url: '/api/account/submit' }] as const

export type AccountControllerSubmitTxMutationKey = ReturnType<typeof accountControllerSubmitTxMutationKey>

export function accountControllerSubmitTxMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AccountControllerSubmitTxMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = accountControllerSubmitTxMutationKey()
        return mutationOptions<AccountControllerSubmitTxMutationResponse, ResponseErrorConfig<Error>, {data: AccountControllerSubmitTxMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return accountControllerSubmitTx(data, config)
          },
        })

}

/**
 * @summary Submit a signed transaction to Stellar
 * {@link /api/account/submit}
 */
export function useAccountControllerSubmitTx<TContext>(options: 
{
  mutation?: UseMutationOptions<AccountControllerSubmitTxMutationResponse, ResponseErrorConfig<Error>, {data: AccountControllerSubmitTxMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountControllerSubmitTxMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? accountControllerSubmitTxMutationKey()

          const baseOptions = accountControllerSubmitTxMutationOptions(config) as UseMutationOptions<AccountControllerSubmitTxMutationResponse, ResponseErrorConfig<Error>, {data: AccountControllerSubmitTxMutationRequest}, TContext>
          

          return useMutation<AccountControllerSubmitTxMutationResponse, ResponseErrorConfig<Error>, {data: AccountControllerSubmitTxMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AccountControllerSubmitTxMutationResponse, ResponseErrorConfig<Error>, {data: AccountControllerSubmitTxMutationRequest}, TContext>
      
}