/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { protocolControllerGetUserPosition } from "@/gen-backend/client/protocol-controller-get-user-position";
import type {
  ProtocolControllerGetUserPositionQueryParams,
  ProtocolControllerGetUserPositionQueryResponse,
} from "@/gen-backend/types/protocol-controller-get-user-position";

export const protocolControllerGetUserPositionQueryKey = (
  params: ProtocolControllerGetUserPositionQueryParams
) => [{ url: "/api/protocol/position" }, ...(params ? [params] : [])] as const;

export type ProtocolControllerGetUserPositionQueryKey = ReturnType<
  typeof protocolControllerGetUserPositionQueryKey
>;

export function protocolControllerGetUserPositionQueryOptions(
  params: ProtocolControllerGetUserPositionQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = protocolControllerGetUserPositionQueryKey(params);
  return queryOptions<
    ProtocolControllerGetUserPositionQueryResponse,
    ResponseErrorConfig<Error>,
    ProtocolControllerGetUserPositionQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return protocolControllerGetUserPosition(params, config);
    },
  });
}

/**
 * @summary Get user position in a protocol
 * {@link /api/protocol/position}
 */
export function useProtocolControllerGetUserPosition<
  TData = ProtocolControllerGetUserPositionQueryResponse,
  TQueryData = ProtocolControllerGetUserPositionQueryResponse,
  TQueryKey extends QueryKey = ProtocolControllerGetUserPositionQueryKey,
>(
  params: ProtocolControllerGetUserPositionQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ProtocolControllerGetUserPositionQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? protocolControllerGetUserPositionQueryKey(params);

  const query = useQuery(
    {
      ...protocolControllerGetUserPositionQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
