/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsersControllerUpdateProfileMutationRequest, UsersControllerUpdateProfileMutationResponse } from "@/gen-backend/types/users-controller-update-profile";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { usersControllerUpdateProfile } from "@/gen-backend/client/users-controller-update-profile";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const usersControllerUpdateProfileMutationKey = () => [{ url: '/api/quest/users/me' }] as const

export type UsersControllerUpdateProfileMutationKey = ReturnType<typeof usersControllerUpdateProfileMutationKey>

export function usersControllerUpdateProfileMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UsersControllerUpdateProfileMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = usersControllerUpdateProfileMutationKey()
        return mutationOptions<UsersControllerUpdateProfileMutationResponse, ResponseErrorConfig<Error>, {data: UsersControllerUpdateProfileMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return usersControllerUpdateProfile(data, config)
          },
        })

}

/**
 * {@link /api/quest/users/me}
 */
export function useUsersControllerUpdateProfile<TContext>(options: 
{
  mutation?: UseMutationOptions<UsersControllerUpdateProfileMutationResponse, ResponseErrorConfig<Error>, {data: UsersControllerUpdateProfileMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UsersControllerUpdateProfileMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? usersControllerUpdateProfileMutationKey()

          const baseOptions = usersControllerUpdateProfileMutationOptions(config) as UseMutationOptions<UsersControllerUpdateProfileMutationResponse, ResponseErrorConfig<Error>, {data: UsersControllerUpdateProfileMutationRequest}, TContext>
          

          return useMutation<UsersControllerUpdateProfileMutationResponse, ResponseErrorConfig<Error>, {data: UsersControllerUpdateProfileMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UsersControllerUpdateProfileMutationResponse, ResponseErrorConfig<Error>, {data: UsersControllerUpdateProfileMutationRequest}, TContext>
      
}