/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerCreateIndividualCodeMutationResponse } from "@/gen-backend/types/admin-controller-create-individual-code";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminControllerCreateIndividualCode } from "@/gen-backend/client/admin-controller-create-individual-code";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminControllerCreateIndividualCodeMutationKey = () => [{ url: '/api/admin/access-codes/individual' }] as const

export type AdminControllerCreateIndividualCodeMutationKey = ReturnType<typeof adminControllerCreateIndividualCodeMutationKey>

export function adminControllerCreateIndividualCodeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = adminControllerCreateIndividualCodeMutationKey()
        return mutationOptions<AdminControllerCreateIndividualCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return adminControllerCreateIndividualCode(config)
          },
        })

}

/**
 * @summary Create a single-use access code
 * {@link /api/admin/access-codes/individual}
 */
export function useAdminControllerCreateIndividualCode<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminControllerCreateIndividualCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminControllerCreateIndividualCodeMutationKey()

          const baseOptions = adminControllerCreateIndividualCodeMutationOptions(config) as UseMutationOptions<AdminControllerCreateIndividualCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<AdminControllerCreateIndividualCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminControllerCreateIndividualCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}