/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TopupControllerCreateQuoteMutationRequest, TopupControllerCreateQuoteMutationResponse } from "@/gen-backend/types/topup-controller-create-quote";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { topupControllerCreateQuote } from "@/gen-backend/client/topup-controller-create-quote";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const topupControllerCreateQuoteMutationKey = () => [{ url: '/api/topup/quote' }] as const

export type TopupControllerCreateQuoteMutationKey = ReturnType<typeof topupControllerCreateQuoteMutationKey>

export function topupControllerCreateQuoteMutationOptions<TContext = unknown>(config: Partial<RequestConfig<TopupControllerCreateQuoteMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = topupControllerCreateQuoteMutationKey()
        return mutationOptions<TopupControllerCreateQuoteMutationResponse, ResponseErrorConfig<Error>, {data: TopupControllerCreateQuoteMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return topupControllerCreateQuote(data, config)
          },
        })

}

/**
 * @summary Create a topup quote (crypto or fiat) for the authenticated user
 * {@link /api/topup/quote}
 */
export function useTopupControllerCreateQuote<TContext>(options: 
{
  mutation?: UseMutationOptions<TopupControllerCreateQuoteMutationResponse, ResponseErrorConfig<Error>, {data: TopupControllerCreateQuoteMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TopupControllerCreateQuoteMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? topupControllerCreateQuoteMutationKey()

          const baseOptions = topupControllerCreateQuoteMutationOptions(config) as UseMutationOptions<TopupControllerCreateQuoteMutationResponse, ResponseErrorConfig<Error>, {data: TopupControllerCreateQuoteMutationRequest}, TContext>
          

          return useMutation<TopupControllerCreateQuoteMutationResponse, ResponseErrorConfig<Error>, {data: TopupControllerCreateQuoteMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<TopupControllerCreateQuoteMutationResponse, ResponseErrorConfig<Error>, {data: TopupControllerCreateQuoteMutationRequest}, TContext>
      
}