/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthControllerCheckQueryResponse } from "@/gen-backend/types/health-controller-check";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { healthControllerCheck } from "@/gen-backend/client/health-controller-check";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const healthControllerCheckQueryKey = () => [{ url: '/api/health' }] as const

export type HealthControllerCheckQueryKey = ReturnType<typeof healthControllerCheckQueryKey>

export function healthControllerCheckQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = healthControllerCheckQueryKey()
        return queryOptions<HealthControllerCheckQueryResponse, ResponseErrorConfig<Error>, HealthControllerCheckQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return healthControllerCheck({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/health}
 */
export function useHealthControllerCheck<TData = HealthControllerCheckQueryResponse, TQueryData = HealthControllerCheckQueryResponse, TQueryKey extends QueryKey = HealthControllerCheckQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<HealthControllerCheckQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? healthControllerCheckQueryKey()
         

         const query = useQuery({
          ...healthControllerCheckQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}