/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatUsageControllerGetMeQueryResponse } from "@/gen-backend/types/chat-usage-controller-get-me";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { chatUsageControllerGetMe } from "@/gen-backend/client/chat-usage-controller-get-me";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatUsageControllerGetMeQueryKey = () => [{ url: '/api/chat-usage/me' }] as const

export type ChatUsageControllerGetMeQueryKey = ReturnType<typeof chatUsageControllerGetMeQueryKey>

export function chatUsageControllerGetMeQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = chatUsageControllerGetMeQueryKey()
        return queryOptions<ChatUsageControllerGetMeQueryResponse, ResponseErrorConfig<Error>, ChatUsageControllerGetMeQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return chatUsageControllerGetMe({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get the authenticated user chat-usage snapshot
 * {@link /api/chat-usage/me}
 */
export function useChatUsageControllerGetMe<TData = ChatUsageControllerGetMeQueryResponse, TQueryData = ChatUsageControllerGetMeQueryResponse, TQueryKey extends QueryKey = ChatUsageControllerGetMeQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ChatUsageControllerGetMeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? chatUsageControllerGetMeQueryKey()
         

         const query = useQuery({
          ...chatUsageControllerGetMeQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}