/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceAdminControllerRejectMutationResponse, MarketplaceAdminControllerRejectPathParams } from "@/gen-backend/types/marketplace-admin-controller-reject";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { marketplaceAdminControllerReject } from "@/gen-backend/client/marketplace-admin-controller-reject";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const marketplaceAdminControllerRejectMutationKey = () => [{ url: '/api/admin/marketplace/strategies/:id/reject' }] as const

export type MarketplaceAdminControllerRejectMutationKey = ReturnType<typeof marketplaceAdminControllerRejectMutationKey>

export function marketplaceAdminControllerRejectMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = marketplaceAdminControllerRejectMutationKey()
        return mutationOptions<MarketplaceAdminControllerRejectMutationResponse, ResponseErrorConfig<Error>, {id: MarketplaceAdminControllerRejectPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return marketplaceAdminControllerReject(id, config)
          },
        })

}

/**
 * @summary Reject a PENDING strategy (409 otherwise)
 * {@link /api/admin/marketplace/strategies/:id/reject}
 */
export function useMarketplaceAdminControllerReject<TContext>(options: 
{
  mutation?: UseMutationOptions<MarketplaceAdminControllerRejectMutationResponse, ResponseErrorConfig<Error>, {id: MarketplaceAdminControllerRejectPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? marketplaceAdminControllerRejectMutationKey()

          const baseOptions = marketplaceAdminControllerRejectMutationOptions(config) as UseMutationOptions<MarketplaceAdminControllerRejectMutationResponse, ResponseErrorConfig<Error>, {id: MarketplaceAdminControllerRejectPathParams["id"]}, TContext>
          

          return useMutation<MarketplaceAdminControllerRejectMutationResponse, ResponseErrorConfig<Error>, {id: MarketplaceAdminControllerRejectPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarketplaceAdminControllerRejectMutationResponse, ResponseErrorConfig<Error>, {id: MarketplaceAdminControllerRejectPathParams["id"]}, TContext>
      
}