/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreditControllerGetMeQueryResponse } from "@/gen-backend/types/credit-controller-get-me";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { creditControllerGetMe } from "@/gen-backend/client/credit-controller-get-me";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const creditControllerGetMeSuspenseQueryKey = () => [{ url: '/api/credit/me' }] as const

export type CreditControllerGetMeSuspenseQueryKey = ReturnType<typeof creditControllerGetMeSuspenseQueryKey>

export function creditControllerGetMeSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = creditControllerGetMeSuspenseQueryKey()
        return queryOptions<CreditControllerGetMeQueryResponse, ResponseErrorConfig<Error>, CreditControllerGetMeQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return creditControllerGetMe({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get the authenticated user credit snapshot
 * {@link /api/credit/me}
 */
export function useCreditControllerGetMeSuspense<TData = CreditControllerGetMeQueryResponse, TQueryKey extends QueryKey = CreditControllerGetMeSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<CreditControllerGetMeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? creditControllerGetMeSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...creditControllerGetMeSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}