/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { accountControllerSubmitTx } from "@/gen-backend/client/account-controller-submit-tx";
import type {
  AccountControllerSubmitTxMutationRequest,
  AccountControllerSubmitTxMutationResponse,
} from "@/gen-backend/types/account-controller-submit-tx";

export const accountControllerSubmitTxMutationKey = () => [{ url: "/api/account/submit" }] as const;

export type AccountControllerSubmitTxMutationKey = ReturnType<
  typeof accountControllerSubmitTxMutationKey
>;

export function accountControllerSubmitTxMutationOptions(
  config: Partial<RequestConfig<AccountControllerSubmitTxMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = accountControllerSubmitTxMutationKey();
  return mutationOptions<
    AccountControllerSubmitTxMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AccountControllerSubmitTxMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return accountControllerSubmitTx(data, config);
    },
  });
}

/**
 * @summary Submit a signed transaction to Stellar
 * {@link /api/account/submit}
 */
export function useAccountControllerSubmitTx<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AccountControllerSubmitTxMutationResponse,
      ResponseErrorConfig<Error>,
      { data?: AccountControllerSubmitTxMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AccountControllerSubmitTxMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? accountControllerSubmitTxMutationKey();

  const baseOptions = accountControllerSubmitTxMutationOptions(config) as UseMutationOptions<
    AccountControllerSubmitTxMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AccountControllerSubmitTxMutationRequest },
    TContext
  >;

  return useMutation<
    AccountControllerSubmitTxMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AccountControllerSubmitTxMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AccountControllerSubmitTxMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AccountControllerSubmitTxMutationRequest },
    TContext
  >;
}
