/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { WelcomeRewardControllerGetFullStatusQueryResponse } from "@/gen-backend/types/welcome-reward-controller-get-full-status";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { welcomeRewardControllerGetFullStatus } from "@/gen-backend/client/welcome-reward-controller-get-full-status";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const welcomeRewardControllerGetFullStatusQueryKey = () => [{ url: '/api/welcome-reward/full-status' }] as const

export type WelcomeRewardControllerGetFullStatusQueryKey = ReturnType<typeof welcomeRewardControllerGetFullStatusQueryKey>

export function welcomeRewardControllerGetFullStatusQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = welcomeRewardControllerGetFullStatusQueryKey()
        return queryOptions<WelcomeRewardControllerGetFullStatusQueryResponse, ResponseErrorConfig<Error>, WelcomeRewardControllerGetFullStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return welcomeRewardControllerGetFullStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get aggregated user status: volume, points, chat credits
 * {@link /api/welcome-reward/full-status}
 */
export function useWelcomeRewardControllerGetFullStatus<TData = WelcomeRewardControllerGetFullStatusQueryResponse, TQueryData = WelcomeRewardControllerGetFullStatusQueryResponse, TQueryKey extends QueryKey = WelcomeRewardControllerGetFullStatusQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<WelcomeRewardControllerGetFullStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? welcomeRewardControllerGetFullStatusQueryKey()
         

         const query = useQuery({
          ...welcomeRewardControllerGetFullStatusQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}