/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceAdminControllerExportStrategiesQueryResponse, MarketplaceAdminControllerExportStrategiesQueryParams } from "@/gen-backend/types/marketplace-admin-controller-export-strategies";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { marketplaceAdminControllerExportStrategies } from "@/gen-backend/client/marketplace-admin-controller-export-strategies";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const marketplaceAdminControllerExportStrategiesQueryKey = (params?: MarketplaceAdminControllerExportStrategiesQueryParams) => [{ url: '/api/admin/marketplace/strategies/export' }, ...(params ? [params] : [])] as const

export type MarketplaceAdminControllerExportStrategiesQueryKey = ReturnType<typeof marketplaceAdminControllerExportStrategiesQueryKey>

export function marketplaceAdminControllerExportStrategiesQueryOptions(params?: MarketplaceAdminControllerExportStrategiesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceAdminControllerExportStrategiesQueryKey(params)
        return queryOptions<MarketplaceAdminControllerExportStrategiesQueryResponse, ResponseErrorConfig<Error>, MarketplaceAdminControllerExportStrategiesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceAdminControllerExportStrategies(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Export marketplace strategies as CSV
 * {@link /api/admin/marketplace/strategies/export}
 */
export function useMarketplaceAdminControllerExportStrategies<TData = MarketplaceAdminControllerExportStrategiesQueryResponse, TQueryData = MarketplaceAdminControllerExportStrategiesQueryResponse, TQueryKey extends QueryKey = MarketplaceAdminControllerExportStrategiesQueryKey>(params?: MarketplaceAdminControllerExportStrategiesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<MarketplaceAdminControllerExportStrategiesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceAdminControllerExportStrategiesQueryKey(params)
         

         const query = useQuery({
          ...marketplaceAdminControllerExportStrategiesQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}