/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { creditControllerGetMe } from "@/gen-backend/client/credit-controller-get-me";
import type { CreditControllerGetMeQueryResponse } from "@/gen-backend/types/credit-controller-get-me";

export const creditControllerGetMeQueryKey = () => [{ url: "/api/credit/me" }] as const;

export type CreditControllerGetMeQueryKey = ReturnType<typeof creditControllerGetMeQueryKey>;

export function creditControllerGetMeQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = creditControllerGetMeQueryKey();
  return queryOptions<
    CreditControllerGetMeQueryResponse,
    ResponseErrorConfig<Error>,
    CreditControllerGetMeQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return creditControllerGetMe(config);
    },
  });
}

/**
 * @summary Get the authenticated user credit snapshot
 * {@link /api/credit/me}
 */
export function useCreditControllerGetMe<
  TData = CreditControllerGetMeQueryResponse,
  TQueryData = CreditControllerGetMeQueryResponse,
  TQueryKey extends QueryKey = CreditControllerGetMeQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        CreditControllerGetMeQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? creditControllerGetMeQueryKey();

  const query = useQuery(
    {
      ...creditControllerGetMeQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
