/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountControllerGetTradingAccountQueryResponse } from "@/gen-backend/types/account-controller-get-trading-account";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { accountControllerGetTradingAccount } from "@/gen-backend/client/account-controller-get-trading-account";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountControllerGetTradingAccountSuspenseQueryKey = () => [{ url: '/api/account/trading-account' }] as const

export type AccountControllerGetTradingAccountSuspenseQueryKey = ReturnType<typeof accountControllerGetTradingAccountSuspenseQueryKey>

export function accountControllerGetTradingAccountSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = accountControllerGetTradingAccountSuspenseQueryKey()
        return queryOptions<AccountControllerGetTradingAccountQueryResponse, ResponseErrorConfig<Error>, AccountControllerGetTradingAccountQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return accountControllerGetTradingAccount({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Check if user has a TRADING KeeperWallet
 * {@link /api/account/trading-account}
 */
export function useAccountControllerGetTradingAccountSuspense<TData = AccountControllerGetTradingAccountQueryResponse, TQueryKey extends QueryKey = AccountControllerGetTradingAccountSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountControllerGetTradingAccountQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? accountControllerGetTradingAccountSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...accountControllerGetTradingAccountSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}