/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { waitlistControllerRegisterWallet } from "@/gen-backend/client/waitlist-controller-register-wallet";
import type {
  WaitlistControllerRegisterWalletMutationRequest,
  WaitlistControllerRegisterWalletMutationResponse,
} from "@/gen-backend/types/waitlist-controller-register-wallet";

export const waitlistControllerRegisterWalletMutationKey = () =>
  [{ url: "/api/waitlist/register-wallet" }] as const;

export type WaitlistControllerRegisterWalletMutationKey = ReturnType<
  typeof waitlistControllerRegisterWalletMutationKey
>;

export function waitlistControllerRegisterWalletMutationOptions(
  config: Partial<RequestConfig<WaitlistControllerRegisterWalletMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = waitlistControllerRegisterWalletMutationKey();
  return mutationOptions<
    WaitlistControllerRegisterWalletMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WaitlistControllerRegisterWalletMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return waitlistControllerRegisterWallet(data, config);
    },
  });
}

/**
 * @summary Register wallet with signed challenge
 * {@link /api/waitlist/register-wallet}
 */
export function useWaitlistControllerRegisterWallet<TContext>(
  options: {
    mutation?: UseMutationOptions<
      WaitlistControllerRegisterWalletMutationResponse,
      ResponseErrorConfig<Error>,
      { data: WaitlistControllerRegisterWalletMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<WaitlistControllerRegisterWalletMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? waitlistControllerRegisterWalletMutationKey();

  const baseOptions = waitlistControllerRegisterWalletMutationOptions(config) as UseMutationOptions<
    WaitlistControllerRegisterWalletMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WaitlistControllerRegisterWalletMutationRequest },
    TContext
  >;

  return useMutation<
    WaitlistControllerRegisterWalletMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WaitlistControllerRegisterWalletMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    WaitlistControllerRegisterWalletMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WaitlistControllerRegisterWalletMutationRequest },
    TContext
  >;
}
