/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceAdminControllerListPublishersQueryResponse } from "@/gen-backend/types/marketplace-admin-controller-list-publishers";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { marketplaceAdminControllerListPublishers } from "@/gen-backend/client/marketplace-admin-controller-list-publishers";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const marketplaceAdminControllerListPublishersSuspenseQueryKey = () => [{ url: '/api/admin/marketplace/publishers' }] as const

export type MarketplaceAdminControllerListPublishersSuspenseQueryKey = ReturnType<typeof marketplaceAdminControllerListPublishersSuspenseQueryKey>

export function marketplaceAdminControllerListPublishersSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceAdminControllerListPublishersSuspenseQueryKey()
        return queryOptions<MarketplaceAdminControllerListPublishersQueryResponse, ResponseErrorConfig<Error>, MarketplaceAdminControllerListPublishersQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceAdminControllerListPublishers({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Strategy publishers with strategy counts
 * {@link /api/admin/marketplace/publishers}
 */
export function useMarketplaceAdminControllerListPublishersSuspense<TData = MarketplaceAdminControllerListPublishersQueryResponse, TQueryKey extends QueryKey = MarketplaceAdminControllerListPublishersSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<MarketplaceAdminControllerListPublishersQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceAdminControllerListPublishersSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...marketplaceAdminControllerListPublishersSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}