/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AppControllerGetHelloQueryResponse } from "@/gen-backend/types/app-controller-get-hello";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { appControllerGetHello } from "@/gen-backend/client/app-controller-get-hello";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const appControllerGetHelloQueryKey = () => [{ url: '/api' }] as const

export type AppControllerGetHelloQueryKey = ReturnType<typeof appControllerGetHelloQueryKey>

export function appControllerGetHelloQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = appControllerGetHelloQueryKey()
        return queryOptions<AppControllerGetHelloQueryResponse, ResponseErrorConfig<Error>, AppControllerGetHelloQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return appControllerGetHello({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api}
 */
export function useAppControllerGetHello<TData = AppControllerGetHelloQueryResponse, TQueryData = AppControllerGetHelloQueryResponse, TQueryKey extends QueryKey = AppControllerGetHelloQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AppControllerGetHelloQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? appControllerGetHelloQueryKey()
         

         const query = useQuery({
          ...appControllerGetHelloQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}