/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PortfolioControllerRegisterAddressMutationRequest, PortfolioControllerRegisterAddressMutationResponse } from "@/gen-backend/types/portfolio-controller-register-address";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { portfolioControllerRegisterAddress } from "@/gen-backend/client/portfolio-controller-register-address";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const portfolioControllerRegisterAddressMutationKey = () => [{ url: '/api/portfolio/snapshot' }] as const

export type PortfolioControllerRegisterAddressMutationKey = ReturnType<typeof portfolioControllerRegisterAddressMutationKey>

export function portfolioControllerRegisterAddressMutationOptions(config: Partial<RequestConfig<PortfolioControllerRegisterAddressMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = portfolioControllerRegisterAddressMutationKey()
  return mutationOptions<PortfolioControllerRegisterAddressMutationResponse, ResponseErrorConfig<Error>, {data: PortfolioControllerRegisterAddressMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return portfolioControllerRegisterAddress(data, config)
    },
  })
}

/**
 * @summary Register a wallet address for portfolio tracking
 * {@link /api/portfolio/snapshot}
 */
export function usePortfolioControllerRegisterAddress<TContext>(options: 
{
  mutation?: UseMutationOptions<PortfolioControllerRegisterAddressMutationResponse, ResponseErrorConfig<Error>, {data: PortfolioControllerRegisterAddressMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PortfolioControllerRegisterAddressMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? portfolioControllerRegisterAddressMutationKey()

  const baseOptions = portfolioControllerRegisterAddressMutationOptions(config) as UseMutationOptions<PortfolioControllerRegisterAddressMutationResponse, ResponseErrorConfig<Error>, {data: PortfolioControllerRegisterAddressMutationRequest}, TContext>

  return useMutation<PortfolioControllerRegisterAddressMutationResponse, ResponseErrorConfig<Error>, {data: PortfolioControllerRegisterAddressMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PortfolioControllerRegisterAddressMutationResponse, ResponseErrorConfig<Error>, {data: PortfolioControllerRegisterAddressMutationRequest}, TContext>
}