/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SponsorAdminControllerExportLogsQueryResponse } from "@/gen-backend/types/sponsor-admin-controller-export-logs";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { sponsorAdminControllerExportLogs } from "@/gen-backend/client/sponsor-admin-controller-export-logs";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const sponsorAdminControllerExportLogsQueryKey = () => [{ url: '/api/admin/sponsor/logs/export' }] as const

export type SponsorAdminControllerExportLogsQueryKey = ReturnType<typeof sponsorAdminControllerExportLogsQueryKey>

export function sponsorAdminControllerExportLogsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = sponsorAdminControllerExportLogsQueryKey()
        return queryOptions<SponsorAdminControllerExportLogsQueryResponse, ResponseErrorConfig<Error>, SponsorAdminControllerExportLogsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return sponsorAdminControllerExportLogs({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Export all sponsor transaction logs as CSV
 * {@link /api/admin/sponsor/logs/export}
 */
export function useSponsorAdminControllerExportLogs<TData = SponsorAdminControllerExportLogsQueryResponse, TQueryData = SponsorAdminControllerExportLogsQueryResponse, TQueryKey extends QueryKey = SponsorAdminControllerExportLogsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<SponsorAdminControllerExportLogsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? sponsorAdminControllerExportLogsQueryKey()
         

         const query = useQuery({
          ...sponsorAdminControllerExportLogsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}