/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { rebalanceControllerHalt } from "@/gen-backend/client/rebalance-controller-halt";
import type { RebalanceControllerHaltMutationResponse } from "@/gen-backend/types/rebalance-controller-halt";

export const rebalanceControllerHaltMutationKey = () => [{ url: "/api/rebalance/halt" }] as const;

export type RebalanceControllerHaltMutationKey = ReturnType<
  typeof rebalanceControllerHaltMutationKey
>;

export function rebalanceControllerHaltMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const mutationKey = rebalanceControllerHaltMutationKey();
  return mutationOptions<
    RebalanceControllerHaltMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async () => {
      return rebalanceControllerHalt(config);
    },
  });
}

/**
 * @summary Manually halt the rebalance bot
 * {@link /api/rebalance/halt}
 */
export function useRebalanceControllerHalt<TContext>(
  options: {
    mutation?: UseMutationOptions<
      RebalanceControllerHaltMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? rebalanceControllerHaltMutationKey();

  const baseOptions = rebalanceControllerHaltMutationOptions(config) as UseMutationOptions<
    RebalanceControllerHaltMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;

  return useMutation<
    RebalanceControllerHaltMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    RebalanceControllerHaltMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;
}
