/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerGetGiftRecipientsQueryResponse, AdminControllerGetGiftRecipientsPathParams, AdminControllerGetGiftRecipientsQueryParams } from "@/gen-backend/types/admin-controller-get-gift-recipients";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminControllerGetGiftRecipients } from "@/gen-backend/client/admin-controller-get-gift-recipients";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminControllerGetGiftRecipientsSuspenseQueryKey = (id: AdminControllerGetGiftRecipientsPathParams["id"] | undefined, params?: AdminControllerGetGiftRecipientsQueryParams) => [{ url: '/api/admin/quest-gifts/:id/recipients', params: {id:id} }, ...(params ? [params] : [])] as const

export type AdminControllerGetGiftRecipientsSuspenseQueryKey = ReturnType<typeof adminControllerGetGiftRecipientsSuspenseQueryKey>

export function adminControllerGetGiftRecipientsSuspenseQueryOptions(id: AdminControllerGetGiftRecipientsPathParams["id"] | undefined, params?: AdminControllerGetGiftRecipientsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerGetGiftRecipientsSuspenseQueryKey(id, params)
        return queryOptions<AdminControllerGetGiftRecipientsQueryResponse, ResponseErrorConfig<Error>, AdminControllerGetGiftRecipientsQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerGetGiftRecipients(id!, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Paged recipient/payout table for a gift
 * {@link /api/admin/quest-gifts/:id/recipients}
 */
export function useAdminControllerGetGiftRecipientsSuspense<TData = AdminControllerGetGiftRecipientsQueryResponse, TQueryKey extends QueryKey = AdminControllerGetGiftRecipientsSuspenseQueryKey>(id: AdminControllerGetGiftRecipientsPathParams["id"] | undefined, params?: AdminControllerGetGiftRecipientsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminControllerGetGiftRecipientsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerGetGiftRecipientsSuspenseQueryKey(id, params)
         

         const query = useSuspenseQuery({
          ...adminControllerGetGiftRecipientsSuspenseQueryOptions(id, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}