/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { WelcomeRewardControllerMarkSeenMutationResponse } from "@/gen-backend/types/welcome-reward-controller-mark-seen";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { welcomeRewardControllerMarkSeen } from "@/gen-backend/client/welcome-reward-controller-mark-seen";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const welcomeRewardControllerMarkSeenMutationKey = () => [{ url: '/api/welcome-reward/seen' }] as const

export type WelcomeRewardControllerMarkSeenMutationKey = ReturnType<typeof welcomeRewardControllerMarkSeenMutationKey>

export function welcomeRewardControllerMarkSeenMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = welcomeRewardControllerMarkSeenMutationKey()
        return mutationOptions<WelcomeRewardControllerMarkSeenMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return welcomeRewardControllerMarkSeen(config)
          },
        })

}

/**
 * @summary Mark the welcome reward card as seen
 * {@link /api/welcome-reward/seen}
 */
export function useWelcomeRewardControllerMarkSeen<TContext>(options: 
{
  mutation?: UseMutationOptions<WelcomeRewardControllerMarkSeenMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? welcomeRewardControllerMarkSeenMutationKey()

          const baseOptions = welcomeRewardControllerMarkSeenMutationOptions(config) as UseMutationOptions<WelcomeRewardControllerMarkSeenMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<WelcomeRewardControllerMarkSeenMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<WelcomeRewardControllerMarkSeenMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}