/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceControllerGetStrategyPerformanceQueryResponse, MarketplaceControllerGetStrategyPerformancePathParams } from "@/gen-backend/types/marketplace-controller-get-strategy-performance";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { marketplaceControllerGetStrategyPerformance } from "@/gen-backend/client/marketplace-controller-get-strategy-performance";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const marketplaceControllerGetStrategyPerformanceQueryKey = (id: MarketplaceControllerGetStrategyPerformancePathParams["id"] | undefined) => [{ url: '/api/marketplace/strategies/:id/performance', params: {id:id} }] as const

export type MarketplaceControllerGetStrategyPerformanceQueryKey = ReturnType<typeof marketplaceControllerGetStrategyPerformanceQueryKey>

export function marketplaceControllerGetStrategyPerformanceQueryOptions(id: MarketplaceControllerGetStrategyPerformancePathParams["id"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceControllerGetStrategyPerformanceQueryKey(id)
        return queryOptions<MarketplaceControllerGetStrategyPerformanceQueryResponse, ResponseErrorConfig<Error>, MarketplaceControllerGetStrategyPerformanceQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceControllerGetStrategyPerformance(id!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get strategy performance history for charts
 * {@link /api/marketplace/strategies/:id/performance}
 */
export function useMarketplaceControllerGetStrategyPerformance<TData = MarketplaceControllerGetStrategyPerformanceQueryResponse, TQueryData = MarketplaceControllerGetStrategyPerformanceQueryResponse, TQueryKey extends QueryKey = MarketplaceControllerGetStrategyPerformanceQueryKey>(id: MarketplaceControllerGetStrategyPerformancePathParams["id"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<MarketplaceControllerGetStrategyPerformanceQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceControllerGetStrategyPerformanceQueryKey(id)
         

         const query = useQuery({
          ...marketplaceControllerGetStrategyPerformanceQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}