/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthControllerVerifyMutationRequest, AuthControllerVerifyMutationResponse } from "@/gen-backend/types/auth-controller-verify";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authControllerVerify } from "@/gen-backend/client/auth-controller-verify";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authControllerVerifyMutationKey = () => [{ url: '/api/auth/verify' }] as const

export type AuthControllerVerifyMutationKey = ReturnType<typeof authControllerVerifyMutationKey>

export function authControllerVerifyMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AuthControllerVerifyMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = authControllerVerifyMutationKey()
        return mutationOptions<AuthControllerVerifyMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerVerifyMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return authControllerVerify(data, config)
          },
        })

}

/**
 * @summary Verify signed challenge and authenticate with Stellar wallet
 * {@link /api/auth/verify}
 */
export function useAuthControllerVerify<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthControllerVerifyMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerVerifyMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthControllerVerifyMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? authControllerVerifyMutationKey()

          const baseOptions = authControllerVerifyMutationOptions(config) as UseMutationOptions<AuthControllerVerifyMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerVerifyMutationRequest}, TContext>
          

          return useMutation<AuthControllerVerifyMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerVerifyMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AuthControllerVerifyMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerVerifyMutationRequest}, TContext>
      
}