/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerListGiftsQueryResponse } from "@/gen-backend/types/admin-controller-list-gifts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminControllerListGifts } from "@/gen-backend/client/admin-controller-list-gifts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminControllerListGiftsQueryKey = () => [{ url: '/api/admin/quest-gifts' }] as const

export type AdminControllerListGiftsQueryKey = ReturnType<typeof adminControllerListGiftsQueryKey>

export function adminControllerListGiftsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerListGiftsQueryKey()
        return queryOptions<AdminControllerListGiftsQueryResponse, ResponseErrorConfig<Error>, AdminControllerListGiftsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerListGifts({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List gifts with recipient counts and totals
 * {@link /api/admin/quest-gifts}
 */
export function useAdminControllerListGifts<TData = AdminControllerListGiftsQueryResponse, TQueryData = AdminControllerListGiftsQueryResponse, TQueryKey extends QueryKey = AdminControllerListGiftsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AdminControllerListGiftsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerListGiftsQueryKey()
         

         const query = useQuery({
          ...adminControllerListGiftsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}