/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceControllerGetLeaderboardQueryResponse, MarketplaceControllerGetLeaderboardQueryParams } from "@/gen-backend/types/marketplace-controller-get-leaderboard";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { marketplaceControllerGetLeaderboard } from "@/gen-backend/client/marketplace-controller-get-leaderboard";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const marketplaceControllerGetLeaderboardSuspenseQueryKey = (params: MarketplaceControllerGetLeaderboardQueryParams) => [{ url: '/api/marketplace/leaderboard' }, ...(params ? [params] : [])] as const

export type MarketplaceControllerGetLeaderboardSuspenseQueryKey = ReturnType<typeof marketplaceControllerGetLeaderboardSuspenseQueryKey>

export function marketplaceControllerGetLeaderboardSuspenseQueryOptions(params: MarketplaceControllerGetLeaderboardQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceControllerGetLeaderboardSuspenseQueryKey(params)
        return queryOptions<MarketplaceControllerGetLeaderboardQueryResponse, ResponseErrorConfig<Error>, MarketplaceControllerGetLeaderboardQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceControllerGetLeaderboard(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Strategy performance leaderboard
 * {@link /api/marketplace/leaderboard}
 */
export function useMarketplaceControllerGetLeaderboardSuspense<TData = MarketplaceControllerGetLeaderboardQueryResponse, TQueryKey extends QueryKey = MarketplaceControllerGetLeaderboardSuspenseQueryKey>(params: MarketplaceControllerGetLeaderboardQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<MarketplaceControllerGetLeaderboardQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceControllerGetLeaderboardSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...marketplaceControllerGetLeaderboardSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}