/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { adminControllerListCodes } from "@/gen-backend/client/admin-controller-list-codes";
import type {
  AdminControllerListCodesQueryParams,
  AdminControllerListCodesQueryResponse,
} from "@/gen-backend/types/admin-controller-list-codes";

export const adminControllerListCodesQueryKey = (params?: AdminControllerListCodesQueryParams) =>
  [{ url: "/api/admin/codes" }, ...(params ? [params] : [])] as const;

export type AdminControllerListCodesQueryKey = ReturnType<typeof adminControllerListCodesQueryKey>;

export function adminControllerListCodesQueryOptions(
  params?: AdminControllerListCodesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = adminControllerListCodesQueryKey(params);
  return queryOptions<
    AdminControllerListCodesQueryResponse,
    ResponseErrorConfig<Error>,
    AdminControllerListCodesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return adminControllerListCodes(params, config);
    },
  });
}

/**
 * @summary List EARLY_ACCESS codes (paginated, 50/page)
 * {@link /api/admin/codes}
 */
export function useAdminControllerListCodes<
  TData = AdminControllerListCodesQueryResponse,
  TQueryData = AdminControllerListCodesQueryResponse,
  TQueryKey extends QueryKey = AdminControllerListCodesQueryKey,
>(
  params?: AdminControllerListCodesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        AdminControllerListCodesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? adminControllerListCodesQueryKey(params);

  const query = useQuery(
    {
      ...adminControllerListCodesQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
