/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerGetWalletsQueryResponse, AdminControllerGetWalletsQueryParams } from "@/gen-backend/types/admin-controller-get-wallets";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminControllerGetWallets } from "@/gen-backend/client/admin-controller-get-wallets";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminControllerGetWalletsQueryKey = (params?: AdminControllerGetWalletsQueryParams) => [{ url: '/api/admin/analytics/wallets' }, ...(params ? [params] : [])] as const

export type AdminControllerGetWalletsQueryKey = ReturnType<typeof adminControllerGetWalletsQueryKey>

export function adminControllerGetWalletsQueryOptions(params?: AdminControllerGetWalletsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerGetWalletsQueryKey(params)
        return queryOptions<AdminControllerGetWalletsQueryResponse, ResponseErrorConfig<Error>, AdminControllerGetWalletsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerGetWallets(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Trade-volume keeper-wallet table for the analytics page
 * {@link /api/admin/analytics/wallets}
 */
export function useAdminControllerGetWallets<TData = AdminControllerGetWalletsQueryResponse, TQueryData = AdminControllerGetWalletsQueryResponse, TQueryKey extends QueryKey = AdminControllerGetWalletsQueryKey>(params?: AdminControllerGetWalletsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<AdminControllerGetWalletsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerGetWalletsQueryKey(params)
         

         const query = useQuery({
          ...adminControllerGetWalletsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}