/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerAddQuestTaskMutationRequest, AdminControllerAddQuestTaskMutationResponse, AdminControllerAddQuestTaskPathParams } from "@/gen-backend/types/admin-controller-add-quest-task";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminControllerAddQuestTask } from "@/gen-backend/client/admin-controller-add-quest-task";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminControllerAddQuestTaskMutationKey = () => [{ url: '/api/admin/quest-campaigns/:id/tasks' }] as const

export type AdminControllerAddQuestTaskMutationKey = ReturnType<typeof adminControllerAddQuestTaskMutationKey>

export function adminControllerAddQuestTaskMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminControllerAddQuestTaskMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminControllerAddQuestTaskMutationKey()
        return mutationOptions<AdminControllerAddQuestTaskMutationResponse, ResponseErrorConfig<Error>, {id: AdminControllerAddQuestTaskPathParams["id"], data: AdminControllerAddQuestTaskMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return adminControllerAddQuestTask(id, data, config)
          },
        })

}

/**
 * @summary Add task to quest campaign
 * {@link /api/admin/quest-campaigns/:id/tasks}
 */
export function useAdminControllerAddQuestTask<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminControllerAddQuestTaskMutationResponse, ResponseErrorConfig<Error>, {id: AdminControllerAddQuestTaskPathParams["id"], data: AdminControllerAddQuestTaskMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminControllerAddQuestTaskMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminControllerAddQuestTaskMutationKey()

          const baseOptions = adminControllerAddQuestTaskMutationOptions(config) as UseMutationOptions<AdminControllerAddQuestTaskMutationResponse, ResponseErrorConfig<Error>, {id: AdminControllerAddQuestTaskPathParams["id"], data: AdminControllerAddQuestTaskMutationRequest}, TContext>
          

          return useMutation<AdminControllerAddQuestTaskMutationResponse, ResponseErrorConfig<Error>, {id: AdminControllerAddQuestTaskPathParams["id"], data: AdminControllerAddQuestTaskMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminControllerAddQuestTaskMutationResponse, ResponseErrorConfig<Error>, {id: AdminControllerAddQuestTaskPathParams["id"], data: AdminControllerAddQuestTaskMutationRequest}, TContext>
      
}