/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerDeleteReferralUserOverrideMutationResponse, AdminControllerDeleteReferralUserOverridePathParams } from "@/gen-backend/types/admin-controller-delete-referral-user-override";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminControllerDeleteReferralUserOverride } from "@/gen-backend/client/admin-controller-delete-referral-user-override";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminControllerDeleteReferralUserOverrideMutationKey = () => [{ url: '/api/admin/quest-referral/users/:userId/override/:layer' }] as const

export type AdminControllerDeleteReferralUserOverrideMutationKey = ReturnType<typeof adminControllerDeleteReferralUserOverrideMutationKey>

export function adminControllerDeleteReferralUserOverrideMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = adminControllerDeleteReferralUserOverrideMutationKey()
        return mutationOptions<AdminControllerDeleteReferralUserOverrideMutationResponse, ResponseErrorConfig<Error>, {userId: AdminControllerDeleteReferralUserOverridePathParams["userId"], layer: AdminControllerDeleteReferralUserOverridePathParams["layer"]}, TContext>({
          mutationKey,
          mutationFn: async({ userId, layer }) => {
            return adminControllerDeleteReferralUserOverride(userId, layer, config)
          },
        })

}

/**
 * @summary Delete a single per-user referral rate override
 * {@link /api/admin/quest-referral/users/:userId/override/:layer}
 */
export function useAdminControllerDeleteReferralUserOverride<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminControllerDeleteReferralUserOverrideMutationResponse, ResponseErrorConfig<Error>, {userId: AdminControllerDeleteReferralUserOverridePathParams["userId"], layer: AdminControllerDeleteReferralUserOverridePathParams["layer"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminControllerDeleteReferralUserOverrideMutationKey()

          const baseOptions = adminControllerDeleteReferralUserOverrideMutationOptions(config) as UseMutationOptions<AdminControllerDeleteReferralUserOverrideMutationResponse, ResponseErrorConfig<Error>, {userId: AdminControllerDeleteReferralUserOverridePathParams["userId"], layer: AdminControllerDeleteReferralUserOverridePathParams["layer"]}, TContext>
          

          return useMutation<AdminControllerDeleteReferralUserOverrideMutationResponse, ResponseErrorConfig<Error>, {userId: AdminControllerDeleteReferralUserOverridePathParams["userId"], layer: AdminControllerDeleteReferralUserOverridePathParams["layer"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminControllerDeleteReferralUserOverrideMutationResponse, ResponseErrorConfig<Error>, {userId: AdminControllerDeleteReferralUserOverridePathParams["userId"], layer: AdminControllerDeleteReferralUserOverridePathParams["layer"]}, TContext>
      
}