/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsersControllerSetReferralCodeMutationResponse } from "@/gen-backend/types/users-controller-set-referral-code";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { usersControllerSetReferralCode } from "@/gen-backend/client/users-controller-set-referral-code";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const usersControllerSetReferralCodeMutationKey = () => [{ url: '/api/quest/users/me/referral-code' }] as const

export type UsersControllerSetReferralCodeMutationKey = ReturnType<typeof usersControllerSetReferralCodeMutationKey>

export function usersControllerSetReferralCodeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = usersControllerSetReferralCodeMutationKey()
        return mutationOptions<UsersControllerSetReferralCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return usersControllerSetReferralCode(config)
          },
        })

}

/**
 * {@link /api/quest/users/me/referral-code}
 */
export function useUsersControllerSetReferralCode<TContext>(options: 
{
  mutation?: UseMutationOptions<UsersControllerSetReferralCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? usersControllerSetReferralCodeMutationKey()

          const baseOptions = usersControllerSetReferralCodeMutationOptions(config) as UseMutationOptions<UsersControllerSetReferralCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<UsersControllerSetReferralCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UsersControllerSetReferralCodeMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}