/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerCreateFomoEventMutationRequest, AdminControllerCreateFomoEventMutationResponse } from "@/gen-backend/types/admin-controller-create-fomo-event";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminControllerCreateFomoEvent } from "@/gen-backend/client/admin-controller-create-fomo-event";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminControllerCreateFomoEventMutationKey = () => [{ url: '/api/admin/quest-fomo' }] as const

export type AdminControllerCreateFomoEventMutationKey = ReturnType<typeof adminControllerCreateFomoEventMutationKey>

export function adminControllerCreateFomoEventMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminControllerCreateFomoEventMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminControllerCreateFomoEventMutationKey()
        return mutationOptions<AdminControllerCreateFomoEventMutationResponse, ResponseErrorConfig<Error>, {data: AdminControllerCreateFomoEventMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return adminControllerCreateFomoEvent(data, config)
          },
        })

}

/**
 * @summary Create a FOMO event
 * {@link /api/admin/quest-fomo}
 */
export function useAdminControllerCreateFomoEvent<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminControllerCreateFomoEventMutationResponse, ResponseErrorConfig<Error>, {data: AdminControllerCreateFomoEventMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminControllerCreateFomoEventMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminControllerCreateFomoEventMutationKey()

          const baseOptions = adminControllerCreateFomoEventMutationOptions(config) as UseMutationOptions<AdminControllerCreateFomoEventMutationResponse, ResponseErrorConfig<Error>, {data: AdminControllerCreateFomoEventMutationRequest}, TContext>
          

          return useMutation<AdminControllerCreateFomoEventMutationResponse, ResponseErrorConfig<Error>, {data: AdminControllerCreateFomoEventMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminControllerCreateFomoEventMutationResponse, ResponseErrorConfig<Error>, {data: AdminControllerCreateFomoEventMutationRequest}, TContext>
      
}