/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { accountControllerResumeAccount } from "@/gen-backend/client/account-controller-resume-account";
import type {
  AccountControllerResumeAccountMutationResponse,
  AccountControllerResumeAccountPathParams,
} from "@/gen-backend/types/account-controller-resume-account";

export const accountControllerResumeAccountMutationKey = () =>
  [{ url: "/api/account/resume/:publicKey" }] as const;

export type AccountControllerResumeAccountMutationKey = ReturnType<
  typeof accountControllerResumeAccountMutationKey
>;

export function accountControllerResumeAccountMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const mutationKey = accountControllerResumeAccountMutationKey();
  return mutationOptions<
    AccountControllerResumeAccountMutationResponse,
    ResponseErrorConfig<Error>,
    { publicKey: AccountControllerResumeAccountPathParams["publicKey"] },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ publicKey }) => {
      return accountControllerResumeAccount(publicKey, config);
    },
  });
}

/**
 * @summary Reset failure counters on a managed account
 * {@link /api/account/resume/:publicKey}
 */
export function useAccountControllerResumeAccount<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AccountControllerResumeAccountMutationResponse,
      ResponseErrorConfig<Error>,
      { publicKey: AccountControllerResumeAccountPathParams["publicKey"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? accountControllerResumeAccountMutationKey();

  const baseOptions = accountControllerResumeAccountMutationOptions(config) as UseMutationOptions<
    AccountControllerResumeAccountMutationResponse,
    ResponseErrorConfig<Error>,
    { publicKey: AccountControllerResumeAccountPathParams["publicKey"] },
    TContext
  >;

  return useMutation<
    AccountControllerResumeAccountMutationResponse,
    ResponseErrorConfig<Error>,
    { publicKey: AccountControllerResumeAccountPathParams["publicKey"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AccountControllerResumeAccountMutationResponse,
    ResponseErrorConfig<Error>,
    { publicKey: AccountControllerResumeAccountPathParams["publicKey"] },
    TContext
  >;
}
