/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SettingsAdminControllerGetSettingsQueryResponse } from "@/gen-backend/types/settings-admin-controller-get-settings";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { settingsAdminControllerGetSettings } from "@/gen-backend/client/settings-admin-controller-get-settings";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const settingsAdminControllerGetSettingsSuspenseQueryKey = () => [{ url: '/api/admin/settings' }] as const

export type SettingsAdminControllerGetSettingsSuspenseQueryKey = ReturnType<typeof settingsAdminControllerGetSettingsSuspenseQueryKey>

export function settingsAdminControllerGetSettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = settingsAdminControllerGetSettingsSuspenseQueryKey()
        return queryOptions<SettingsAdminControllerGetSettingsQueryResponse, ResponseErrorConfig<Error>, SettingsAdminControllerGetSettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return settingsAdminControllerGetSettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/admin/settings}
 */
export function useSettingsAdminControllerGetSettingsSuspense<TData = SettingsAdminControllerGetSettingsQueryResponse, TQueryKey extends QueryKey = SettingsAdminControllerGetSettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<SettingsAdminControllerGetSettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? settingsAdminControllerGetSettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...settingsAdminControllerGetSettingsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}