/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PublicControllerGetTractionQueryResponse, PublicControllerGetTraction503 } from "@/gen-backend/types/public-controller-get-traction";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { publicControllerGetTraction } from "@/gen-backend/client/public-controller-get-traction";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const publicControllerGetTractionQueryKey = () => [{ url: '/api/public/traction' }] as const

export type PublicControllerGetTractionQueryKey = ReturnType<typeof publicControllerGetTractionQueryKey>

export function publicControllerGetTractionQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = publicControllerGetTractionQueryKey()
        return queryOptions<PublicControllerGetTractionQueryResponse, ResponseErrorConfig<PublicControllerGetTraction503>, PublicControllerGetTractionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return publicControllerGetTraction({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get public traction metrics (KPIs + 90-day growth series)
 * {@link /api/public/traction}
 */
export function usePublicControllerGetTraction<TData = PublicControllerGetTractionQueryResponse, TQueryData = PublicControllerGetTractionQueryResponse, TQueryKey extends QueryKey = PublicControllerGetTractionQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<PublicControllerGetTractionQueryResponse, ResponseErrorConfig<PublicControllerGetTraction503>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? publicControllerGetTractionQueryKey()
         

         const query = useQuery({
          ...publicControllerGetTractionQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<PublicControllerGetTraction503>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}