/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerListCodesQueryResponse, AdminControllerListCodesQueryParams } from "@/gen-backend/types/admin-controller-list-codes";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminControllerListCodes } from "@/gen-backend/client/admin-controller-list-codes";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminControllerListCodesSuspenseQueryKey = (params?: AdminControllerListCodesQueryParams) => [{ url: '/api/admin/codes' }, ...(params ? [params] : [])] as const

export type AdminControllerListCodesSuspenseQueryKey = ReturnType<typeof adminControllerListCodesSuspenseQueryKey>

export function adminControllerListCodesSuspenseQueryOptions(params?: AdminControllerListCodesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerListCodesSuspenseQueryKey(params)
        return queryOptions<AdminControllerListCodesQueryResponse, ResponseErrorConfig<Error>, AdminControllerListCodesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerListCodes(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List EARLY_ACCESS codes (paginated, 50/page)
 * {@link /api/admin/codes}
 */
export function useAdminControllerListCodesSuspense<TData = AdminControllerListCodesQueryResponse, TQueryKey extends QueryKey = AdminControllerListCodesSuspenseQueryKey>(params?: AdminControllerListCodesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminControllerListCodesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerListCodesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...adminControllerListCodesSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}