/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerGetQuestStatsQueryResponse } from "@/gen-backend/types/admin-controller-get-quest-stats";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminControllerGetQuestStats } from "@/gen-backend/client/admin-controller-get-quest-stats";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminControllerGetQuestStatsSuspenseQueryKey = () => [{ url: '/api/admin/quest-stats' }] as const

export type AdminControllerGetQuestStatsSuspenseQueryKey = ReturnType<typeof adminControllerGetQuestStatsSuspenseQueryKey>

export function adminControllerGetQuestStatsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerGetQuestStatsSuspenseQueryKey()
        return queryOptions<AdminControllerGetQuestStatsQueryResponse, ResponseErrorConfig<Error>, AdminControllerGetQuestStatsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerGetQuestStats({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get quest statistics
 * {@link /api/admin/quest-stats}
 */
export function useAdminControllerGetQuestStatsSuspense<TData = AdminControllerGetQuestStatsQueryResponse, TQueryKey extends QueryKey = AdminControllerGetQuestStatsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminControllerGetQuestStatsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerGetQuestStatsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...adminControllerGetQuestStatsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}