/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AccountControllerBuildReactivateTxsMutationRequest, AccountControllerBuildReactivateTxsMutationResponse } from "@/gen-backend/types/account-controller-build-reactivate-txs";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { accountControllerBuildReactivateTxs } from "@/gen-backend/client/account-controller-build-reactivate-txs";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const accountControllerBuildReactivateTxsMutationKey = () => [{ url: '/api/account/reactivate' }] as const

export type AccountControllerBuildReactivateTxsMutationKey = ReturnType<typeof accountControllerBuildReactivateTxsMutationKey>

export function accountControllerBuildReactivateTxsMutationOptions(config: Partial<RequestConfig<AccountControllerBuildReactivateTxsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = accountControllerBuildReactivateTxsMutationKey()
  return mutationOptions<AccountControllerBuildReactivateTxsMutationResponse, ResponseErrorConfig<Error>, {data?: AccountControllerBuildReactivateTxsMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return accountControllerBuildReactivateTxs(data, config)
    },
  })
}

/**
 * @summary Build unsigned TXs to re-register a session key for a revoked or paused account
 * {@link /api/account/reactivate}
 */
export function useAccountControllerBuildReactivateTxs<TContext>(options: 
{
  mutation?: UseMutationOptions<AccountControllerBuildReactivateTxsMutationResponse, ResponseErrorConfig<Error>, {data?: AccountControllerBuildReactivateTxsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountControllerBuildReactivateTxsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? accountControllerBuildReactivateTxsMutationKey()

  const baseOptions = accountControllerBuildReactivateTxsMutationOptions(config) as UseMutationOptions<AccountControllerBuildReactivateTxsMutationResponse, ResponseErrorConfig<Error>, {data?: AccountControllerBuildReactivateTxsMutationRequest}, TContext>

  return useMutation<AccountControllerBuildReactivateTxsMutationResponse, ResponseErrorConfig<Error>, {data?: AccountControllerBuildReactivateTxsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AccountControllerBuildReactivateTxsMutationResponse, ResponseErrorConfig<Error>, {data?: AccountControllerBuildReactivateTxsMutationRequest}, TContext>
}