/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { accountControllerBuildWithdrawTx } from "@/gen-backend/client/account-controller-build-withdraw-tx";
import type {
  AccountControllerBuildWithdrawTxMutationRequest,
  AccountControllerBuildWithdrawTxMutationResponse,
} from "@/gen-backend/types/account-controller-build-withdraw-tx";

export const accountControllerBuildWithdrawTxMutationKey = () =>
  [{ url: "/api/account/withdraw" }] as const;

export type AccountControllerBuildWithdrawTxMutationKey = ReturnType<
  typeof accountControllerBuildWithdrawTxMutationKey
>;

export function accountControllerBuildWithdrawTxMutationOptions(
  config: Partial<RequestConfig<AccountControllerBuildWithdrawTxMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = accountControllerBuildWithdrawTxMutationKey();
  return mutationOptions<
    AccountControllerBuildWithdrawTxMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AccountControllerBuildWithdrawTxMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return accountControllerBuildWithdrawTx(data, config);
    },
  });
}

/**
 * @summary Build unsigned withdraw transaction from keeper wallet
 * {@link /api/account/withdraw}
 */
export function useAccountControllerBuildWithdrawTx<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AccountControllerBuildWithdrawTxMutationResponse,
      ResponseErrorConfig<Error>,
      { data?: AccountControllerBuildWithdrawTxMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AccountControllerBuildWithdrawTxMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? accountControllerBuildWithdrawTxMutationKey();

  const baseOptions = accountControllerBuildWithdrawTxMutationOptions(config) as UseMutationOptions<
    AccountControllerBuildWithdrawTxMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AccountControllerBuildWithdrawTxMutationRequest },
    TContext
  >;

  return useMutation<
    AccountControllerBuildWithdrawTxMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AccountControllerBuildWithdrawTxMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AccountControllerBuildWithdrawTxMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AccountControllerBuildWithdrawTxMutationRequest },
    TContext
  >;
}
