/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { adminControllerGetDashboard } from "@/gen-backend/client/admin-controller-get-dashboard";
import type { AdminControllerGetDashboardQueryResponse } from "@/gen-backend/types/admin-controller-get-dashboard";

export const adminControllerGetDashboardSuspenseQueryKey = () =>
  [{ url: "/api/admin/dashboard" }] as const;

export type AdminControllerGetDashboardSuspenseQueryKey = ReturnType<
  typeof adminControllerGetDashboardSuspenseQueryKey
>;

export function adminControllerGetDashboardSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = adminControllerGetDashboardSuspenseQueryKey();
  return queryOptions<
    AdminControllerGetDashboardQueryResponse,
    ResponseErrorConfig<Error>,
    AdminControllerGetDashboardQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return adminControllerGetDashboard(config);
    },
  });
}

/**
 * @summary Get admin dashboard stats
 * {@link /api/admin/dashboard}
 */
export function useAdminControllerGetDashboardSuspense<
  TData = AdminControllerGetDashboardQueryResponse,
  TQueryKey extends QueryKey = AdminControllerGetDashboardSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        AdminControllerGetDashboardQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? adminControllerGetDashboardSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...adminControllerGetDashboardSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
