/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerChallenge } from "@/gen-backend/client/auth-controller-challenge";
import type {
  AuthControllerChallengeMutationRequest,
  AuthControllerChallengeMutationResponse,
} from "@/gen-backend/types/auth-controller-challenge";

export const authControllerChallengeMutationKey = () => [{ url: "/api/auth/challenge" }] as const;

export type AuthControllerChallengeMutationKey = ReturnType<
  typeof authControllerChallengeMutationKey
>;

export function authControllerChallengeMutationOptions(
  config: Partial<RequestConfig<AuthControllerChallengeMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = authControllerChallengeMutationKey();
  return mutationOptions<
    AuthControllerChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerChallengeMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return authControllerChallenge(data, config);
    },
  });
}

/**
 * @summary Request a challenge nonce for wallet authentication
 * {@link /api/auth/challenge}
 */
export function useAuthControllerChallenge<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AuthControllerChallengeMutationResponse,
      ResponseErrorConfig<Error>,
      { data?: AuthControllerChallengeMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AuthControllerChallengeMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authControllerChallengeMutationKey();

  const baseOptions = authControllerChallengeMutationOptions(config) as UseMutationOptions<
    AuthControllerChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerChallengeMutationRequest },
    TContext
  >;

  return useMutation<
    AuthControllerChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerChallengeMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AuthControllerChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerChallengeMutationRequest },
    TContext
  >;
}
