/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountControllerGetPositionQueryResponse, AccountControllerGetPositionPathParams } from "@/gen-backend/types/account-controller-get-position";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { accountControllerGetPosition } from "@/gen-backend/client/account-controller-get-position";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountControllerGetPositionQueryKey = (publicKey: AccountControllerGetPositionPathParams["publicKey"] | undefined) => [{ url: '/api/account/position/:publicKey', params: {publicKey:publicKey} }] as const

export type AccountControllerGetPositionQueryKey = ReturnType<typeof accountControllerGetPositionQueryKey>

export function accountControllerGetPositionQueryOptions(publicKey: AccountControllerGetPositionPathParams["publicKey"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = accountControllerGetPositionQueryKey(publicKey)
        return queryOptions<AccountControllerGetPositionQueryResponse, ResponseErrorConfig<Error>, AccountControllerGetPositionQueryResponse, typeof queryKey>({
         enabled: !!(publicKey),
         queryKey,
         queryFn: async ({ signal }) => {
            return accountControllerGetPosition(publicKey!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get current position and P&L for a managed account
 * {@link /api/account/position/:publicKey}
 */
export function useAccountControllerGetPosition<TData = AccountControllerGetPositionQueryResponse, TQueryData = AccountControllerGetPositionQueryResponse, TQueryKey extends QueryKey = AccountControllerGetPositionQueryKey>(publicKey: AccountControllerGetPositionPathParams["publicKey"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<AccountControllerGetPositionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? accountControllerGetPositionQueryKey(publicKey)
         

         const query = useQuery({
          ...accountControllerGetPositionQueryOptions(publicKey, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}