/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountControllerGetTradingAccountQueryResponse } from "@/gen-backend/types/account-controller-get-trading-account";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { accountControllerGetTradingAccount } from "@/gen-backend/client/account-controller-get-trading-account";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountControllerGetTradingAccountQueryKey = () => [{ url: '/api/account/trading-account' }] as const

export type AccountControllerGetTradingAccountQueryKey = ReturnType<typeof accountControllerGetTradingAccountQueryKey>

export function accountControllerGetTradingAccountQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = accountControllerGetTradingAccountQueryKey()
        return queryOptions<AccountControllerGetTradingAccountQueryResponse, ResponseErrorConfig<Error>, AccountControllerGetTradingAccountQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return accountControllerGetTradingAccount({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Check if user has a TRADING KeeperWallet
 * {@link /api/account/trading-account}
 */
export function useAccountControllerGetTradingAccount<TData = AccountControllerGetTradingAccountQueryResponse, TQueryData = AccountControllerGetTradingAccountQueryResponse, TQueryKey extends QueryKey = AccountControllerGetTradingAccountQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AccountControllerGetTradingAccountQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? accountControllerGetTradingAccountQueryKey()
         

         const query = useQuery({
          ...accountControllerGetTradingAccountQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}