/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminAuthControllerWalletLoginMutationRequest, AdminAuthControllerWalletLoginMutationResponse } from "@/gen-backend/types/admin-auth-controller-wallet-login";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminAuthControllerWalletLogin } from "@/gen-backend/client/admin-auth-controller-wallet-login";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminAuthControllerWalletLoginMutationKey = () => [{ url: '/api/admin-auth/wallet-login' }] as const

export type AdminAuthControllerWalletLoginMutationKey = ReturnType<typeof adminAuthControllerWalletLoginMutationKey>

export function adminAuthControllerWalletLoginMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AdminAuthControllerWalletLoginMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = adminAuthControllerWalletLoginMutationKey()
        return mutationOptions<AdminAuthControllerWalletLoginMutationResponse, ResponseErrorConfig<Error>, {data: AdminAuthControllerWalletLoginMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return adminAuthControllerWalletLogin(data, config)
          },
        })

}

/**
 * @summary Login with Stellar wallet signature + PIN
 * {@link /api/admin-auth/wallet-login}
 */
export function useAdminAuthControllerWalletLogin<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminAuthControllerWalletLoginMutationResponse, ResponseErrorConfig<Error>, {data: AdminAuthControllerWalletLoginMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminAuthControllerWalletLoginMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminAuthControllerWalletLoginMutationKey()

          const baseOptions = adminAuthControllerWalletLoginMutationOptions(config) as UseMutationOptions<AdminAuthControllerWalletLoginMutationResponse, ResponseErrorConfig<Error>, {data: AdminAuthControllerWalletLoginMutationRequest}, TContext>
          

          return useMutation<AdminAuthControllerWalletLoginMutationResponse, ResponseErrorConfig<Error>, {data: AdminAuthControllerWalletLoginMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminAuthControllerWalletLoginMutationResponse, ResponseErrorConfig<Error>, {data: AdminAuthControllerWalletLoginMutationRequest}, TContext>
      
}