/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthControllerLoginMutationRequest, AuthControllerLoginMutationResponse } from "@/gen-backend/types/auth-controller-login";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authControllerLogin } from "@/gen-backend/client/auth-controller-login";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authControllerLoginMutationKey = () => [{ url: '/api/auth/login' }] as const

export type AuthControllerLoginMutationKey = ReturnType<typeof authControllerLoginMutationKey>

export function authControllerLoginMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AuthControllerLoginMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = authControllerLoginMutationKey()
        return mutationOptions<AuthControllerLoginMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerLoginMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return authControllerLogin(data, config)
          },
        })

}

/**
 * @summary Admin login with username/password
 * {@link /api/auth/login}
 */
export function useAuthControllerLogin<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthControllerLoginMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerLoginMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthControllerLoginMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? authControllerLoginMutationKey()

          const baseOptions = authControllerLoginMutationOptions(config) as UseMutationOptions<AuthControllerLoginMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerLoginMutationRequest}, TContext>
          

          return useMutation<AuthControllerLoginMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerLoginMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AuthControllerLoginMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerLoginMutationRequest}, TContext>
      
}