/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceAdminControllerExportPublishersQueryResponse } from "@/gen-backend/types/marketplace-admin-controller-export-publishers";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { marketplaceAdminControllerExportPublishers } from "@/gen-backend/client/marketplace-admin-controller-export-publishers";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const marketplaceAdminControllerExportPublishersSuspenseQueryKey = () => [{ url: '/api/admin/marketplace/publishers/export' }] as const

export type MarketplaceAdminControllerExportPublishersSuspenseQueryKey = ReturnType<typeof marketplaceAdminControllerExportPublishersSuspenseQueryKey>

export function marketplaceAdminControllerExportPublishersSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceAdminControllerExportPublishersSuspenseQueryKey()
        return queryOptions<MarketplaceAdminControllerExportPublishersQueryResponse, ResponseErrorConfig<Error>, MarketplaceAdminControllerExportPublishersQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceAdminControllerExportPublishers({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Export strategy publishers as CSV
 * {@link /api/admin/marketplace/publishers/export}
 */
export function useMarketplaceAdminControllerExportPublishersSuspense<TData = MarketplaceAdminControllerExportPublishersQueryResponse, TQueryKey extends QueryKey = MarketplaceAdminControllerExportPublishersSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<MarketplaceAdminControllerExportPublishersQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceAdminControllerExportPublishersSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...marketplaceAdminControllerExportPublishersSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}