/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerVerifySessionForAi } from "@/gen-backend/client/auth-controller-verify-session-for-ai";
import type {
  AuthControllerVerifySessionForAiMutationRequest,
  AuthControllerVerifySessionForAiMutationResponse,
} from "@/gen-backend/types/auth-controller-verify-session-for-ai";

export const authControllerVerifySessionForAiMutationKey = () =>
  [{ url: "/api/auth/internal/verify-session" }] as const;

export type AuthControllerVerifySessionForAiMutationKey = ReturnType<
  typeof authControllerVerifySessionForAiMutationKey
>;

export function authControllerVerifySessionForAiMutationOptions(
  config: Partial<RequestConfig<AuthControllerVerifySessionForAiMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = authControllerVerifySessionForAiMutationKey();
  return mutationOptions<
    AuthControllerVerifySessionForAiMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerVerifySessionForAiMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return authControllerVerifySessionForAi(data, config);
    },
  });
}

/**
 * {@link /api/auth/internal/verify-session}
 */
export function useAuthControllerVerifySessionForAi<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AuthControllerVerifySessionForAiMutationResponse,
      ResponseErrorConfig<Error>,
      { data?: AuthControllerVerifySessionForAiMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AuthControllerVerifySessionForAiMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authControllerVerifySessionForAiMutationKey();

  const baseOptions = authControllerVerifySessionForAiMutationOptions(config) as UseMutationOptions<
    AuthControllerVerifySessionForAiMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerVerifySessionForAiMutationRequest },
    TContext
  >;

  return useMutation<
    AuthControllerVerifySessionForAiMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerVerifySessionForAiMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AuthControllerVerifySessionForAiMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerVerifySessionForAiMutationRequest },
    TContext
  >;
}
