/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsersControllerGetMyCampaignsQueryResponse, UsersControllerGetMyCampaignsQueryParams } from "@/gen-backend/types/users-controller-get-my-campaigns";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { usersControllerGetMyCampaigns } from "@/gen-backend/client/users-controller-get-my-campaigns";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const usersControllerGetMyCampaignsSuspenseQueryKey = (params?: UsersControllerGetMyCampaignsQueryParams) => [{ url: '/api/quest/users/me/campaign' }, ...(params ? [params] : [])] as const

export type UsersControllerGetMyCampaignsSuspenseQueryKey = ReturnType<typeof usersControllerGetMyCampaignsSuspenseQueryKey>

export function usersControllerGetMyCampaignsSuspenseQueryOptions(params?: UsersControllerGetMyCampaignsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = usersControllerGetMyCampaignsSuspenseQueryKey(params)
        return queryOptions<UsersControllerGetMyCampaignsQueryResponse, ResponseErrorConfig<Error>, UsersControllerGetMyCampaignsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return usersControllerGetMyCampaigns(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/quest/users/me/campaign}
 */
export function useUsersControllerGetMyCampaignsSuspense<TData = UsersControllerGetMyCampaignsQueryResponse, TQueryKey extends QueryKey = UsersControllerGetMyCampaignsSuspenseQueryKey>(params?: UsersControllerGetMyCampaignsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<UsersControllerGetMyCampaignsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? usersControllerGetMyCampaignsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...usersControllerGetMyCampaignsSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}