/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { poolsControllerGetPools } from "@/gen-backend/client/pools-controller-get-pools";
import type {
  PoolsControllerGetPoolsQueryParams,
  PoolsControllerGetPoolsQueryResponse,
} from "@/gen-backend/types/pools-controller-get-pools";

export const poolsControllerGetPoolsQueryKey = (params?: PoolsControllerGetPoolsQueryParams) =>
  [{ url: "/api/pools" }, ...(params ? [params] : [])] as const;

export type PoolsControllerGetPoolsQueryKey = ReturnType<typeof poolsControllerGetPoolsQueryKey>;

export function poolsControllerGetPoolsQueryOptions(
  params?: PoolsControllerGetPoolsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = poolsControllerGetPoolsQueryKey(params);
  return queryOptions<
    PoolsControllerGetPoolsQueryResponse,
    ResponseErrorConfig<Error>,
    PoolsControllerGetPoolsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return poolsControllerGetPools(params, config);
    },
  });
}

/**
 * {@link /api/pools}
 */
export function usePoolsControllerGetPools<
  TData = PoolsControllerGetPoolsQueryResponse,
  TQueryData = PoolsControllerGetPoolsQueryResponse,
  TQueryKey extends QueryKey = PoolsControllerGetPoolsQueryKey,
>(
  params?: PoolsControllerGetPoolsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        PoolsControllerGetPoolsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? poolsControllerGetPoolsQueryKey(params);

  const query = useQuery(
    {
      ...poolsControllerGetPoolsQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
