/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarketplaceControllerListStrategiesQueryResponse, MarketplaceControllerListStrategiesQueryParams } from "@/gen-backend/types/marketplace-controller-list-strategies";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { marketplaceControllerListStrategies } from "@/gen-backend/client/marketplace-controller-list-strategies";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const marketplaceControllerListStrategiesSuspenseQueryKey = (params: MarketplaceControllerListStrategiesQueryParams) => [{ url: '/api/marketplace/strategies' }, ...(params ? [params] : [])] as const

export type MarketplaceControllerListStrategiesSuspenseQueryKey = ReturnType<typeof marketplaceControllerListStrategiesSuspenseQueryKey>

export function marketplaceControllerListStrategiesSuspenseQueryOptions(params: MarketplaceControllerListStrategiesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketplaceControllerListStrategiesSuspenseQueryKey(params)
        return queryOptions<MarketplaceControllerListStrategiesQueryResponse, ResponseErrorConfig<Error>, MarketplaceControllerListStrategiesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return marketplaceControllerListStrategies(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List approved marketplace strategies
 * {@link /api/marketplace/strategies}
 */
export function useMarketplaceControllerListStrategiesSuspense<TData = MarketplaceControllerListStrategiesQueryResponse, TQueryKey extends QueryKey = MarketplaceControllerListStrategiesSuspenseQueryKey>(params: MarketplaceControllerListStrategiesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<MarketplaceControllerListStrategiesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? marketplaceControllerListStrategiesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...marketplaceControllerListStrategiesSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}