/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerExportQuestWalletsQueryResponse } from "@/gen-backend/types/admin-controller-export-quest-wallets";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminControllerExportQuestWallets } from "@/gen-backend/client/admin-controller-export-quest-wallets";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminControllerExportQuestWalletsQueryKey = () => [{ url: '/api/admin/quest-wallets/export' }] as const

export type AdminControllerExportQuestWalletsQueryKey = ReturnType<typeof adminControllerExportQuestWalletsQueryKey>

export function adminControllerExportQuestWalletsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerExportQuestWalletsQueryKey()
        return queryOptions<AdminControllerExportQuestWalletsQueryResponse, ResponseErrorConfig<Error>, AdminControllerExportQuestWalletsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerExportQuestWallets({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Export full quest wallet leaderboard as CSV
 * {@link /api/admin/quest-wallets/export}
 */
export function useAdminControllerExportQuestWallets<TData = AdminControllerExportQuestWalletsQueryResponse, TQueryData = AdminControllerExportQuestWalletsQueryResponse, TQueryKey extends QueryKey = AdminControllerExportQuestWalletsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AdminControllerExportQuestWalletsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerExportQuestWalletsQueryKey()
         

         const query = useQuery({
          ...adminControllerExportQuestWalletsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}