/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerExportQuestCampaignsQueryResponse } from "@/gen-backend/types/admin-controller-export-quest-campaigns";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminControllerExportQuestCampaigns } from "@/gen-backend/client/admin-controller-export-quest-campaigns";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminControllerExportQuestCampaignsSuspenseQueryKey = () => [{ url: '/api/admin/quest-campaigns/export' }] as const

export type AdminControllerExportQuestCampaignsSuspenseQueryKey = ReturnType<typeof adminControllerExportQuestCampaignsSuspenseQueryKey>

export function adminControllerExportQuestCampaignsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerExportQuestCampaignsSuspenseQueryKey()
        return queryOptions<AdminControllerExportQuestCampaignsQueryResponse, ResponseErrorConfig<Error>, AdminControllerExportQuestCampaignsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerExportQuestCampaigns({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Export all quest campaigns as CSV
 * {@link /api/admin/quest-campaigns/export}
 */
export function useAdminControllerExportQuestCampaignsSuspense<TData = AdminControllerExportQuestCampaignsQueryResponse, TQueryKey extends QueryKey = AdminControllerExportQuestCampaignsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminControllerExportQuestCampaignsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerExportQuestCampaignsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...adminControllerExportQuestCampaignsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}