/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminControllerListTierBandsQueryResponse } from "@/gen-backend/types/admin-controller-list-tier-bands";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminControllerListTierBands } from "@/gen-backend/client/admin-controller-list-tier-bands";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminControllerListTierBandsSuspenseQueryKey = () => [{ url: '/api/admin/tier-bands' }] as const

export type AdminControllerListTierBandsSuspenseQueryKey = ReturnType<typeof adminControllerListTierBandsSuspenseQueryKey>

export function adminControllerListTierBandsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerListTierBandsSuspenseQueryKey()
        return queryOptions<AdminControllerListTierBandsQueryResponse, ResponseErrorConfig<Error>, AdminControllerListTierBandsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return adminControllerListTierBands({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List points-to-reach-tier thresholds
 * {@link /api/admin/tier-bands}
 */
export function useAdminControllerListTierBandsSuspense<TData = AdminControllerListTierBandsQueryResponse, TQueryKey extends QueryKey = AdminControllerListTierBandsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminControllerListTierBandsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? adminControllerListTierBandsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...adminControllerListTierBandsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}