/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerResolveChatUserForAi } from "@/gen-backend/client/auth-controller-resolve-chat-user-for-ai";
import type {
  AuthControllerResolveChatUserForAiMutationRequest,
  AuthControllerResolveChatUserForAiMutationResponse,
} from "@/gen-backend/types/auth-controller-resolve-chat-user-for-ai";

export const authControllerResolveChatUserForAiMutationKey = () =>
  [{ url: "/api/auth/internal/resolve-chat-user" }] as const;

export type AuthControllerResolveChatUserForAiMutationKey = ReturnType<
  typeof authControllerResolveChatUserForAiMutationKey
>;

export function authControllerResolveChatUserForAiMutationOptions(
  config: Partial<RequestConfig<AuthControllerResolveChatUserForAiMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = authControllerResolveChatUserForAiMutationKey();
  return mutationOptions<
    AuthControllerResolveChatUserForAiMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerResolveChatUserForAiMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return authControllerResolveChatUserForAi(data, config);
    },
  });
}

/**
 * {@link /api/auth/internal/resolve-chat-user}
 */
export function useAuthControllerResolveChatUserForAi<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AuthControllerResolveChatUserForAiMutationResponse,
      ResponseErrorConfig<Error>,
      { data?: AuthControllerResolveChatUserForAiMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AuthControllerResolveChatUserForAiMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? authControllerResolveChatUserForAiMutationKey();

  const baseOptions = authControllerResolveChatUserForAiMutationOptions(
    config
  ) as UseMutationOptions<
    AuthControllerResolveChatUserForAiMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerResolveChatUserForAiMutationRequest },
    TContext
  >;

  return useMutation<
    AuthControllerResolveChatUserForAiMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerResolveChatUserForAiMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AuthControllerResolveChatUserForAiMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerResolveChatUserForAiMutationRequest },
    TContext
  >;
}
