/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthControllerMeQueryResponse } from "@/gen-backend/types/auth-controller-me";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { authControllerMe } from "@/gen-backend/client/auth-controller-me";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const authControllerMeSuspenseQueryKey = () => [{ url: '/api/auth/me' }] as const

export type AuthControllerMeSuspenseQueryKey = ReturnType<typeof authControllerMeSuspenseQueryKey>

export function authControllerMeSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = authControllerMeSuspenseQueryKey()
        return queryOptions<AuthControllerMeQueryResponse, ResponseErrorConfig<Error>, AuthControllerMeQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return authControllerMe({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Rehydrate session from tasmil_auth httpOnly cookie
 * {@link /api/auth/me}
 */
export function useAuthControllerMeSuspense<TData = AuthControllerMeQueryResponse, TQueryKey extends QueryKey = AuthControllerMeSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AuthControllerMeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? authControllerMeSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...authControllerMeSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}