/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryClient, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { welcomeRewardControllerTrackTransaction } from "@/gen-backend/client/welcome-reward-controller-track-transaction";
import type {
  WelcomeRewardControllerTrackTransactionMutationRequest,
  WelcomeRewardControllerTrackTransactionMutationResponse,
} from "@/gen-backend/types/welcome-reward-controller-track-transaction";

export const welcomeRewardControllerTrackTransactionMutationKey = () =>
  [{ url: "/api/welcome-reward/track" }] as const;

export type WelcomeRewardControllerTrackTransactionMutationKey = ReturnType<
  typeof welcomeRewardControllerTrackTransactionMutationKey
>;

export function welcomeRewardControllerTrackTransactionMutationOptions(
  config: Partial<RequestConfig<WelcomeRewardControllerTrackTransactionMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = welcomeRewardControllerTrackTransactionMutationKey();
  return mutationOptions<
    WelcomeRewardControllerTrackTransactionMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WelcomeRewardControllerTrackTransactionMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return welcomeRewardControllerTrackTransaction(data, config);
    },
  });
}

/**
 * @summary Track a memo-marked transaction hash for welcome reward volume
 * {@link /api/welcome-reward/track}
 */
export function useWelcomeRewardControllerTrackTransaction<TContext>(
  options: {
    mutation?: UseMutationOptions<
      WelcomeRewardControllerTrackTransactionMutationResponse,
      ResponseErrorConfig<Error>,
      { data: WelcomeRewardControllerTrackTransactionMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<WelcomeRewardControllerTrackTransactionMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? welcomeRewardControllerTrackTransactionMutationKey();

  const baseOptions = welcomeRewardControllerTrackTransactionMutationOptions(
    config
  ) as UseMutationOptions<
    WelcomeRewardControllerTrackTransactionMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WelcomeRewardControllerTrackTransactionMutationRequest },
    TContext
  >;

  return useMutation<
    WelcomeRewardControllerTrackTransactionMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WelcomeRewardControllerTrackTransactionMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    WelcomeRewardControllerTrackTransactionMutationResponse,
    ResponseErrorConfig<Error>,
    { data: WelcomeRewardControllerTrackTransactionMutationRequest },
    TContext
  >;
}
