/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PortfolioControllerGetHistoryQueryResponse, PortfolioControllerGetHistoryPathParams, PortfolioControllerGetHistoryQueryParams } from "@/gen-backend/types/portfolio-controller-get-history";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { portfolioControllerGetHistory } from "@/gen-backend/client/portfolio-controller-get-history";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const portfolioControllerGetHistorySuspenseQueryKey = (address: PortfolioControllerGetHistoryPathParams["address"] | undefined, params?: PortfolioControllerGetHistoryQueryParams) => [{ url: '/api/portfolio/history/:address', params: {address:address} }, ...(params ? [params] : [])] as const

export type PortfolioControllerGetHistorySuspenseQueryKey = ReturnType<typeof portfolioControllerGetHistorySuspenseQueryKey>

export function portfolioControllerGetHistorySuspenseQueryOptions(address: PortfolioControllerGetHistoryPathParams["address"] | undefined, params?: PortfolioControllerGetHistoryQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = portfolioControllerGetHistorySuspenseQueryKey(address, params)
        return queryOptions<PortfolioControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, PortfolioControllerGetHistoryQueryResponse, typeof queryKey>({
         enabled: !!(address),
         queryKey,
         queryFn: async ({ signal }) => {
            return portfolioControllerGetHistory(address!, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get portfolio value history for an address
 * {@link /api/portfolio/history/:address}
 */
export function usePortfolioControllerGetHistorySuspense<TData = PortfolioControllerGetHistoryQueryResponse, TQueryKey extends QueryKey = PortfolioControllerGetHistorySuspenseQueryKey>(address: PortfolioControllerGetHistoryPathParams["address"] | undefined, params?: PortfolioControllerGetHistoryQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<PortfolioControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? portfolioControllerGetHistorySuspenseQueryKey(address, params)
         

         const query = useSuspenseQuery({
          ...portfolioControllerGetHistorySuspenseQueryOptions(address, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}