/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { waitlistControllerVerifyReferral } from "@/gen-backend/client/waitlist-controller-verify-referral";
import type {
  WaitlistControllerVerifyReferralQueryParams,
  WaitlistControllerVerifyReferralQueryResponse,
} from "@/gen-backend/types/waitlist-controller-verify-referral";

export const waitlistControllerVerifyReferralQueryKey = (
  params: WaitlistControllerVerifyReferralQueryParams
) => [{ url: "/api/waitlist/verify-referral" }, ...(params ? [params] : [])] as const;

export type WaitlistControllerVerifyReferralQueryKey = ReturnType<
  typeof waitlistControllerVerifyReferralQueryKey
>;

export function waitlistControllerVerifyReferralQueryOptions(
  params: WaitlistControllerVerifyReferralQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = waitlistControllerVerifyReferralQueryKey(params);
  return queryOptions<
    WaitlistControllerVerifyReferralQueryResponse,
    ResponseErrorConfig<Error>,
    WaitlistControllerVerifyReferralQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return waitlistControllerVerifyReferral(params, config);
    },
  });
}

/**
 * @summary Verify a referral code is valid
 * {@link /api/waitlist/verify-referral}
 */
export function useWaitlistControllerVerifyReferral<
  TData = WaitlistControllerVerifyReferralQueryResponse,
  TQueryData = WaitlistControllerVerifyReferralQueryResponse,
  TQueryKey extends QueryKey = WaitlistControllerVerifyReferralQueryKey,
>(
  params: WaitlistControllerVerifyReferralQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        WaitlistControllerVerifyReferralQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? waitlistControllerVerifyReferralQueryKey(params);

  const query = useQuery(
    {
      ...waitlistControllerVerifyReferralQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
