/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RebalanceControllerGetStatusQueryResponse } from "@/gen-backend/types/rebalance-controller-get-status";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { rebalanceControllerGetStatus } from "@/gen-backend/client/rebalance-controller-get-status";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const rebalanceControllerGetStatusSuspenseQueryKey = () => [{ url: '/api/rebalance/status' }] as const

export type RebalanceControllerGetStatusSuspenseQueryKey = ReturnType<typeof rebalanceControllerGetStatusSuspenseQueryKey>

export function rebalanceControllerGetStatusSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = rebalanceControllerGetStatusSuspenseQueryKey()
        return queryOptions<RebalanceControllerGetStatusQueryResponse, ResponseErrorConfig<Error>, RebalanceControllerGetStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return rebalanceControllerGetStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get rebalance bot status
 * {@link /api/rebalance/status}
 */
export function useRebalanceControllerGetStatusSuspense<TData = RebalanceControllerGetStatusQueryResponse, TQueryKey extends QueryKey = RebalanceControllerGetStatusSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<RebalanceControllerGetStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? rebalanceControllerGetStatusSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...rebalanceControllerGetStatusSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}