/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type {
  QueryClient,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { accountControllerGetPresets } from "@/gen-backend/client/account-controller-get-presets";
import type {
  AccountControllerGetPresetsQueryParams,
  AccountControllerGetPresetsQueryResponse,
} from "@/gen-backend/types/account-controller-get-presets";

export const accountControllerGetPresetsSuspenseQueryKey = (
  params: AccountControllerGetPresetsQueryParams
) => [{ url: "/api/account/presets" }, ...(params ? [params] : [])] as const;

export type AccountControllerGetPresetsSuspenseQueryKey = ReturnType<
  typeof accountControllerGetPresetsSuspenseQueryKey
>;

export function accountControllerGetPresetsSuspenseQueryOptions(
  params: AccountControllerGetPresetsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = accountControllerGetPresetsSuspenseQueryKey(params);
  return queryOptions<
    AccountControllerGetPresetsQueryResponse,
    ResponseErrorConfig<Error>,
    AccountControllerGetPresetsQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return accountControllerGetPresets(params, config);
    },
  });
}

/**
 * @summary Get preset card data with live APY estimates
 * {@link /api/account/presets}
 */
export function useAccountControllerGetPresetsSuspense<
  TData = AccountControllerGetPresetsQueryResponse,
  TQueryKey extends QueryKey = AccountControllerGetPresetsSuspenseQueryKey,
>(
  params: AccountControllerGetPresetsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        AccountControllerGetPresetsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? accountControllerGetPresetsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...accountControllerGetPresetsSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
