/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AccountControllerWithdrawTrading201 = any;

export type AccountControllerWithdrawTradingMutationResponse = AccountControllerWithdrawTrading201;

export type AccountControllerWithdrawTradingMutation = {
  Response: AccountControllerWithdrawTrading201;
  Errors: any;
};
