/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AccountControllerGetTradingAccount200 = any;

export type AccountControllerGetTradingAccountQueryResponse = AccountControllerGetTradingAccount200;

export type AccountControllerGetTradingAccountQuery = {
    Response: AccountControllerGetTradingAccount200;
    Errors: any;
};