/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateCampaignDto } from "@/gen-quest/types/create-campaign-dto";

export type AdminControllerCreateCampaign201 = any;

export type AdminControllerCreateCampaignMutationRequest = CreateCampaignDto;

export type AdminControllerCreateCampaignMutationResponse = AdminControllerCreateCampaign201;

export type AdminControllerCreateCampaignMutation = {
    Response: AdminControllerCreateCampaign201;
    Request: AdminControllerCreateCampaignMutationRequest;
    Errors: any;
};