/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AdminSponsorshipControllerGetConfig200 = any;

export type AdminSponsorshipControllerGetConfigQueryResponse =
  AdminSponsorshipControllerGetConfig200;

export type AdminSponsorshipControllerGetConfigQuery = {
  Response: AdminSponsorshipControllerGetConfig200;
  Errors: any;
};
