/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateSeasonDto } from "@/gen-quest/types/create-season-dto";

export type AdminSeasonsControllerCreate201 = any;

export type AdminSeasonsControllerCreateMutationRequest = CreateSeasonDto;

export type AdminSeasonsControllerCreateMutationResponse = AdminSeasonsControllerCreate201;

export type AdminSeasonsControllerCreateMutation = {
  Response: AdminSeasonsControllerCreate201;
  Request: AdminSeasonsControllerCreateMutationRequest;
  Errors: any;
};
