/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminSeasonsControllerEndPathParams = {
    /**
     * @type string
    */
    id: string;
};

export type AdminSeasonsControllerEnd201 = any;

export type AdminSeasonsControllerEndMutationResponse = AdminSeasonsControllerEnd201;

export type AdminSeasonsControllerEndMutation = {
    Response: AdminSeasonsControllerEnd201;
    PathParams: AdminSeasonsControllerEndPathParams;
    Errors: any;
};