/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerCreateSharedCode201 = any;

export type AdminControllerCreateSharedCodeMutationResponse = AdminControllerCreateSharedCode201;

export type AdminControllerCreateSharedCodeMutation = {
    Response: AdminControllerCreateSharedCode201;
    Errors: any;
};