/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateSeasonDto } from "@/gen-quest/types/update-season-dto";

export type AdminSeasonsControllerUpdatePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type AdminSeasonsControllerUpdate200 = any;

export type AdminSeasonsControllerUpdateMutationRequest = UpdateSeasonDto;

export type AdminSeasonsControllerUpdateMutationResponse = AdminSeasonsControllerUpdate200;

export type AdminSeasonsControllerUpdateMutation = {
  Response: AdminSeasonsControllerUpdate200;
  Request: AdminSeasonsControllerUpdateMutationRequest;
  PathParams: AdminSeasonsControllerUpdatePathParams;
  Errors: any;
};
