/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerDeleteQuestTaskPathParams = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    taskId: string;
};

export type AdminControllerDeleteQuestTask200 = any;

export type AdminControllerDeleteQuestTaskMutationResponse = AdminControllerDeleteQuestTask200;

export type AdminControllerDeleteQuestTaskMutation = {
    Response: AdminControllerDeleteQuestTask200;
    PathParams: AdminControllerDeleteQuestTaskPathParams;
    Errors: any;
};