/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AppControllerGetHello200 = any;

export type AppControllerGetHelloQueryResponse = AppControllerGetHello200;

export type AppControllerGetHelloQuery = {
    Response: AppControllerGetHello200;
    Errors: any;
};