/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type BatchPayoutItemDto = {
    /**
     * @type string
    */
    resultId: string;
    /**
     * @type string | undefined
    */
    paidTxHash?: string;
};