/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CampaignsControllerJoinCampaignPathParams = {
    /**
     * @type string
    */
    id: string;
};

export type CampaignsControllerJoinCampaign201 = any;

export type CampaignsControllerJoinCampaignMutationResponse = CampaignsControllerJoinCampaign201;

export type CampaignsControllerJoinCampaignMutation = {
    Response: CampaignsControllerJoinCampaign201;
    PathParams: CampaignsControllerJoinCampaignPathParams;
    Errors: any;
};