/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CampaignSendDto = {
    /**
     * @type string
    */
    name: string;
    /**
     * @description Comma-separated emails. Empty = all eligible.
     * @type string | undefined
    */
    targetEmails?: string;
};