/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ChatUsageInternalControllerGetSnapshotPathParams = {
    /**
     * @type string
    */
    userId: string;
};

export type ChatUsageInternalControllerGetSnapshot200 = any;

export type ChatUsageInternalControllerGetSnapshotQueryResponse = ChatUsageInternalControllerGetSnapshot200;

export type ChatUsageInternalControllerGetSnapshotQuery = {
    Response: ChatUsageInternalControllerGetSnapshot200;
    PathParams: ChatUsageInternalControllerGetSnapshotPathParams;
    Errors: any;
};