/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DailyMissionsControllerCompletePathParams = {
    /**
     * @type string
    */
    code: string;
};

export type DailyMissionsControllerComplete201 = any;

export type DailyMissionsControllerCompleteMutationResponse = DailyMissionsControllerComplete201;

export type DailyMissionsControllerCompleteMutation = {
    Response: DailyMissionsControllerComplete201;
    PathParams: DailyMissionsControllerCompletePathParams;
    Errors: any;
};