/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GasSponsorshipControllerMe200 = any;

export type GasSponsorshipControllerMeQueryResponse = GasSponsorshipControllerMe200;

export type GasSponsorshipControllerMeQuery = {
    Response: GasSponsorshipControllerMe200;
    Errors: any;
};