/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketplaceControllerGetPublishedStrategies200 = any;

export type MarketplaceControllerGetPublishedStrategiesQueryResponse = MarketplaceControllerGetPublishedStrategies200;

export type MarketplaceControllerGetPublishedStrategiesQuery = {
    Response: MarketplaceControllerGetPublishedStrategies200;
    Errors: any;
};