/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketplaceControllerListPendingStrategies200 = any;

export type MarketplaceControllerListPendingStrategiesQueryResponse = MarketplaceControllerListPendingStrategies200;

export type MarketplaceControllerListPendingStrategiesQuery = {
    Response: MarketplaceControllerListPendingStrategies200;
    Errors: any;
};