/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MarketplaceControllerGetFeeBalance200 = any;

export type MarketplaceControllerGetFeeBalanceQueryResponse = MarketplaceControllerGetFeeBalance200;

export type MarketplaceControllerGetFeeBalanceQuery = {
  Response: MarketplaceControllerGetFeeBalance200;
  Errors: any;
};
