/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MarketplaceControllerGetPublisherClaims200 = any;

export type MarketplaceControllerGetPublisherClaimsQueryResponse =
  MarketplaceControllerGetPublisherClaims200;

export type MarketplaceControllerGetPublisherClaimsQuery = {
  Response: MarketplaceControllerGetPublisherClaims200;
  Errors: any;
};
