/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProtocolControllerGetAvailableAssetsQueryParams = {
    /**
     * @type string
    */
    chain: string;
};

/**
 * @description Returns list of available assets on the specified chain
*/
export type ProtocolControllerGetAvailableAssets200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type string | undefined
        */
        chain?: string;
        /**
         * @type array | undefined
        */
        assets?: string[];
    };
};

export type ProtocolControllerGetAvailableAssetsQueryResponse = ProtocolControllerGetAvailableAssets200;

export type ProtocolControllerGetAvailableAssetsQuery = {
    Response: ProtocolControllerGetAvailableAssets200;
    QueryParams: ProtocolControllerGetAvailableAssetsQueryParams;
    Errors: any;
};