/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProtocolControllerGetAllApysQueryParams = {
    /**
     * @description Asset address or symbol (e.g., \"USDC\" or \"0x...\")
     * @type string
    */
    asset: string;
};

/**
 * @description Returns APY from all protocols across all chains for an asset, sorted by APY descending
*/
export type ProtocolControllerGetAllApys200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type array | undefined
    */
    data?: {
        /**
         * @type string | undefined
        */
        protocol?: string;
        /**
         * @type string | undefined
        */
        chain?: string;
        /**
         * @type string | undefined
        */
        asset?: string;
        /**
         * @type number | undefined
        */
        supplyApy?: number;
        /**
         * @type string | undefined
        */
        error?: string;
    }[];
};

export type ProtocolControllerGetAllApysQueryResponse = ProtocolControllerGetAllApys200;

export type ProtocolControllerGetAllApysQuery = {
    Response: ProtocolControllerGetAllApys200;
    QueryParams: ProtocolControllerGetAllApysQueryParams;
    Errors: any;
};