/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RebalanceControllerGetStatus200 = any;

export type RebalanceControllerGetStatusQueryResponse = RebalanceControllerGetStatus200;

export type RebalanceControllerGetStatusQuery = {
    Response: RebalanceControllerGetStatus200;
    Errors: any;
};