/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const registerWalletDtoWalletProviderEnum = {
    FREIGHTER: "FREIGHTER",
    ALBEDO: "ALBEDO",
    XBull: "XBull",
    OTHER: "OTHER"
} as const;

export type RegisterWalletDtoWalletProviderEnumKey = (typeof registerWalletDtoWalletProviderEnum)[keyof typeof registerWalletDtoWalletProviderEnum];

export type RegisterWalletDto = {
    /**
     * @type string
    */
    walletAddress: string;
    /**
     * @type string
    */
    walletProvider: RegisterWalletDtoWalletProviderEnumKey;
    /**
     * @type string | undefined
    */
    signedChallenge?: string;
    /**
     * @type string | undefined
    */
    referredByCode?: string;
    /**
     * @type string | undefined
    */
    source?: string;
};