/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RequestChallengeDto = {
    /**
     * @description Stellar public key (G...)
     * @type string
    */
    walletAddress: string;
};