/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SeasonsControllerLeaderboard200 = any;

export type SeasonsControllerLeaderboardQueryResponse = SeasonsControllerLeaderboard200;

export type SeasonsControllerLeaderboardQuery = {
  Response: SeasonsControllerLeaderboard200;
  Errors: any;
};
