/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RankRewardItemDto } from "@/gen-quest/types/rank-reward-item-dto";

export type SetRankRewardsDto = {
    /**
     * @type array
    */
    rewards: RankRewardItemDto[];
};