/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SponsorAdminControllerGetSponsorBalance200 = any;

export type SponsorAdminControllerGetSponsorBalanceQueryResponse = SponsorAdminControllerGetSponsorBalance200;

export type SponsorAdminControllerGetSponsorBalanceQuery = {
    Response: SponsorAdminControllerGetSponsorBalance200;
    Errors: any;
};