/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateTopupQuoteDto } from "@/gen-quest/types/create-topup-quote-dto";

export type TopupControllerCreateQuote201 = any;

export type TopupControllerCreateQuoteMutationRequest = CreateTopupQuoteDto;

export type TopupControllerCreateQuoteMutationResponse = TopupControllerCreateQuote201;

export type TopupControllerCreateQuoteMutation = {
    Response: TopupControllerCreateQuote201;
    Request: TopupControllerCreateQuoteMutationRequest;
    Errors: any;
};