/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateFomoEventDto = {
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    startAt?: string;
    /**
     * @type string | undefined
    */
    endAt?: string;
    /**
     * @minLength 1
     * @type number | undefined
    */
    multiplier?: number;
    /**
     * @default 3
     * @type number | undefined
    */
    countdownDays?: number;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
};