/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateReferralConfigDto = {
  /**
   * @description Commission rate in basis points
   * @minLength 0
   * @maxLength 10000
   * @type number
   */
  rateBps: number;
  /**
   * @description Whether this layer is active
   * @type boolean | undefined
   */
  isActive?: boolean;
};
