/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateTierBandDto = {
    /**
     * @description Points required to reach this tier
     * @minLength 1
     * @type number
    */
    min: number;
};