/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UsersControllerGetCheckInStatus200 = any;

export type UsersControllerGetCheckInStatusQueryResponse = UsersControllerGetCheckInStatus200;

export type UsersControllerGetCheckInStatusQuery = {
    Response: UsersControllerGetCheckInStatus200;
    Errors: any;
};