/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateProfileDto } from "@/gen-quest/types/update-profile-dto";

export type UsersControllerUpdateProfile200 = any;

export type UsersControllerUpdateProfileMutationRequest = UpdateProfileDto;

export type UsersControllerUpdateProfileMutationResponse = UsersControllerUpdateProfile200;

export type UsersControllerUpdateProfileMutation = {
    Response: UsersControllerUpdateProfile200;
    Request: UsersControllerUpdateProfileMutationRequest;
    Errors: any;
};