/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UsersControllerGetReferrals200 = any;

export type UsersControllerGetReferralsQueryResponse = UsersControllerGetReferrals200;

export type UsersControllerGetReferralsQuery = {
  Response: UsersControllerGetReferrals200;
  Errors: any;
};
