/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UsersControllerStrategyCheckin201 = any;

export type UsersControllerStrategyCheckinMutationResponse = UsersControllerStrategyCheckin201;

export type UsersControllerStrategyCheckinMutation = {
    Response: UsersControllerStrategyCheckin201;
    Errors: any;
};