/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type VolumeIntentControllerGetMyIntents200 = any;

export type VolumeIntentControllerGetMyIntentsQueryResponse = VolumeIntentControllerGetMyIntents200;

export type VolumeIntentControllerGetMyIntentsQuery = {
  Response: VolumeIntentControllerGetMyIntents200;
  Errors: any;
};
