"use client";

import { Plus, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Typography } from "@/shared/ui/typography";

type FAQItem = {
  id: string;
  question: string;
  answer: string;
};

const faqs: FAQItem[] = [
  {
    id: "001",
    question: "What is Tasmil Finance?",
    answer:
      "Tasmil Finance is an AI-powered DeFi platform built exclusively for the U2U blockchain ecosystem. It serves as your intelligent gateway to U2U's leading DeFi protocols, combining conversational AI agents with seamless access to U2U's DeFi infrastructure through natural language interactions.",
  },
  {
    id: "002",
    question: "How does the AI agent system work on U2U?",
    answer:
      'Our AI agents act as your personal U2U DeFi assistants. Simply describe what you want to do in natural language - like "swap 100 U2U for USDC" or "find the best yield opportunity on U2U" - and the agents handle the complex protocol interactions automatically on U2U blockchain. They combine real-time U2U on-chain data with market sentiment analysis to make intelligent decisions.',
  },
  {
    id: "003",
    question: "Is my U2U wallet secure with Tasmil Finance?",
    answer:
      "Absolutely. Tasmil Finance uses a non-custodial, self-custody wallet architecture. Your private keys are stored locally in your browser and never leave your device. We cannot access your U2U funds - you maintain complete control over your assets while enjoying the convenience of AI-powered U2U DeFi interactions.",
  },
  {
    id: "004",
    question: "What makes Tasmil different from other U2U DeFi platforms?",
    answer:
      "Tasmil is the first comprehensive AI-powered gateway specifically built for U2U blockchain's DeFi ecosystem. Unlike traditional DeFi interfaces that require technical knowledge, our conversational agents make sophisticated U2U strategies accessible to everyone. Plus, our creator economy lets you build and monetize your own U2U trading agents.",
  },
  {
    id: "005",
    question: "How does the credit system and pricing work?",
    answer:
      "We offer flexible pricing with a base plan at $20/month plus credits for compute-intensive operations on U2U. You only pay additional fees when following creator agents that generate profits for you. Credits ensure priority processing and unlock advanced features like custom U2U agent building and real-time U2U market analysis.",
  },
  {
    id: "006",
    question: "Can I create my own U2U trading agents?",
    answer:
      "Yes! Our no-code agent builder lets you create sophisticated U2U DeFi strategies through simple prompts. Set your risk parameters, automation levels, and trading rules for U2U protocols, then test your strategies in our simulation environment before deploying real capital. Successful agents can be published to our marketplace for passive revenue.",
  },
  {
    id: "007",
    question: "Which U2U protocols does Tasmil integrate with?",
    answer:
      "Tasmil directly integrates with major U2U DeFi protocols including U2U-based DEXs, lending platforms, liquidity pools, and yield farming protocols. Our agents can execute complex multi-protocol strategies seamlessly across the U2U ecosystem, from yield farming to arbitrage opportunities.",
  },
  {
    id: "008",
    question: "How do I get started with Tasmil Finance on U2U?",
    answer:
      "Simply connect your U2U-compatible wallet (MetaMask, Trust Wallet, etc.) or create a new one through our platform. Start chatting with our AI agents to explore available U2U strategies, or browse our agent marketplace to find U2U strategies created by other users. Your first interactions help our AI learn your U2U DeFi preferences and risk tolerance.",
  },
  {
    id: "009",
    question: "What kind of returns can I expect on U2U?",
    answer:
      "Returns vary based on U2U market conditions and chosen strategies. Our agents analyze real-time U2U blockchain data to identify optimal opportunities across U2U lending, DEX trading, yield farming, and arbitrage. Historical performance data is available for all published U2U agents, and you can simulate strategies before committing capital.",
  },
  {
    id: "010",
    question: "How does the creator economy work on U2U?",
    answer:
      "Build profitable U2U trading agents and earn passive income when others use them. Creators earn a percentage of profits generated by their agents on U2U, with performance-based fees ensuring alignment between creators and users. Top-performing U2U agents get featured in our marketplace and can generate significant recurring revenue.",
  },
];

export const FAQSection = () => {
  const [openFAQ, setOpenFAQ] = useState<string>("001");
  const [heights, setHeights] = useState<Record<string, number>>({});
  const answerRefs = useRef<Record<string, HTMLDivElement | null>>({});

  // Initialize height for the default open FAQ
  useEffect(() => {
    if (openFAQ) {
      const element = answerRefs.current[openFAQ];
      if (element) {
        setHeights({
          [openFAQ]: element.scrollHeight,
        });
      }
    }
  }, [openFAQ]);

  const toggleFAQ = (id: string) => {
    if (openFAQ === id) {
      // Closing
      setHeights((prev) => ({ ...prev, [id]: 0 }));
      setTimeout(() => {
        setOpenFAQ("");
      }, 300); // Match this with the transition duration
    } else {
      // Opening
      const element = answerRefs.current[id];
      if (element) {
        // First set the current open one to close
        if (openFAQ) {
          setHeights((prev) => ({ ...prev, [openFAQ]: 0 }));
        }

        // Set the new one to open
        setOpenFAQ(id);

        // Need a small delay to ensure the element is in the DOM
        setTimeout(() => {
          setHeights((prev) => ({ ...prev, [id]: element.scrollHeight }));
        }, 50);
      }
    }
  };

  // Function to set a ref for a specific FAQ item
  const setAnswerRef = (id: string) => (element: HTMLDivElement | null) => {
    answerRefs.current[id] = element;
  };

  return (
    <section className="w-full bg-black">
      <div className="mx-auto w-full px-4 py-12 md:px-10 md:py-16">
        <div className="mb-12 text-center">
          <Typography as="p" className="mb-2 text-center text-xl" gradient={true} weight="semibold">
            / FAQS
          </Typography>
          <Typography
            align="center"
            className="mb-8 text-4xl md:text-5xl"
            gradient={true}
            variant="h2"
            weight="semibold"
          >
            FREQUENTLY ASKED QUESTIONS
          </Typography>
        </div>

        <div className="mx-auto w-full rounded-2xl bg-white">
          {faqs.map((faq, index) => {
            const isFirst = index === 0;
            const isLast = index === faqs.length - 1;
            const isOpen = openFAQ === faq.id;

            return (
              <div
                className={`${!isLast || isOpen ? "border-[#E5E5E5] border-b" : ""} ${
                  isFirst && isOpen ? "rounded-t-2xl" : ""
                } ${isLast && isOpen ? "rounded-b-2xl" : ""}`}
                key={faq.id}
              >
                <div
                  aria-controls={`faq-answer-${faq.id}`}
                  aria-expanded={isOpen}
                  className="flex cursor-pointer items-center justify-between px-6 py-6"
                  onClick={() => toggleFAQ(faq.id)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" || e.key === " ") {
                      e.preventDefault();
                      toggleFAQ(faq.id);
                    }
                  }}
                  role="button"
                  tabIndex={0}
                >
                  <div className="flex items-center">
                    <Typography as="span" className="mr-6 font-mono text-[#9A9BA0]">
                      {faq.id}
                    </Typography>
                    <Typography className="mb-1 text-black text-lg md:text-xl" weight="medium">
                      {faq.question}
                    </Typography>
                  </div>
                  <button className="flex h-8 w-8 items-center justify-center" type="button">
                    {isOpen ? (
                      <X className="h-6 w-6 text-black transition-transform duration-300" />
                    ) : (
                      <Plus className="h-6 w-6 text-black transition-transform duration-300" />
                    )}
                  </button>
                </div>
                <div
                  className="overflow-hidden transition-all duration-300 ease-in-out"
                  style={{
                    height: heights[faq.id] || 0,
                    opacity: heights[faq.id] ? 1 : 0,
                  }}
                >
                  <div
                    className="mx-6 mb-6 rounded-2xl bg-[#111111] p-6 pr-8 pl-16"
                    ref={setAnswerRef(faq.id)}
                  >
                    <Typography className="text-lg text-white">{faq.answer}</Typography>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};
